Repository openxla/stablehlo, pull requests merged in 2022-08, with the labels that each got.

#28 Add issue templates. Based on IREE templates.
  .github/ISSUE_TEMPLATE/bug_report.yml
  .github/ISSUE_TEMPLATE/config.yml
  .github/ISSUE_TEMPLATE/feature_request.yml
Labels: Process

#29 Pretty printing for StableHLO types.
  dialect/StablehloOps.cpp
  dialect/StablehloOps.td
  tests/infer_stablehlo.mlir
  tests/ops_sparse.mlir
  tests/ops_stablehlo.mlir
  tests/print_binary_invalid.mlir
  tests/print_stablehlo.mlir
  tests/print_types_invalid.mlir
Labels: Prettyprinting

#23 Skeleton of the StableHLO spec
  docs/spec_draft.md
Labels: Spec

#39 Allows StableHLO to be built as part of other CMake projects
  CMakeLists.txt
  tests/lit.site.cfg.py.in
Labels: Process

#41 Allow blank issues to be created.
  .github/ISSUE_TEMPLATE/config.yml
Labels: Process

#40 Add Python bindings for CHLO/StableHLO
  CMakeLists.txt
  build_tools/README.md
  integrations/CMakeLists.txt
  integrations/c/CMakeLists.txt
  integrations/c/ChloAttributes.cpp
  integrations/c/ChloAttributes.h
  integrations/c/ChloDialect.cpp
  integrations/c/ChloDialect.h
  integrations/c/StablehloAttributes.cpp
  integrations/c/StablehloAttributes.h
  integrations/c/StablehloDialect.cpp
  integrations/c/StablehloDialect.h
  integrations/c/StablehloTypes.cpp
  integrations/c/StablehloTypes.h
  integrations/python/CMakeLists.txt
  integrations/python/ChloModule.cpp
  integrations/python/StablehloModule.cpp
  integrations/python/mlir/dialects/ChloOps.td
  integrations/python/mlir/dialects/StablehloOps.td
  integrations/python/mlir/dialects/chlo.py
  integrations/python/mlir/dialects/stablehlo.py
  integrations/python/tests/CMakeLists.txt
  integrations/python/tests/smoketest.py
Labels: Integrations

#52 clarified the semantics of 0 dimension of a tensor
  docs/spec_draft.md
Labels: Spec

#56 Add specifications for maximum and minimum operators
  docs/spec_draft.md
Labels: Spec

#38 Implement pretty print for CustomCallOp, ReducePrecisionOp
  stablehlo/dialect/StablehloOps.cpp
  stablehlo/dialect/StablehloOps.td
  stablehlo/tests/print_stablehlo.mlir
  stablehlo/tests/print_types_invalid.mlir
Labels: Prettyprinting
