Repository openxla/stablehlo, pull requests merged in 2022-09, with the labels that each got.

#54 Add specifications for and, or, xor, not operators
  docs/spec_draft.md
Labels: Spec

#60 Bytecode implementation for StableHLO
  docs/bytecode.md
  stablehlo/dialect/CMakeLists.txt
  stablehlo/dialect/StablehloBytecode.cpp
  stablehlo/dialect/StablehloBytecode.h
  stablehlo/dialect/StablehloOps.cpp
  stablehlo/tests/ops_stablehlo_roundtrip.mlir
Labels: Integrations

#37 Implement pretty printing for SelectOp, ClampOp, AfterAllOp types. Clean up type prints.
  stablehlo/dialect/StablehloOps.cpp
  stablehlo/dialect/StablehloOps.td
  stablehlo/tests/print_stablehlo.mlir
  stablehlo/tests/print_types_invalid.mlir
Labels: Prettyprinting

#44 Interpreter skeleton
  docs/interpreter.md
  stablehlo/CMakeLists.txt
  stablehlo/reference/CMakeLists.txt
  stablehlo/reference/Element.cpp
  stablehlo/reference/Element.h
  stablehlo/reference/Interpreter.cpp
  stablehlo/reference/Interpreter.h
  stablehlo/reference/Ops.cpp
  stablehlo/reference/Ops.h
  stablehlo/reference/Tensor.cpp
  stablehlo/reference/Tensor.h
  stablehlo/tests/CMakeLists.txt
  stablehlo/tests/interpret_add.mlir
  stablehlo/tests/lit.cfg.py
  stablehlo/tools/CMakeLists.txt
  stablehlo/tools/StablehloInterpreterMain.cpp
Labels: Interpreter

#65 Add specifications for constant operator
  docs/spec_draft.md
Labels: Spec

#78 interpreter: Fix a few outdated links in interpreter.md file
  docs/interpreter.md
Labels: Interpreter

#66 CHLO Bytecode Implementation
  docs/bytecode.md
  stablehlo/dialect/Base.h
  stablehlo/dialect/CMakeLists.txt
  stablehlo/dialect/ChloBytecode.cpp
  stablehlo/dialect/ChloBytecode.h
  stablehlo/dialect/ChloOps.cpp
  stablehlo/dialect/StablehloBytecode.cpp
  stablehlo/tests/ops_chlo_roundtrip.mlir
Labels: Integrations

#50 Add type inference for stablehlo.reduce
  stablehlo/dialect/StablehloOps.cpp
  stablehlo/dialect/StablehloOps.td
  stablehlo/tests/infer_stablehlo.mlir
  stablehlo/tests/verify_reduce.mlir
Labels: Type inference

#67 Add type inference for stablehlo.batch_norm_* ops.
  stablehlo/dialect/StablehloOps.cpp
  stablehlo/dialect/StablehloOps.td
  stablehlo/tests/infer_stablehlo.mlir
  stablehlo/tests/ops_stablehlo.mlir
Labels: Type inference

#87 spec: Add an index of documented ops
  docs/spec_draft.md
Labels: Spec

#84 Fix examples to include operand and result names
  docs/spec_draft.md
Labels: Spec

#93 Remove "Additional context" from bug and FR templates
  .github/ISSUE_TEMPLATE/bug_report.yml
  .github/ISSUE_TEMPLATE/feature_request.yml
Labels: Process

#92 Update the "Discussions" link
  .github/ISSUE_TEMPLATE/config.yml
Labels: Process

#94 Clarify the floating point semantics of add/max/min
  docs/spec_draft.md
Labels: Spec

#72 spec-draft: floor/ceil
  docs/spec_draft.md
Labels: Spec

#74 spec-draft: negate/abs
  docs/spec_draft.md
Labels: Spec

#86 Add specifications for sine, cosine, and tanh operators
  docs/spec_draft.md
Labels: Spec

#89 Add specifications for sqrt and rsqrt operators
  docs/spec_draft.md
Labels: Spec

#102 Remove the redundant fp equality comparison function.
  stablehlo/reference/Element.cpp
  stablehlo/reference/Element.h
Labels: Interpreter

#103 Refactor constraints
  docs/spec_draft.md
Labels: Spec

#109 Update README.md with a link to GitHub discussions
  README.md
Labels: Process

#107 Add specification for logistic operator
  docs/spec_draft.md
Labels: Spec

#91 Add type inference for stablehlo.reduce_window
  stablehlo/dialect/StablehloOps.cpp
  stablehlo/dialect/StablehloOps.td
  stablehlo/tests/infer_stablehlo.mlir
  stablehlo/tests/verify_conv.mlir
  stablehlo/tests/verify_reduce_window.mlir
  stablehlo/tests/verify_select_and_scatter.mlir
Labels: Type inference

#106 Add spec of div/rem
  docs/spec_draft.md
Labels: Spec

#104 Add Python API Testing to GitHub Actions
  .github/actions/setup-build/action.yml
  .github/workflows/buildAndTest.yml
  build_tools/github_actions/ci_build_stablehlo_python_api.sh
Labels: Process

#111 Clarification on floating-point exception env.
  docs/spec_draft.md
Labels: Spec

#114 Add type inference for stablehlo.triangular_solve.
  stablehlo/dialect/StablehloOps.cpp
  stablehlo/dialect/StablehloOps.td
  stablehlo/tests/infer_stablehlo.mlir
  stablehlo/tests/ops_stablehlo.mlir
Labels: Type inference

#116 Add type inference for stablehlo.map.
  stablehlo/dialect/StablehloOps.cpp
  stablehlo/dialect/StablehloOps.td
  stablehlo/tests/infer_stablehlo.mlir
  stablehlo/tests/ops_stablehlo.mlir
Labels: Type inference

#112 Add test for constant op
  stablehlo/tests/interpret_constant.mlir
Labels: Interpreter

#123 Reorder interpret_add.mlir tests and fix typos in spec_draft.md
  docs/spec_draft.md
  stablehlo/tests/interpret_add.mlir
Labels: Interpreter

#130 Migrate away from kEmitAccessorPrefix_Raw
  stablehlo/dialect/ChloOps.cpp
  stablehlo/dialect/StablehloOps.cpp
Labels: Integrations

#124 Add TableGen targets to mlir-headers
  stablehlo/dialect/CMakeLists.txt
Labels: Build

#131 Remove mlir_runner_utils_dir replacement from lit.cfg.py
  stablehlo/tests/lit.cfg.py
  stablehlo/tests/lit.site.cfg.py.in
Labels: Integrations

#121 Tracking of completeness of the implementation
  docs/implementation_progress.md
Labels: Process

#136 Review feedback for #121
  docs/status.md
Labels: Process

#132 Integrate LLVM at llvm/llvm-project@70ac46667613
  build_tools/llvm_version.txt
Labels: Integrations

#128 Format markdown files consistently with MLIR-HLO
  README.md
  build_tools/README.md
Labels: Build

#127 Add specification for exp operator
  docs/spec_draft.md
Labels: Spec

#134 Remove GEN_PASS_CLASSES
  stablehlo/tests/TestUtils.cpp
Labels: Integrations

#141 Further tweaking of status.md
  docs/status.md
Labels: Process

#150 Switch CHLO and StableHLO to kEmitAccessorPrefix_Both
  stablehlo/dialect/ChloOps.td
  stablehlo/dialect/StablehloOps.td
Labels: Integrations

#137 Build with all warnings as errors.
  CMakeLists.txt
  stablehlo/reference/Tensor.h
Labels: Build

#139 Add interpreter for sine op
  stablehlo/reference/Element.cpp
  stablehlo/reference/Element.h
  stablehlo/reference/Interpreter.cpp
  stablehlo/reference/Ops.cpp
  stablehlo/reference/Ops.h
  stablehlo/tests/interpret_sine.mlir
Labels: Interpreter

#156 fix a bug in AddOp spec
  docs/spec_draft.md
Labels: Spec

#157 remove trailing spaces
  stablehlo/tests/infer_stablehlo.mlir
Labels: Type inference

#158 fix typos in AddOp spec
  docs/spec_draft.md
Labels: Spec

#160 Move warning and error flags into CI build flags.
  CMakeLists.txt
  build_tools/github_actions/ci_build_stablehlo.sh
Labels: Build

#176 Use auto-generated pass create functions
  stablehlo/tests/TestUtils.cpp
  stablehlo/tests/TestUtils.td
Labels: Integrations

#142 Add additional special test cases for interpret_add.mlir and interpret_constant.mlir
  stablehlo/tests/interpret_add.mlir
  stablehlo/tests/interpret_constant.mlir
Labels: Interpreter

#168 Populate progress of verifier and type inference.
  docs/status.md
Labels: Verification, Type inference, Process

#174 Add bytecode test for compare_type attr.
  stablehlo/tests/ops_chlo_roundtrip.mlir
Labels: Process

#159 Pretty print for ops with single scalar attributes
  stablehlo/dialect/StablehloOps.cpp
  stablehlo/dialect/StablehloOps.td
  stablehlo/tests/print_stablehlo.mlir
  stablehlo/tests/print_types_invalid.mlir
Labels: Prettyprinting

#135 Add type inference for stablehlo.if stablehlo.case.
  stablehlo/dialect/Base.cpp
  stablehlo/dialect/Base.h
  stablehlo/dialect/StablehloOps.cpp
  stablehlo/dialect/StablehloOps.td
  stablehlo/tests/infer_stablehlo.mlir
  stablehlo/tests/ops_stablehlo.mlir
Labels: Type inference

#184 Update prettyprint status in status.md
  docs/status.md
Labels: Prettyprinting, Process

#161 Pretty print for ops with single enum attribute
  stablehlo/dialect/StablehloEnums.td
  stablehlo/dialect/StablehloOps.cpp
  stablehlo/dialect/StablehloOps.td
  stablehlo/tests/infer_stablehlo.mlir
  stablehlo/tests/ops_stablehlo.mlir
  stablehlo/tests/ops_stablehlo_roundtrip.mlir
  stablehlo/tests/print_stablehlo.mlir
  stablehlo/tests/print_types_invalid.mlir
Labels: Prettyprinting

#183 Refactor the lint action into a build script, temporarily update .clang-format
  .clang-format
  .github/workflows/lint.yml
  build_tools/github_actions/lint_clang_format.sh
Labels: Process

#155 adding links to elaborative testing
  docs/spec_draft.md
Labels: Spec

#186 Bootstrap StableHLO governance
  docs/governance.md
Labels: Process

#191 Refactor op syntax in the spec draft
  docs/spec_draft.md
Labels: Spec

#192 Minor fixes to the formatting of the spec draft
  docs/spec_draft.md
Labels: Spec

#198 Fix up headers in the interpreter
  stablehlo/reference/Interpreter.h
  stablehlo/reference/Ops.h
  stablehlo/reference/Tensor.h
Labels: Interpreter

#200 Fix a few typos in the spec
  docs/spec_draft.md
Labels: Spec

#162 Add interpreters for cosine and tanh op
  docs/status.md
  stablehlo/reference/Element.cpp
  stablehlo/reference/Element.h
  stablehlo/reference/Interpreter.cpp
  stablehlo/reference/Ops.cpp
  stablehlo/reference/Ops.h
  stablehlo/tests/interpret_cosine.mlir
  stablehlo/tests/interpret_tanh.mlir
Labels: Interpreter

#167 Use multi-dimensional indices to access tensor elements
  docs/interpreter.md
  stablehlo/reference/CMakeLists.txt
  stablehlo/reference/Element.cpp
  stablehlo/reference/Index.cpp
  stablehlo/reference/Index.h
  stablehlo/reference/Ops.cpp
  stablehlo/reference/Tensor.cpp
  stablehlo/reference/Tensor.h
Labels: Interpreter

#170 Specification and Interpreter for reshape op
  docs/interpreter.md
  docs/spec_draft.md
  docs/status.md
  stablehlo/reference/Element.cpp
  stablehlo/reference/Interpreter.cpp
  stablehlo/reference/Ops.cpp
  stablehlo/reference/Ops.h
  stablehlo/reference/Tensor.cpp
  stablehlo/tests/interpret_reshape.mlir
Labels: Spec, Interpreter

#179 Add specification and interpreter for SubtractOp
  docs/spec_draft.md
  docs/status.md
  stablehlo/reference/Element.cpp
  stablehlo/reference/Element.h
  stablehlo/reference/Interpreter.cpp
  stablehlo/reference/Ops.cpp
  stablehlo/reference/Ops.h
  stablehlo/tests/interpret_subtract.mlir
Labels: Spec, Interpreter

#209 Fix table format and other typos
  docs/spec_draft.md
  docs/status.md
  stablehlo/reference/Interpreter.cpp
  stablehlo/tests/interpret_add.mlir
Labels: Process

#202 Fix build warning spew. Change $operands->$inputs.
  stablehlo/dialect/StablehloOps.cpp
  stablehlo/dialect/StablehloOps.td
Labels: Build

#203 Update to use prefixed accessors
  stablehlo/dialect/StablehloOps.cpp
  stablehlo/dialect/StablehloOps.td
  stablehlo/reference/Interpreter.cpp
Labels: Build

#222 Fix a spec bug for negate and abs op
  docs/spec_draft.md
Labels: Spec

#220 Integrate LLVM at llvm/llvm-project@0fb2676c248e
  build_tools/llvm_version.txt
Labels: Integrations

#101 Revisit use of mlir::Attribute storage of Element Class
  docs/interpreter.md
  stablehlo/reference/Element.cpp
  stablehlo/reference/Element.h
  stablehlo/reference/Tensor.cpp
  stablehlo/reference/Tensor.h
  stablehlo/tests/interpret_add.mlir
  stablehlo/tests/interpret_constant.mlir
  stablehlo/tests/interpret_cosine.mlir
  stablehlo/tests/interpret_sine.mlir
  stablehlo/tests/interpret_subtract.mlir
  stablehlo/tests/interpret_tanh.mlir
Labels: Interpreter

#214 Add interpreter for NegOp
  docs/spec_draft.md
  docs/status.md
  stablehlo/reference/Element.cpp
  stablehlo/reference/Element.h
  stablehlo/reference/Interpreter.cpp
  stablehlo/reference/Ops.cpp
  stablehlo/reference/Ops.h
  stablehlo/tests/interpret_negate.mlir
Labels: Interpreter

#145 Enhance result capability match for all ops.
  stablehlo/dialect/ChloOps.td
  stablehlo/dialect/StablehloOps.td
  stablehlo/tests/ops_chlo_roundtrip.mlir
Labels: Type inference

#215 Enforce compatible indices and shape while indexing into Tensor
  stablehlo/reference/Index.cpp
  stablehlo/reference/Index.h
  stablehlo/reference/Ops.cpp
  stablehlo/reference/Tensor.cpp
  stablehlo/tests/interpret_add.mlir
Labels: Interpreter

#172 Specification and Interpreter for transpose op
  docs/spec_draft.md
  docs/status.md
  stablehlo/reference/Element.cpp
  stablehlo/reference/Interpreter.cpp
  stablehlo/reference/Ops.cpp
  stablehlo/reference/Ops.h
  stablehlo/tests/interpret_transpose.mlir
Labels: Spec, Interpreter

#230 Move type utilities into a separate file
  stablehlo/reference/CMakeLists.txt
  stablehlo/reference/Element.cpp
  stablehlo/reference/Element.h
  stablehlo/reference/Tensor.cpp
  stablehlo/reference/Types.cpp
  stablehlo/reference/Types.h
Labels: Interpreter

#231 Assorted cleanup
  stablehlo/reference/Interpreter.cpp
  stablehlo/reference/Ops.cpp
  stablehlo/reference/Tensor.cpp
Labels: Interpreter
