Repository openxla/stablehlo, pull requests merged in 2023-07, with the labels that each got.

#1561 Avoid out of bound writes in the spec of ScatterOp
  docs/images/spec/scatter.svg
  docs/spec.md
  stablehlo/tests/interpret_scatter.mlir
Labels: Spec, Interpreter

#1669 Elaborate on the semantics of tokens
  docs/spec.md
Labels: Spec

#1665 Fix incorrect `window_end` calculation for ReduceWindowOp
  docs/spec.md
  stablehlo/reference/Ops.cpp
  stablehlo/tests/interpret_reduce_window.mlir
Labels: Spec, Interpreter

#1673 Integrate LLVM at llvm/llvm-project@8910cc2742f9
  WORKSPACE.bazel
  build_tools/llvm_version.txt
Labels: Integrations

#1670 Add lint to ensure that compatibility tests are implemented for new versions of StableHLO
  .github/workflows/lint.yml
  build_tools/github_actions/lint_version.sh
Labels: Compatibility

#1671 Fix spelling errors in .cpp and .h files
  stablehlo/api/PortableApi.cpp
  stablehlo/dialect/ChloBytecode.cpp
  stablehlo/dialect/ChloOps.cpp
  stablehlo/dialect/StablehloBytecode.cpp
  stablehlo/dialect/StablehloOps.cpp
  stablehlo/dialect/StablehloOps.h
  stablehlo/dialect/TypeInference.cpp
  stablehlo/dialect/VhloBytecode.cpp
  stablehlo/integrations/c/StablehloAttributes.h
  stablehlo/reference/Axes.cpp
  stablehlo/reference/Element.cpp
  stablehlo/tests/ops_stablehlo.mlir
  stablehlo/transforms/StablehloRefineShapes.cpp
Labels: Build

#1674 Fix cspell spelling issues in MD files
  docs/spec.md
  docs/vhlo.md
  stablehlo/tests/ops_stablehlo_roundtrip.mlir
Labels: Build

#1651 Offer StableHLO portable artifact deserialization as a pass pipeline
  BUILD.bazel
  stablehlo/dialect/Serialization.cpp
  stablehlo/tests/stablehlo_legalize_to_vhlo.mlir
  stablehlo/tools/StablehloOptMain.cpp
  stablehlo/transforms/CMakeLists.txt
  stablehlo/transforms/PassPipelines.cpp
  stablehlo/transforms/Passes.h
  stablehlo/transforms/VhloToVersion.cpp
Labels: Compatibility

#1676 Cleanup after a downstream integrate
  stablehlo/dialect/AssemblyFormat.cpp
  stablehlo/reference/Element.cpp
  stablehlo/reference/Ops.cpp
  stablehlo/tests/stablehlo_canonicalize_dynamism.mlir
Labels: Integrations, Migrate from MHLO

#1677 Fix a build warning in conversion to TOSA
  stablehlo/conversions/tosa/transforms/StablehloLegalizeToTosa.pdll
Labels: Integrations

#1680 Bump patch version after integrate 0.14.2 -> 0.14.3
  stablehlo/dialect/Version.h
Labels: Integrations

#1681 Integrate LLVM at llvm/llvm-project@986001c8274a
  WORKSPACE.bazel
  build_tools/llvm_version.txt
Labels: Integrations

#1682 Integrate LLVM at llvm/llvm-project@dbaa5838c13e
  WORKSPACE.bazel
  build_tools/llvm_version.txt
Labels: Integrations

#1498 [RFC] Forward Compatibility Testing
  rfcs/20230517-forward-compatibility-testing.md
Labels: RFC, Compatibility

#1684 Bump patch version after integrate 0.14.3 -> 0.14.4
  stablehlo/dialect/Version.h
Labels: Integrations

#1685 Integrate LLVM at llvm/llvm-project@b10899d86995
  WORKSPACE.bazel
  build_tools/llvm_version.txt
Labels: Integrations

#1686 Bump patch version after integrate 0.14.4 -> 0.14.5
  stablehlo/dialect/Version.h
Labels: Integrations

#1688 Add header for Forward Compat Testing RFC, fix header in fp8 RFC.
  rfcs/20221031-fp8.md
  rfcs/20230517-forward-compatibility-testing.md
Labels: RFC

#1690 Integrate LLVM at llvm/llvm-project@f0dfe682bca0
  WORKSPACE.bazel
  build_tools/llvm_version.txt
  stablehlo/reference/Element.cpp
Labels: Integrations

#1692 Fix --stablehlo-refine-shapes for i1 => ... conversions
  stablehlo/dialect/Base.cpp
  stablehlo/tests/stablehlo_refine_shapes.mlir
Labels: Type inference, Dynamism, Migrate from MHLO

#1693 Integrate LLVM at llvm/llvm-project@37937b8a040c
  WORKSPACE.bazel
  build_tools/llvm_version.txt
Labels: Integrations

#1647 Specification of quantized ops from `Control-flow`, `Distribution`, `Extensibility`, and `Miscellaneous` categories.
  docs/spec.md
Labels: Spec

#1695 Bump patch version after integrate 0.14.5 -> 0.14.6
  stablehlo/dialect/Version.h
Labels: Integrations

#1696 Integrate LLVM at llvm/llvm-project@fc3b7874b6c9
  BUILD.bazel
  WORKSPACE.bazel
  build_tools/llvm_version.txt
  stablehlo/integrations/python/mlir/dialects/ChloOps.td
  stablehlo/integrations/python/mlir/dialects/StablehloOps.td
  stablehlo/integrations/python/mlir/dialects/VhloOps.td
Labels: Integrations, Migrate from MHLO

#1697 Typo in convolution constraint
  docs/spec.md
Labels: Spec

#1698 Add `HLO_Commutative` trait to avoid inheriting folders
  stablehlo/dialect/Base.h
  stablehlo/dialect/Base.td
  stablehlo/dialect/StablehloOps.cpp
  stablehlo/dialect/StablehloOps.td
Labels: Integrations, Migrate from MHLO

#1699 Bump patch version after integrate 0.14.6 -> 0.14.7
  stablehlo/dialect/Version.h
Labels: Process

#1701 Alphanumerically order ops
  stablehlo/reference/Ops.cpp
Labels: Interpreter

#1704 Integrate LLVM at llvm/llvm-project@cb924ddca514
  WORKSPACE.bazel
  build_tools/llvm_version.txt
  stablehlo/tests/stablehlo_legalize_to_vhlo.0_10_0.mlir.bc
  stablehlo/tests/stablehlo_legalize_to_vhlo.0_11_0.mlir.bc
  stablehlo/tests/stablehlo_legalize_to_vhlo.0_12_0.mlir.bc
  stablehlo/tests/stablehlo_legalize_to_vhlo.0_13_0.mlir.bc
  stablehlo/tests/stablehlo_legalize_to_vhlo.0_14_0.mlir.bc
  stablehlo/tests/stablehlo_legalize_to_vhlo.0_9_0.mlir.bc
Labels: Integrations
