Repository openxla/stablehlo, pull requests merged in 2023-09, with the labels that each got.

#1767 Integrate LLVM at llvm/llvm-project@f0f395e00e2e
  WORKSPACE.bazel
  build_tools/llvm_version.txt
  stablehlo/dialect/ChloOps.cpp
  stablehlo/dialect/StablehloOps.cpp
  stablehlo/dialect/VhloOps.cpp
  stablehlo/dialect/VhloOps.h
Labels: Integrations

#1766 build: miscellaneous CMake fixes
  stablehlo/api/CMakeLists.txt
  stablehlo/dialect/CMakeLists.txt
  stablehlo/integrations/python/tests/CMakeLists.txt
Labels: Build

#1769 Bump patch version after integrate 0.14.17 -> 0.14.18
  stablehlo/dialect/Version.h
Labels: Integrations

#1771 Bump patch version after integrate 0.14.18 -> 0.14.19
  stablehlo/dialect/Version.h
Labels: Integrations

#1768 Fix TSAN violations for Distribution ops
  stablehlo/reference/Ops.cpp
  stablehlo/reference/Process.cpp
  stablehlo/reference/Process.h
  stablehlo/reference/ProcessGrid.cpp
  stablehlo/reference/ProcessGrid.h
  stablehlo/reference/Tensor.h
  stablehlo/tests/interpret_all_gather.mlir
  stablehlo/tests/interpret_all_reduce.mlir
  stablehlo/tests/interpret_all_to_all.mlir
  stablehlo/tests/interpret_collective_permute.mlir
  stablehlo/tests/interpret_outfeed.mlir
  stablehlo/tests/interpret_reduce_scatter.mlir
Labels: Interpreter

#1774 Allow the specification of a scalar operand for broadcast_in_dim operation
  docs/spec.md
Labels: Spec

#1777 Fixing the access of scalar elements in `broadcast_in_dim`, `clamp`, and `select` operations
  docs/spec.md
Labels: Spec

#1776 Integrate LLVM at llvm/llvm-project@79e96b2457fe
  WORKSPACE.bazel
  build_tools/llvm_version.txt
Labels: Integrations

#1778 Fix clang tidy, change constness of rendezvous results
  stablehlo/reference/Process.cpp
  stablehlo/reference/Process.h
  stablehlo/reference/ProcessGrid.cpp
  stablehlo/reference/ProcessGrid.h
Labels: Integrations

#1779 Bump patch version after integrate 0.14.19 -> 0.14.20
  stablehlo/dialect/Version.h
Labels: Integrations

#1781 Integrate LLVM at llvm/llvm-project@f7bf99fb529f
  WORKSPACE.bazel
  build_tools/llvm_version.txt
Labels: Integrations

#1722 Add interpreter for InfeedOp
  docs/spec.md
  docs/status.md
  stablehlo/dialect/StablehloOps.td
  stablehlo/dialect/TypeInference.cpp
  stablehlo/reference/InterpreterOps.cpp
  stablehlo/reference/InterpreterOps.h
  stablehlo/reference/InterpreterOps.td
  stablehlo/reference/Ops.cpp
  stablehlo/reference/Ops.h
  stablehlo/reference/Process.cpp
  stablehlo/reference/Process.h
  stablehlo/reference/ProcessGrid.cpp
  stablehlo/reference/ProcessGrid.h
  stablehlo/tests/interpret_all_gather.mlir
  stablehlo/tests/interpret_all_reduce.mlir
  stablehlo/tests/interpret_all_to_all.mlir
  stablehlo/tests/interpret_collective_permute.mlir
  stablehlo/tests/interpret_infeed.mlir
  stablehlo/tests/interpret_outfeed.mlir
  stablehlo/tests/interpret_partition_id.mlir
  stablehlo/tests/interpret_reduce_scatter.mlir
  stablehlo/tests/interpret_replica_id.mlir
  stablehlo/tests/ops_interpreter.mlir
  stablehlo/tests/ops_stablehlo.mlir
  stablehlo/tools/StablehloTranslateMain.cpp
Labels: Interpreter, Migrate to MHLO

#1783 Minor edits to the sparsity RFC
  rfcs/20230210-sparsity.md
Labels: Process

#1782 Fixing verifier for reshape, transpose, and broadcast_in_dim ops
  stablehlo/dialect/StablehloOps.td
  stablehlo/tests/ops_stablehlo.mlir
Labels: Spec

#1732 Add interpreter for SendOp and RecvOp
  docs/spec.md
  docs/status.md
  stablehlo/dialect/StablehloOps.cpp
  stablehlo/dialect/StablehloOps.td
  stablehlo/dialect/TypeInference.cpp
  stablehlo/dialect/TypeInference.h
  stablehlo/reference/Ops.cpp
  stablehlo/reference/Ops.h
  stablehlo/reference/Process.cpp
  stablehlo/reference/Process.h
  stablehlo/reference/ProcessGrid.cpp
  stablehlo/reference/ProcessGrid.h
  stablehlo/tests/infer_stablehlo.mlir
  stablehlo/tests/interpret_send_recv.mlir
  stablehlo/tests/ops_stablehlo.mlir
  stablehlo/tests/stablehlo_legalize_to_vhlo.0_10_0.mlir
  stablehlo/tests/stablehlo_legalize_to_vhlo.0_10_0.mlir.bc
  stablehlo/tests/stablehlo_legalize_to_vhlo.0_11_0.mlir
  stablehlo/tests/stablehlo_legalize_to_vhlo.0_11_0.mlir.bc
  stablehlo/tests/stablehlo_legalize_to_vhlo.0_12_0.mlir
  stablehlo/tests/stablehlo_legalize_to_vhlo.0_12_0.mlir.bc
  stablehlo/tests/stablehlo_legalize_to_vhlo.0_13_0.mlir
  stablehlo/tests/stablehlo_legalize_to_vhlo.0_13_0.mlir.bc
  stablehlo/tests/stablehlo_legalize_to_vhlo.0_14_0.mlir
  stablehlo/tests/stablehlo_legalize_to_vhlo.0_14_0.mlir.bc
  stablehlo/tests/stablehlo_legalize_to_vhlo.0_9_0.mlir
  stablehlo/tests/stablehlo_legalize_to_vhlo.0_9_0.mlir.bc
  stablehlo/tests/stablehlo_legalize_to_vhlo.mlir
Labels: Interpreter, Migrate to MHLO

#1785 Bump patch version after integrate 0.14.20 -> 0.14.21
  stablehlo/dialect/Version.h
Labels: Integrations

#1786 Integrate LLVM at llvm/llvm-project@512739ebbb25
  WORKSPACE.bazel
  build_tools/llvm_version.txt
Labels: Integrations
