Repository openxla/stablehlo, pull requests merged in 2023-03, with the labels that each got.

#1242 Update build to remove traces of conformance
  stablehlo/testdata/CMakeLists.txt
Labels: Compatibility

#1243 Fix prettyprint bug with default optional attr in CholeskyOp
  stablehlo/dialect/StablehloOps.td
  stablehlo/tests/print_stablehlo.mlir
  stablehlo/tests/stablehlo_legalize_to_vhlo.mlir
Labels: Prettyprinting

#1244 Add compatibility.md
  docs/compatibility.md
  rfcs/20220912-compatibility.md
Labels: Compatibility

#1252 Only lint whitespace for changed files
  build_tools/github_actions/lint_whitespace_checks.sh
Labels: Build

#1253 [CHLO] Add erf_inv
  stablehlo/dialect/ChloOps.cpp
  stablehlo/dialect/ChloOps.td
  stablehlo/tests/ops_chlo.mlir
  stablehlo/tests/ops_chlo_roundtrip.mlir
Labels: CHLO

#1250 Add VHLO documentation and usage instructions
  docs/bytecode.md
  docs/compatibility.md
  docs/images/vhlo/backward_compatibility.png
  docs/images/vhlo/forward_compatibility.png
  docs/vhlo.md
Labels: Compatibility

#1259 Treat VHLO as an implementation detail in compatibility.md
  docs/compatibility.md
Labels: Compatibility

#1260 Version and bytecode stablehlo_legalize_to_vhlo.mlir for 0.9.0
  stablehlo/tests/stablehlo_legalize_to_vhlo.0_9_0.mlir
  stablehlo/tests/stablehlo_legalize_to_vhlo.0_9_0.mlir.bc
Labels: Compatibility

#1263 Update compatibility.md with a link to the VHLO cookbook
  docs/compatibility.md
Labels: Compatibility

#1265 Two minor bugs fixes in lint whitespace check
  build_tools/github_actions/lint_whitespace_checks.sh
Labels: Build

#1267 Use std::optional instead of llvm::Optional
  stablehlo/dialect/Base.cpp
  stablehlo/dialect/Base.h
  stablehlo/dialect/TypeInference.cpp
  stablehlo/dialect/TypeInference.h
Labels: Integrations, Migrate from MHLO

#1266 Standardize summaries
  stablehlo/dialect/StablehloOps.td
Labels: Process, Migrate from MHLO

#1273 Fix typo in ReverseOp's spec example
  docs/spec.md
Labels: Spec

#1230 Sync check ops with IREE check ops
  stablehlo/tests/CheckOps.cpp
  stablehlo/tests/CheckOps.h
  stablehlo/tests/CheckOps.td
  stablehlo/tests/interpret_abs.mlir
  stablehlo/tests/interpret_add.mlir
  stablehlo/tests/interpret_and.mlir
  stablehlo/tests/interpret_broadcast_in_dim.mlir
  stablehlo/tests/interpret_case.mlir
  stablehlo/tests/interpret_ceil.mlir
  stablehlo/tests/interpret_clamp.mlir
  stablehlo/tests/interpret_concatenate.mlir
  stablehlo/tests/interpret_constant.mlir
  stablehlo/tests/interpret_cosine.mlir
  stablehlo/tests/interpret_divide.mlir
  stablehlo/tests/interpret_dynamic_slice.mlir
  stablehlo/tests/interpret_dynamic_update_slice.mlir
  stablehlo/tests/interpret_exponential.mlir
  stablehlo/tests/interpret_floor.mlir
  stablehlo/tests/interpret_if.mlir
  stablehlo/tests/interpret_imag.mlir
  stablehlo/tests/interpret_iota.mlir
  stablehlo/tests/interpret_log.mlir
  stablehlo/tests/interpret_maximum.mlir
  stablehlo/tests/interpret_minimum.mlir
  stablehlo/tests/interpret_multiply.mlir
  stablehlo/tests/interpret_negate.mlir
  stablehlo/tests/interpret_not.mlir
  stablehlo/tests/interpret_or.mlir
  stablehlo/tests/interpret_pad.mlir
  stablehlo/tests/interpret_real.mlir
  stablehlo/tests/interpret_rem.mlir
  stablehlo/tests/interpret_reshape.mlir
  stablehlo/tests/interpret_reverse.mlir
  stablehlo/tests/interpret_rsqrt.mlir
  stablehlo/tests/interpret_select.mlir
  stablehlo/tests/interpret_sine.mlir
  stablehlo/tests/interpret_slice.mlir
  stablehlo/tests/interpret_sqrt.mlir
  stablehlo/tests/interpret_subtract.mlir
  stablehlo/tests/interpret_tanh.mlir
  stablehlo/tests/interpret_transpose.mlir
  stablehlo/tests/interpret_while.mlir
  stablehlo/tests/interpret_xor.mlir
  stablehlo/tools/StablehloInterpreterMain.cpp
Labels: Interpreter

#1207 Add interpreter for PowOp
  docs/spec.md
  docs/status.md
  stablehlo/dialect/StablehloOps.td
  stablehlo/reference/Element.cpp
  stablehlo/reference/Element.h
  stablehlo/reference/Ops.cpp
  stablehlo/reference/Ops.h
  stablehlo/tests/interpret_power.mlir
Labels: Interpreter

#1274 Improve newcomer experience
  README.md
  build_tools/build_mlir.sh
  stablehlo/testdata/CMakeLists.txt
  stablehlo/testdata/lit.cfg.py
  stablehlo/tests/CMakeLists.txt
  stablehlo/tests/lit.cfg.py
Labels: Build

#1285 Integrate LLVM at llvm/llvm-project@31c39439a894
  WORKSPACE.bazel
  build_tools/llvm_version.txt
Labels: Build

#1272 Add StableHLO portable artifact serialization APIs
  BUILD.bazel
  docs/vhlo.md
  stablehlo/dialect/CMakeLists.txt
  stablehlo/dialect/Serialization.cpp
  stablehlo/dialect/Serialization.h
  stablehlo/tests/stablehlo_legalize_to_vhlo.0_9_0.mlir
  stablehlo/tests/stablehlo_legalize_to_vhlo.mlir
  stablehlo/tests/vhlo_to_version_invalid_target_empty.mlir
  stablehlo/tools/CMakeLists.txt
  stablehlo/tools/StablehloInterpreterMain.cpp
  stablehlo/transforms/VhloToVersion.cpp
Labels: Compatibility

#1286 Rename stablehlo-interpreter --> stablehlo-translate, fix tests/
  BUILD.bazel
  docs/reference.md
  docs/vhlo.md
  stablehlo/testdata/CMakeLists.txt
  stablehlo/testdata/lit.cfg.py
  stablehlo/tests/CMakeLists.txt
  stablehlo/tests/interpret_abs.mlir
  stablehlo/tests/interpret_add.mlir
  stablehlo/tests/interpret_and.mlir
  stablehlo/tests/interpret_broadcast_in_dim.mlir
  stablehlo/tests/interpret_case.mlir
  stablehlo/tests/interpret_ceil.mlir
  stablehlo/tests/interpret_clamp.mlir
  stablehlo/tests/interpret_concatenate.mlir
  stablehlo/tests/interpret_constant.mlir
  stablehlo/tests/interpret_cosine.mlir
  stablehlo/tests/interpret_divide.mlir
  stablehlo/tests/interpret_dynamic_slice.mlir
  stablehlo/tests/interpret_dynamic_update_slice.mlir
  stablehlo/tests/interpret_exponential.mlir
  stablehlo/tests/interpret_floor.mlir
  stablehlo/tests/interpret_if.mlir
  stablehlo/tests/interpret_imag.mlir
  stablehlo/tests/interpret_iota.mlir
  stablehlo/tests/interpret_log.mlir
  stablehlo/tests/interpret_maximum.mlir
  stablehlo/tests/interpret_minimum.mlir
  stablehlo/tests/interpret_multiply.mlir
  stablehlo/tests/interpret_negate.mlir
  stablehlo/tests/interpret_not.mlir
  stablehlo/tests/interpret_or.mlir
  stablehlo/tests/interpret_pad.mlir
  stablehlo/tests/interpret_power.mlir
  stablehlo/tests/interpret_real.mlir
  stablehlo/tests/interpret_rem.mlir
  stablehlo/tests/interpret_reshape.mlir
  stablehlo/tests/interpret_reverse.mlir
  stablehlo/tests/interpret_rsqrt.mlir
  stablehlo/tests/interpret_select.mlir
  stablehlo/tests/interpret_sine.mlir
  stablehlo/tests/interpret_slice.mlir
  stablehlo/tests/interpret_sqrt.mlir
  stablehlo/tests/interpret_subtract.mlir
  stablehlo/tests/interpret_tanh.mlir
  stablehlo/tests/interpret_transpose.mlir
  stablehlo/tests/interpret_while.mlir
  stablehlo/tests/interpret_xor.mlir
  stablehlo/tests/lit.cfg.py
  stablehlo/tests/stablehlo_legalize_to_vhlo.0_9_0.mlir
  stablehlo/tests/stablehlo_legalize_to_vhlo.mlir
  stablehlo/tools/CMakeLists.txt
  stablehlo/tools/StablehloTranslateMain.cpp
Labels: Interpreter, Compatibility

#1288 Remove unnecessary include
  stablehlo/dialect/Serialization.cpp
Labels: Build

#1278 Fix for float diff error on Mac platform
  docs/reference.md
  stablehlo/reference/Element.cpp
  stablehlo/reference/Element.h
Labels: Interpreter

#1293 Fix compilation error on macOS
  stablehlo/reference/Element.cpp
Labels: Build

#1294 Update signature of `inferPadOp` function for re-usability
  stablehlo/dialect/StablehloOps.cpp
  stablehlo/dialect/TypeInference.cpp
  stablehlo/dialect/TypeInference.h
  stablehlo/transforms/StablehloRefineShapes.cpp
Labels: Type inference

#1296 Update signature of `inferConvolutionOp` function for re-usability
  stablehlo/dialect/StablehloOps.cpp
  stablehlo/dialect/TypeInference.cpp
  stablehlo/dialect/TypeInference.h
  stablehlo/transforms/StablehloRefineShapes.cpp
Labels: Type inference

#1297 Update how pad is used in spec
  docs/spec.md
Labels: Spec

#1295 Update signature of `inferReverseOp` function for re-usability
  stablehlo/dialect/StablehloOps.cpp
  stablehlo/dialect/TypeInference.cpp
  stablehlo/dialect/TypeInference.h
Labels: Type inference

#1277 Significantly compress syntax for bounded dynamism
  stablehlo/dialect/AssemblyFormat.cpp
  stablehlo/dialect/AssemblyFormat.h
  stablehlo/dialect/StablehloOps.cpp
  stablehlo/dialect/TypeInference.cpp
  stablehlo/dialect/TypeInference.h
  stablehlo/tests/infer_stablehlo.mlir
  stablehlo/tests/ops_stablehlo.mlir
  stablehlo/tests/print_stablehlo.mlir
Labels: Prettyprinting

#1239 Add interpreter for LogisticOp
  docs/spec.md
  docs/status.md
  stablehlo/dialect/StablehloOps.td
  stablehlo/reference/Element.cpp
  stablehlo/reference/Element.h
  stablehlo/reference/Ops.cpp
  stablehlo/reference/Ops.h
  stablehlo/tests/interpret_logistic.mlir
Labels: Interpreter

#1300 Update reference checklist example
  docs/reference_checklist.md
Labels: Interpreter

#1292 Refactor CustomCallOp evaluator
  stablehlo/tools/StablehloTranslateMain.cpp
Labels: Interpreter

#1276 Implement prettyprinting for dot_general
  stablehlo/dialect/AssemblyFormat.h
  stablehlo/dialect/StablehloOps.cpp
  stablehlo/dialect/StablehloOps.td
  stablehlo/tests/ops_sparse.mlir
  stablehlo/tests/print_stablehlo.mlir
  stablehlo/tests/stablehlo_refine_shapes.mlir
Labels: Prettyprinting

#1304 Retire the link to GitHub Discussions
  README.md
Labels: Process

#1307 Fix formatting in the rfcs/ directory
  rfcs/20220912-compatibility.md
Labels: Process

#1299 Link recently added frontend contract tickets in the spec
  docs/spec.md
Labels: Spec

#1310 Streamline the on: part of all GitHub workflows
  .github/workflows/buildAndTestCMake.yml
  .github/workflows/buildBazel.yml
  .github/workflows/lint.yml
  .github/workflows/markdown_lint.yml
Labels: Build

#1312 Integrate LLVM at llvm/llvm-project@fbcca1bc03d3
  WORKSPACE.bazel
  build_tools/llvm_version.txt
Labels: Build

#1320 Synchronize our BUILD.bazel with downstream build
  BUILD.bazel
Labels: Build

#1321 Add support for running FileCheck tests in the Bazel build
  .github/workflows/buildAndTestBazel.yml
  .github/workflows/buildAndTestCMake.yml
  BUILD.bazel
  CMakeLists.txt
  build_tools/github_actions/ci_build_bazel.sh
  build_tools/github_actions/ci_build_cmake.sh
  build_tools/github_actions/ci_build_cmake_code_coverage.sh
  build_tools/github_actions/ci_build_cmake_llvm.sh
  build_tools/github_actions/ci_build_cmake_python_api.sh
  build_tools/github_actions/llvm_gcov.sh
  docs/reference_checklist.md
  stablehlo/testdata/BUILD.bazel
  stablehlo/testdata/CMakeLists.txt
  stablehlo/testdata/lit.cfg.py
  stablehlo/testdata/lit.site.cfg.py.in
  stablehlo/tests/BUILD.bazel
  stablehlo/tests/CMakeLists.txt
  stablehlo/tests/lit.cfg.py
  stablehlo/tests/lit.site.cfg.py.in
Labels: Build

#1324 Integrate LLVM at llvm/llvm-project@83586a61b162
  WORKSPACE.bazel
  build_tools/llvm_version.txt
Labels: Integrations

#1323 Update interpreter checklist
  docs/reference_checklist.md
Labels: Interpreter

#1326 Fix issues found during integration testing.
  stablehlo/dialect/TypeInference.h
  stablehlo/transforms/StablehloRefineShapes.cpp
Labels: Build

#1331 Load VHLO before deserialization
  stablehlo/dialect/Serialization.cpp
Labels: Compatibility

#1332 Integrate LLVM at llvm/llvm-project@5cb8381aea56
  WORKSPACE.bazel
  build_tools/llvm_version.txt
Labels: Integrations

#1333 fix a typo in reduceOp spec
  docs/spec.md
Labels: Spec

#1335 Fix tests by updating STABLEHLO_TOOLS_DIR
  CMakeLists.txt
Labels: Integrations

#1337 Integrate LLVM at llvm/llvm-project@a7cf2892e964
  WORKSPACE.bazel
  build_tools/llvm_version.txt
Labels: Integrations

#1340 Spec update for ConvolutionOp: Clarify permute
  docs/spec.md
Labels: Spec

#1343 Fix CompareOp interpreter interface inconsistency
  stablehlo/reference/Ops.h
Labels: Interpreter

#1348 Integrate LLVM at llvm/llvm-project@411b1d8f0795
  WORKSPACE.bazel
  build_tools/llvm_version.txt
Labels: Integrations

#1308 [RFC] Add a new type to StableHLO: E4M3B11FNUZ
  rfcs/20230309-e4m3b11.md
Labels: RFC

#1306 [RFC] Increase backward compatibility guarantees to 6 months
  docs/compatibility.md
  rfcs/20220912-compatibility.md
Labels: RFC

#1356 Integrate LLVM at llvm/llvm-project@42058eea7912
  WORKSPACE.bazel
  build_tools/llvm_version.txt
Labels: Integrations

#1353 Add Python API version number
  stablehlo/dialect/CMakeLists.txt
  stablehlo/dialect/Version.h
  stablehlo/integrations/python/CMakeLists.txt
  stablehlo/integrations/python/StablehloModule.cpp
  stablehlo/integrations/python/tests/stablehlo.py
Labels: Integrations

#1359 Integrate LLVM at llvm/llvm-project@c6a132a8023d
  WORKSPACE.bazel
  build_tools/llvm_version.txt
Labels: Integrations

#1360 Enabling a few passing interpreter tests
  stablehlo/testdata/acos_shape_complex64_20_20.mlir
  stablehlo/testdata/convert_element_type_dtypes_to_dtypes_shape_complex64_100_100__olddtype_complex64_newdtype_bool.mlir
  stablehlo/testdata/cummax_dtype_by_fun_shape_complex64_8_9__associative_scan_reductions_axis_0_reverse_False.mlir
  stablehlo/testdata/cummax_dtype_by_fun_shape_complex64_8_9__axis_0_reverse_False.mlir
  stablehlo/testdata/cummin_dtype_by_fun_shape_complex64_8_9__associative_scan_reductions_axis_0_reverse_False.mlir
  stablehlo/testdata/cummin_dtype_by_fun_shape_complex64_8_9__axis_0_reverse_False.mlir
  stablehlo/testdata/dynamic_slice_dtypes_a_complex64_3__start_indices__1___limit_indices__2___enablexla_True.mlir
  stablehlo/testdata/dynamic_update_slice_dtypes_operand_complex64_3__update_complex64_1__start_indices__1___enable_xla_True.mlir
  stablehlo/testdata/eq_dtypes_lhs_complex64___rhs_complex64.mlir
  stablehlo/testdata/ge_dtypes_lhs_complex64___rhs_complex64.mlir
  stablehlo/testdata/gt_dtypes_lhs_complex64___rhs_complex64.mlir
  stablehlo/testdata/le_dtypes_lhs_complex64___rhs_complex64.mlir
  stablehlo/testdata/lt_dtypes_lhs_complex64___rhs_complex64.mlir
  stablehlo/testdata/max_broadcasting_lhs_complex128_1_20__rhs_complex128_20_20.mlir
  stablehlo/testdata/max_broadcasting_lhs_complex128_20_20__rhs_complex128_1_20.mlir
  stablehlo/testdata/max_broadcasting_lhs_complex64_1_20__rhs_complex64_20_20.mlir
  stablehlo/testdata/max_broadcasting_lhs_complex64_20_20__rhs_complex64_1_20.mlir
  stablehlo/testdata/max_dtypes_lhs_complex64_20_20__rhs_complex64_20_20.mlir
  stablehlo/testdata/max_inf_nan_complex64.mlir
  stablehlo/testdata/min_broadcasting_lhs_complex128_1_20__rhs_complex128_20_20.mlir
  stablehlo/testdata/min_broadcasting_lhs_complex128_20_20__rhs_complex128_1_20.mlir
  stablehlo/testdata/min_broadcasting_lhs_complex64_1_20__rhs_complex64_20_20.mlir
  stablehlo/testdata/min_broadcasting_lhs_complex64_20_20__rhs_complex64_1_20.mlir
  stablehlo/testdata/min_dtypes_lhs_complex64_20_20__rhs_complex64_20_20.mlir
  stablehlo/testdata/min_inf_nan_complex64.mlir
  stablehlo/testdata/ne_dtypes_lhs_complex64___rhs_complex64.mlir
  stablehlo/testdata/select_n_dtypes_shapepred_int32_2_3__shapeargs_complex64_2_3.mlir
Labels: Interpreter

#1362 Update function type for return with multiple operands, some repeating
  stablehlo/tests/stablehlo_refine_shapes.mlir
  stablehlo/transforms/StablehloRefineShapes.cpp
Labels: Dynamism
