Repository openxla/stablehlo, pull requests merged in 2023-12, with the labels that each got.

#1864 Do not throw error when executing empty StableHLO modules
  stablehlo/reference/Api.cpp
  stablehlo/tests/interpret_probe.mlir
Labels: Interpreter

#1841 Introduce a compiler pass to instrument modules
  BUILD.bazel
  stablehlo/tests/stablehlo_probe_instrumentation.mlir
  stablehlo/transforms/CMakeLists.txt
  stablehlo/transforms/Passes.h
  stablehlo/transforms/Passes.td
  stablehlo/transforms/StablehloInstrumentWithProbe.cpp
Labels: Interpreter

#1870 Bump patch version after integrate 0.16.0 -> 0.16.1
  stablehlo/dialect/Version.h
Labels: Integrations

#1796 Specification of quantized `reduce` and other related ops
  docs/spec.md
Labels: Spec

#1873 Fix broken links
  docs/reference_checklist.md
  docs/spec_checklist.md
  docs/status.md
  docs/type_inference.md
Labels: Process

#1871 Integrate LLVM at llvm/llvm-project@c4cebe5b4489
  WORKSPACE.bazel
  build_tools/llvm_version.txt
  stablehlo/dialect/StablehloOps.h
Labels: Integrations

#1884 Bump patch version after integrate 0.16.1 -> 0.16.2
  stablehlo/dialect/Version.h
Labels: Integrations

#1886 Remove redundant cppNamespace fields
  stablehlo/dialect/StablehloAttrs.td
  stablehlo/dialect/VhloAttrs.td
Labels: Cleanup/Refactoring

#1889 Bump patch version after integrate 0.16.2 -> 0.16.3
  stablehlo/dialect/Version.h
Labels: Integrations

#1890 Integrate LLVM at llvm/llvm-project@b2cdf3cc4c08
  WORKSPACE.bazel
  build_tools/llvm_version.txt
Labels: Integrations

#1892 Updating API version
  .bazelversion
  stablehlo/api/PortableApi.h
Labels: Integrations
