Repository openxla/stablehlo, pull requests merged in 2023-06, with the labels that each got.

#1564 Bump patch version after integrate 0.13.0 -> 0.13.1
  stablehlo/dialect/Version.h
Labels: Integrations

#1565 Integrate LLVM at llvm/llvm-project@b9e328fd9113
  WORKSPACE.bazel
  build_tools/llvm_version.txt
Labels: Integrations

#1568 Bump patch version after integrate 0.13.1 -> 0.13.2
  stablehlo/dialect/Version.h
Labels: Integrations

#1554 Align the notation of spec and interpreter for Data Movement operations
  docs/spec.md
  stablehlo/reference/Ops.cpp
  stablehlo/reference/Sizes.cpp
  stablehlo/reference/Sizes.h
Labels: Interpreter

#1579 Integrate LLVM at llvm/llvm-project@9d531c2dcfa7
  WORKSPACE.bazel
  build_tools/llvm_version.txt
Labels: Integrations

#1556 Tighten the formal notation that we're using in the spec
  docs/spec.md
Labels: Spec

#1591 Compress a few more formulas using the ellipsis syntax
  docs/spec.md
Labels: Spec

#1592 Bump patch version after integrate 0.13.2 -> 0.13.3
  stablehlo/dialect/Version.h
Labels: Integrations

#1597 Enable passing testdata tests and tag failing floating-point precision tests
  stablehlo/testdata/asinh_shape_float16_20_20.mlir
  stablehlo/testdata/atanh_shape_float16_20_20.mlir
  stablehlo/testdata/cbrt_shape_float16_20_20.mlir
  stablehlo/testdata/cumlogsumexp_dtype_by_fun_shape_float16_8_9__axis_0_reverse_False.mlir
  stablehlo/testdata/expm1_shape_float16_20_20.mlir
  stablehlo/testdata/expm1_shape_float32_20_20.mlir
  stablehlo/testdata/gather_from_take_indices_name__5_oob__axis_0_enable_xla_True_mode_fill.mlir
  stablehlo/testdata/gather_from_take_indices_name__5_oob__axis_1_enable_xla_True_mode_fill.mlir
  stablehlo/testdata/gather_from_take_indices_name__5_oob__axis_2_enable_xla_True_mode_fill.mlir
  stablehlo/testdata/gather_from_take_indices_name__6_neg__axis_0_enable_xla_True_mode_clip.mlir
  stablehlo/testdata/gather_from_take_indices_name__6_neg__axis_1_enable_xla_True_mode_clip.mlir
  stablehlo/testdata/gather_from_take_indices_name__7_neg__axis_0_enable_xla_True_mode_clip.mlir
  stablehlo/testdata/gather_from_take_indices_name__7_neg__axis_1_enable_xla_True_mode_clip.mlir
  stablehlo/testdata/gather_from_take_indices_name__8_neg_oob__axis_0_enable_xla_True_mode_clip.mlir
  stablehlo/testdata/gather_from_take_indices_name__8_neg_oob__axis_0_enable_xla_True_mode_fill.mlir
  stablehlo/testdata/gather_from_take_indices_name__8_neg_oob__axis_1_enable_xla_True_mode_clip.mlir
  stablehlo/testdata/gather_from_take_indices_name__8_neg_oob__axis_1_enable_xla_True_mode_fill.mlir
  stablehlo/testdata/gather_from_take_indices_name__8_neg_oob__axis_2_enable_xla_True_mode_fill.mlir
  stablehlo/testdata/log1p_shape_float16_20_20.mlir
  stablehlo/testdata/reduce_window_mul_dtypes_shape_complex64_4_6__initvalue_2_windowdimensions__2_2__windowstrides__1_1_-4418219444220371989.mlir
Labels: Interpreter

#1598 Fix table spacing in the spec
  docs/spec.md
Labels: Spec

#1492 Update spec and interpreter for ReduceWindowOp to properly calculate window_end
  docs/spec.md
  stablehlo/reference/Ops.cpp
  stablehlo/testdata/reduce_window_add_window_dilation_shape_float32_4_6__initvalue_0_windowdimensions__2_2__windowstride1490052185320441557.mlir
  stablehlo/testdata/select_and_gather_add_dilations_shape_float32_4_6__selectprim_le_windowdimensions__2__2__windowstrid-1234442230378059557.mlir
  stablehlo/testdata/select_and_gather_add_dilations_shape_float32_4_6__selectprim_le_windowdimensions__2__2__windowstrid4494141771612406334.mlir
Labels: Spec, Interpreter

#1573 Fail interpretation on Not in HLO and Miscellaneous ops
  docs/spec.md
  docs/status.md
  stablehlo/reference/Ops.cpp
  stablehlo/reference/Ops.h
  stablehlo/tests/interpret_batch_norm_grad.mlir
  stablehlo/tests/interpret_batch_norm_inference.mlir
  stablehlo/tests/interpret_batch_norm_training.mlir
  stablehlo/tests/interpret_cholesky.mlir
Labels: Interpreter

#1600 [RFC] Reduce StableHLO v1.0 Compatibility Guarantees
  rfcs/20230525-compatibility.md
Labels: RFC

#1601 Add the 6 months compatibility RFC to rfcs/ for future reference
  rfcs/20230309-compatibility.md
Labels: Process

#1605 Correction to Min Normal bitstring for Float8E5M2FNUZ
  rfcs/20230321-fp8_fnuz.md
Labels: Spec

#1606 Update compatibility.md
  docs/compatibility.md
  docs/roadmap.md
  rfcs/20220912-compatibility.md
Labels: Compatibility

#1604 Integrate LLVM at llvm/llvm-project@309023263dba
  WORKSPACE.bazel
  build_tools/llvm_version.txt
Labels: Integrations

#1518 Add interpreter for SelectAndScatterOp
  BUILD.bazel
  docs/spec.md
  docs/status.md
  stablehlo/dialect/StablehloOps.td
  stablehlo/dialect/TypeInference.cpp
  stablehlo/reference/CMakeLists.txt
  stablehlo/reference/Index.cpp
  stablehlo/reference/Index.h
  stablehlo/reference/Ops.cpp
  stablehlo/reference/Ops.h
  stablehlo/reference/Sizes.cpp
  stablehlo/reference/Sizes.h
  stablehlo/reference/Tensor.cpp
  stablehlo/reference/Tensor.h
  stablehlo/testdata/select_and_scatter_add_dtypes_shape_bfloat16_2_4_6__selectprim_ge_windowdimensions__2__2__2__windows5498388055904314537.mlir
  stablehlo/testdata/select_and_scatter_add_dtypes_shape_bool_2_4_6__selectprim_ge_windowdimensions__2__2__2__windowstrid3953935332736217868.mlir
  stablehlo/testdata/select_and_scatter_add_dtypes_shape_float16_2_4_6__selectprim_ge_windowdimensions__2__2__2__windowst645862737998720881.mlir
  stablehlo/testdata/select_and_scatter_add_dtypes_shape_float32_2_4_6__selectprim_ge_windowdimensions__2__2__2__windowst6350781848831556769.mlir
  stablehlo/testdata/select_and_scatter_add_dtypes_shape_int16_2_4_6__selectprim_ge_windowdimensions__2__2__2__windowstri1180273328702244000.mlir
  stablehlo/testdata/select_and_scatter_add_dtypes_shape_int32_2_4_6__selectprim_ge_windowdimensions__2__2__2__windowstri-799453658564734982.mlir
  stablehlo/testdata/select_and_scatter_add_dtypes_shape_int8_2_4_6__selectprim_ge_windowdimensions__2__2__2__windowstrid-1158927479391781377.mlir
  stablehlo/testdata/select_and_scatter_add_dtypes_shape_uint16_2_4_6__selectprim_ge_windowdimensions__2__2__2__windowstr2639417885255268371.mlir
  stablehlo/testdata/select_and_scatter_add_dtypes_shape_uint32_2_4_6__selectprim_ge_windowdimensions__2__2__2__windowstr4996434443108277595.mlir
  stablehlo/testdata/select_and_scatter_add_dtypes_shape_uint8_2_4_6__selectprim_ge_windowdimensions__2__2__2__windowstri3918878843829093576.mlir
  stablehlo/testdata/select_and_scatter_add_padding_shape_float32_2_4_6__selectprim_ge_windowdimensions__2__2__2__windows7745011263169515186.mlir
  stablehlo/testdata/select_and_scatter_add_select_prim_shape_float32_2_4_6__selectprim_le_windowdimensions__2__2__2__win3195252304676505603.mlir
  stablehlo/testdata/select_and_scatter_add_tpu_dtypes_shape_bfloat16_2_4_6__selectprim_ge_windowdimensions__1__3__1__win7138983918417685208.mlir
  stablehlo/testdata/select_and_scatter_add_tpu_dtypes_shape_float16_2_4_6__selectprim_ge_windowdimensions__1__3__1__wind7040864175077487301.mlir
  stablehlo/testdata/select_and_scatter_add_tpu_dtypes_shape_float32_2_4_6__selectprim_ge_windowdimensions__1__3__1__wind-6867541439412093951.mlir
  stablehlo/testdata/select_and_scatter_add_tpu_dtypes_shape_int16_2_4_6__selectprim_ge_windowdimensions__1__3__1__window-1515521222491375303.mlir
  stablehlo/testdata/select_and_scatter_add_tpu_dtypes_shape_int32_2_4_6__selectprim_ge_windowdimensions__1__3__1__window-8827730052770528042.mlir
  stablehlo/testdata/select_and_scatter_add_tpu_dtypes_shape_uint16_2_4_6__selectprim_ge_windowdimensions__1__3__1__windo2756544409025303514.mlir
  stablehlo/testdata/select_and_scatter_add_tpu_dtypes_shape_uint32_2_4_6__selectprim_ge_windowdimensions__1__3__1__windo-6304561722695857269.mlir
  stablehlo/testdata/select_and_scatter_add_window_dimensions_shape_float32_2_4_6__selectprim_ge_windowdimensions__1__2__2730457018571670567.mlir
  stablehlo/testdata/select_and_scatter_add_window_strides_shape_float32_2_4_6__selectprim_ge_windowdimensions__2__2__2__-3819633790000483811.mlir
  stablehlo/tests/infer_stablehlo.mlir
  stablehlo/tests/interpret_select_and_scatter.mlir
  stablehlo/tests/verify_select_and_scatter.mlir
Labels: Interpreter, Migrate to MHLO

#1609 Bump patch version after integrate 0.13.3 -> 0.13.4
  stablehlo/dialect/Version.h
Labels: Integrations

#1610 [RFC] Add StableHLO => Linalg lowering to openxla/stablehlo
  rfcs/20230528-linalg.md
Labels: RFC

#1611 Unify references to discussion threads in RFCs
  rfcs/20220912-compatibility.md
  rfcs/20221031-fp8.md
  rfcs/20230210-sparsity.md
  rfcs/20230309-compatibility.md
  rfcs/20230309-e4m3b11.md
  rfcs/20230321-fp8_fnuz.md
  rfcs/20230525-compatibility.md
Labels: Process

#1612 [CMake] Make StableHLO build consistent with MLIR-HLO
  CMakeLists.txt
Labels: Build

#1616 Integrate LLVM at llvm/llvm-project@0258a53521cf
  WORKSPACE.bazel
  build_tools/llvm_version.txt
Labels: Integrations

#1617 [chlo] Add HLO_CompatibleOperandsAndResultElementType to validate quantized types
  stablehlo/dialect/Base.cpp
  stablehlo/dialect/Base.h
  stablehlo/dialect/Base.td
  stablehlo/dialect/ChloOps.cpp
  stablehlo/dialect/ChloOps.td
  stablehlo/tests/ops_chlo.mlir
Labels: Verification, Migrate from MHLO

#1618 Make getMinVersion() and getMaxVersion() parse version numbers at compile time
  stablehlo/dialect/VhloAttrs.td
  stablehlo/dialect/VhloEnums.td
  stablehlo/dialect/VhloOps.td
  stablehlo/dialect/VhloTypes.td
Labels: Migrate from MHLO, Compatibility

#1477 Specification for quantized ConvolutionOp
  docs/spec.md
Labels: Spec

#1619 Implement EvalMinOp and EvalClampOp in shape refinement
  stablehlo/tests/stablehlo_refine_shapes.mlir
  stablehlo/transforms/StablehloRefineShapes.cpp
Labels: Type inference, Dynamism

#1620 Add stablehlo-lsp-server
  stablehlo/tools/CMakeLists.txt
  stablehlo/tools/StablehloLspServerMain.cpp
Labels: Integrations

#1621 Integrate LLVM at llvm/llvm-project@261b693afd82
  BUILD.bazel
  WORKSPACE.bazel
  build_tools/llvm_version.txt
  stablehlo/tools/CMakeLists.txt
  stablehlo/tools/StablehloOptMain.cpp
Labels: Integrations

#1622 Further integrate stablehlo-lsp-server into our build
  BUILD.bazel
  stablehlo/tools/CMakeLists.txt
  stablehlo/tools/StablehloLspServerMain.cpp
Labels: Integrations

#1624 Actually bump MLIR Bytecode Format Version to 5
  docs/vhlo.md
  stablehlo/dialect/Version.cpp
  stablehlo/dialect/Version.h
  stablehlo/dialect/VhloDialect.td
  stablehlo/tests/stablehlo_legalize_to_vhlo.0_14_0.mlir
  stablehlo/tests/stablehlo_legalize_to_vhlo.0_14_0.mlir.bc
Labels: Integrations

#1626 Augment the `spec_checklist.md`
  docs/reference_checklist.md
  docs/spec_checklist.md
Labels: Verification

#1496 Specification for UniformQuantizeOp and UniformDequantizeOp
  docs/spec.md
  docs/status.md
  stablehlo/dialect/StablehloOps.td
  stablehlo/dialect/TypeInference.cpp
  stablehlo/tests/infer_stablehlo.mlir
  stablehlo/tests/ops_stablehlo.mlir
Labels: Spec

#1629 Refactor the grammar for element types
  docs/spec.md
Labels: Spec

#1623 Also build //... with Bazel in CI
  build_tools/github_actions/ci_build_bazel.sh
Labels: Integrations

#1625 Add license header to StablehloLspServerMain.cpp
  stablehlo/tools/StablehloLspServerMain.cpp
Labels: Process

#1630 Disable OOB gather tests
  stablehlo/testdata/gather_from_take_indices_name__5_oob__axis_0_enable_xla_True_mode_fill.mlir
  stablehlo/testdata/gather_from_take_indices_name__5_oob__axis_1_enable_xla_True_mode_fill.mlir
  stablehlo/testdata/gather_from_take_indices_name__5_oob__axis_2_enable_xla_True_mode_fill.mlir
  stablehlo/testdata/gather_from_take_indices_name__6_neg__axis_0_enable_xla_True_mode_clip.mlir
  stablehlo/testdata/gather_from_take_indices_name__6_neg__axis_1_enable_xla_True_mode_clip.mlir
  stablehlo/testdata/gather_from_take_indices_name__7_neg__axis_0_enable_xla_True_mode_clip.mlir
  stablehlo/testdata/gather_from_take_indices_name__7_neg__axis_1_enable_xla_True_mode_clip.mlir
  stablehlo/testdata/gather_from_take_indices_name__8_neg_oob__axis_0_enable_xla_True_mode_clip.mlir
  stablehlo/testdata/gather_from_take_indices_name__8_neg_oob__axis_0_enable_xla_True_mode_fill.mlir
  stablehlo/testdata/gather_from_take_indices_name__8_neg_oob__axis_1_enable_xla_True_mode_clip.mlir
  stablehlo/testdata/gather_from_take_indices_name__8_neg_oob__axis_1_enable_xla_True_mode_fill.mlir
  stablehlo/testdata/gather_from_take_indices_name__8_neg_oob__axis_2_enable_xla_True_mode_fill.mlir
Labels: Interpreter

#1562 Add scheduled CI for StableHLO builds against LLVM@HEAD
  .github/workflows/buildAndTestCMake.yml
Labels: Build, Compatibility

#1638 Sharpen wording in compatibility.md
  docs/compatibility.md
Labels: Compatibility

#1637 Fix a constraint in `bitcast_convert` op
  docs/spec.md
Labels: Spec

#1421 Remove uses of ArgResultAliasAttr as it is not used, specced, or supported in VHLO
  stablehlo/dialect/StablehloAttrs.td
  stablehlo/dialect/StablehloBytecode.cpp
  stablehlo/dialect/StablehloOps.cpp
  stablehlo/dialect/StablehloOps.h
  stablehlo/dialect/VhloAttrs.td
  stablehlo/dialect/VhloBytecode.cpp
  stablehlo/tests/ops_stablehlo.mlir
  stablehlo/tests/ops_stablehlo_roundtrip.mlir
  stablehlo/transforms/VhloLegalizeToStablehlo.cpp
Labels: Compatibility

#1640 Integrate LLVM at llvm/llvm-project@213709e7be03
  WORKSPACE.bazel
  build_tools/llvm_version.txt
Labels: Integrations

#1639 Fix typo in a link in one of the RFC
  rfcs/20230525-compatibility.md
Labels: Process

#1614 Further align StableHLO and MLIR-HLO builds
  CMakeLists.txt
Labels: Build

#1635 Add interpreter for AfterAllOp
  BUILD.bazel
  docs/spec.md
  docs/status.md
  stablehlo/dialect/StablehloOps.td
  stablehlo/reference/CMakeLists.txt
  stablehlo/reference/InterpreterValue.cpp
  stablehlo/reference/InterpreterValue.h
  stablehlo/reference/Ops.cpp
  stablehlo/reference/Ops.h
  stablehlo/reference/Scope.cpp
  stablehlo/reference/Scope.h
  stablehlo/reference/Token.cpp
  stablehlo/reference/Token.h
  stablehlo/tests/BUILD.bazel
  stablehlo/tests/infer_stablehlo.mlir
  stablehlo/tests/interpret_after_all.mlir
  stablehlo/tools/StablehloTranslateMain.cpp
Labels: Interpreter, Migrate to MHLO

#1636 Add interpreter for OptimizationBarrierOp
  docs/spec.md
  docs/status.md
  stablehlo/dialect/StablehloOps.td
  stablehlo/dialect/TypeInference.cpp
  stablehlo/reference/Ops.cpp
  stablehlo/reference/Ops.h
  stablehlo/tests/infer_stablehlo.mlir
  stablehlo/tests/interpret_optimization_barrier.mlir
  stablehlo/tests/ops_stablehlo.mlir
Labels: Interpreter, Migrate to MHLO

#1644 Specialize `getResult()` calls to specific `FooOp` classes
  stablehlo/reference/Ops.cpp
Labels: Interpreter

#1541 Avoid out of bound reads in the spec of GatherOp
  docs/images/spec/gather.svg
  docs/spec.md
  stablehlo/reference/Ops.cpp
  stablehlo/testdata/gather_batchdims_shape__2__3__3__start_indices_shape__2__3__slice_sizes__1__3__2__enable_xla_True.mlir
  stablehlo/testdata/gather_batchdims_shape__3__10__start_indices_shape__3__2__slice_sizes__1__5__enable_xla_True.mlir
  stablehlo/testdata/gather_from_slicing_name___-1_-5_-200___enable_xla_True.mlir
  stablehlo/testdata/gather_from_slicing_name___5_-2_300___enable_xla_True.mlir
  stablehlo/testdata/gather_from_take_indices_name__5_oob__axis_0_enable_xla_True_mode_clip.mlir
  stablehlo/testdata/gather_from_take_indices_name__5_oob__axis_0_enable_xla_True_mode_fill.mlir
  stablehlo/testdata/gather_from_take_indices_name__5_oob__axis_1_enable_xla_True_mode_clip.mlir
  stablehlo/testdata/gather_from_take_indices_name__5_oob__axis_1_enable_xla_True_mode_fill.mlir
  stablehlo/testdata/gather_from_take_indices_name__5_oob__axis_2_enable_xla_True_mode_clip.mlir
  stablehlo/testdata/gather_from_take_indices_name__5_oob__axis_2_enable_xla_True_mode_fill.mlir
  stablehlo/testdata/gather_from_take_indices_name__6_neg__axis_0_enable_xla_True_mode_clip.mlir
  stablehlo/testdata/gather_from_take_indices_name__6_neg__axis_1_enable_xla_True_mode_clip.mlir
  stablehlo/testdata/gather_from_take_indices_name__6_neg__axis_2_enable_xla_True_mode_clip.mlir
  stablehlo/testdata/gather_from_take_indices_name__7_neg__axis_0_enable_xla_True_mode_clip.mlir
  stablehlo/testdata/gather_from_take_indices_name__7_neg__axis_1_enable_xla_True_mode_clip.mlir
  stablehlo/testdata/gather_from_take_indices_name__7_neg__axis_2_enable_xla_True_mode_clip.mlir
  stablehlo/testdata/gather_from_take_indices_name__8_neg_oob__axis_0_enable_xla_True_mode_clip.mlir
  stablehlo/testdata/gather_from_take_indices_name__8_neg_oob__axis_0_enable_xla_True_mode_fill.mlir
  stablehlo/testdata/gather_from_take_indices_name__8_neg_oob__axis_1_enable_xla_True_mode_clip.mlir
  stablehlo/testdata/gather_from_take_indices_name__8_neg_oob__axis_1_enable_xla_True_mode_fill.mlir
  stablehlo/testdata/gather_from_take_indices_name__8_neg_oob__axis_2_enable_xla_True_mode_clip.mlir
  stablehlo/testdata/gather_from_take_indices_name__8_neg_oob__axis_2_enable_xla_True_mode_fill.mlir
  stablehlo/tests/interpret_gather.mlir
Labels: Spec, Interpreter

#1479 Add interpreter for ReducePrecisionOp
  docs/spec.md
  docs/status.md
  stablehlo/dialect/StablehloOps.td
  stablehlo/dialect/TypeInference.cpp
  stablehlo/reference/Element.cpp
  stablehlo/reference/Element.h
  stablehlo/reference/Ops.cpp
  stablehlo/reference/Ops.h
  stablehlo/testdata/reduce_precision_in_bfloat16_5_7__out_bfloat16_5_7.mlir
  stablehlo/testdata/reduce_precision_in_bfloat16_5_7__out_float16_5_7.mlir
  stablehlo/testdata/reduce_precision_in_bfloat16_5_7__out_float32_5_7.mlir
  stablehlo/testdata/reduce_precision_in_bfloat16___out_bfloat16.mlir
  stablehlo/testdata/reduce_precision_in_bfloat16___out_float16.mlir
  stablehlo/testdata/reduce_precision_in_bfloat16___out_float32.mlir
  stablehlo/testdata/reduce_precision_in_float16_5_7__out_bfloat16_5_7.mlir
  stablehlo/testdata/reduce_precision_in_float16_5_7__out_float16_5_7.mlir
  stablehlo/testdata/reduce_precision_in_float16_5_7__out_float32_5_7.mlir
  stablehlo/testdata/reduce_precision_in_float16___out_bfloat16.mlir
  stablehlo/testdata/reduce_precision_in_float16___out_float16.mlir
  stablehlo/testdata/reduce_precision_in_float16___out_float32.mlir
  stablehlo/testdata/reduce_precision_in_float32_5_7__out_bfloat16_5_7.mlir
  stablehlo/testdata/reduce_precision_in_float32_5_7__out_float16_5_7.mlir
  stablehlo/testdata/reduce_precision_in_float32___out_bfloat16.mlir
  stablehlo/testdata/reduce_precision_in_float32___out_float16.mlir
  stablehlo/testdata/reduce_precision_in_float32___out_float32.mlir
  stablehlo/tests/infer_stablehlo.mlir
  stablehlo/tests/interpret_reduce_precision.mlir
  stablehlo/tests/ops_stablehlo.mlir
Labels: Interpreter, Migrate to MHLO

#1642 Further update compatibility.md
  docs/compatibility.md
Labels: Compatibility

#1649 Patch bazel build dependency issues found during integrate
  BUILD.bazel
Labels: Integrations, Migrate from MHLO

#1567 Specification of the remaining quantized data movement ops
  docs/spec.md
Labels: Spec

#1654 Bump patch version 0.14.0 -> 0.14.1
  stablehlo/dialect/Version.h
Labels: Process

#1652 Clarify what "unspecced features" means
  docs/compatibility.md
Labels: Compatibility

#1655 Integrate LLVM at llvm/llvm-project@989879f8fded
  WORKSPACE.bazel
  build_tools/llvm_version.txt
Labels: Integrations, Process

#1608 Adding the missing quantized-type support in the ODS
  stablehlo/dialect/Base.td
  stablehlo/dialect/StablehloOps.td
  stablehlo/tests/ops_stablehlo.mlir
Labels: Spec

#1659 Add HLO_CompatibleOperandsAndResultElementType to CHLO broadcast MinOp and MaxOp
  stablehlo/dialect/ChloOps.td
  stablehlo/tests/ops_chlo.mlir
Labels: Migrate from MHLO

#1661 Bump patch version after integrate 0.14.1 -> 0.14.2
  stablehlo/dialect/Version.h
Labels: Integrations

#1657 Add custom print for stablehlo.slice
  stablehlo/conversions/tosa/tests/unary.mlir
  stablehlo/dialect/AssemblyFormat.cpp
  stablehlo/dialect/AssemblyFormat.h
  stablehlo/dialect/StablehloOps.cpp
  stablehlo/dialect/StablehloOps.td
  stablehlo/reference/Ops.cpp
  stablehlo/tests/print_stablehlo.mlir
  stablehlo/tests/stablehlo_canonicalize_dynamism.mlir
Labels: Prettyprinting

#1663 Update 20230210-sparsity.md
  rfcs/20230210-sparsity.md
Labels: Process
