Repository openxla/stablehlo, pull requests merged in 2023-11, with the labels that each got.

#1819 Integrate LLVM at llvm/llvm-project@6ae7b735dbd5
  WORKSPACE.bazel
  build_tools/llvm_version.txt
  stablehlo/tests/infer_stablehlo.mlir
  stablehlo/tests/legalize_stablehlo_to_vhlo_invalid.mlir
  stablehlo/tests/ops_sparse.mlir
  stablehlo/tests/ops_stablehlo.mlir
Labels: Integrations

#1803 Add Documentation on Reference Interpreter
  docs/interpreter_status.md
Labels: Interpreter

#1821 Bump patch version after integrate 0.14.28 -> 0.14.29
  stablehlo/dialect/Version.h
Labels: Integrations

#1822 Integrate LLVM at llvm/llvm-project@46732e2abb34
  WORKSPACE.bazel
  build_tools/llvm_version.txt
  stablehlo/conversions/tosa/tests/nullary.mlir
  stablehlo/conversions/tosa/transforms/StablehloLegalizeToTosa.cpp
Labels: Integrations

#1823 Bump patch version after integrate 0.14.29 -> 0.14.30
  stablehlo/dialect/Version.h
Labels: Integrations

#1825 Print optional attr-dict on stablehlo.reduce
  stablehlo/dialect/StablehloOps.cpp
  stablehlo/tests/print_reduce.mlir
Labels: Migrate from MHLO

#1826 Sort dependencies of the stablehlo_ci_tests target
  BUILD.bazel
Labels: Integrations

#1830 Migrate InterpreterDialect and CheckDialect to use properties
  stablehlo/reference/InterpreterOps.td
  stablehlo/tests/CheckOps.td
Labels: Integrations

#1832 Integrate LLVM at llvm/llvm-project@f9404a1b57a5
  WORKSPACE.bazel
  build_tools/llvm_version.txt
Labels: Integrations

#1833 Fix issues found during the recent downstream integrate
  BUILD.bazel
  stablehlo/reference/Ops.cpp
Labels: Migrate from MHLO

#1835 Shorten some file and target names under reference/
  BUILD.bazel
  stablehlo/reference/Api.cpp
  stablehlo/reference/Api.h
  stablehlo/reference/CMakeLists.txt
  stablehlo/reference/Configuration.cpp
  stablehlo/reference/Configuration.h
  stablehlo/reference/InterpreterOps.cpp
  stablehlo/reference/InterpreterOps.h
  stablehlo/reference/Ops.cpp
  stablehlo/reference/Ops.h
  stablehlo/reference/Scope.cpp
  stablehlo/reference/Scope.h
  stablehlo/reference/Value.cpp
  stablehlo/reference/Value.h
  stablehlo/tests/BUILD.bazel
  stablehlo/tools/CMakeLists.txt
  stablehlo/tools/StablehloTranslateMain.cpp
Labels: Interpreter

#1836 Bump patch version after integrate 0.15.0 -> 0.15.1
  stablehlo/dialect/Version.h
Labels: Integrations

#1837 Integrate LLVM at llvm/llvm-project@75d6795e4202
  WORKSPACE.bazel
  build_tools/llvm_version.txt
Labels: Integrations

#1839 Fix issues found during the recent downstream integrate
  BUILD.bazel
  stablehlo/dialect/Base.h
  stablehlo/tests/BUILD.bazel
Labels: Migrate from MHLO

#1834 Minor code style updates
  stablehlo/transforms/Passes.h
Labels: Migrate from MHLO

#1838 Bump patch version after integrate 0.15.1 -> 0.15.2
  stablehlo/dialect/Version.h
Labels: Integrations

#1829 Add dependency on LLVM's not tool
  stablehlo/tests/CMakeLists.txt
Labels: Build

#1817 linalg: copy subset of stablehlo-to-linalg passes from IREE
  BUILD.bazel
  stablehlo/conversions/CMakeLists.txt
  stablehlo/conversions/linalg/CMakeLists.txt
  stablehlo/conversions/linalg/tests/BUILD.bazel
  stablehlo/conversions/linalg/tests/CMakeLists.txt
  stablehlo/conversions/linalg/tests/convolution.mlir
  stablehlo/conversions/linalg/tests/dot-product.mlir
  stablehlo/conversions/linalg/tests/gather.mlir
  stablehlo/conversions/linalg/tests/lit.cfg.py
  stablehlo/conversions/linalg/tests/lit.site.cfg.py.in
  stablehlo/conversions/linalg/tests/miscellaneous.mlir
  stablehlo/conversions/linalg/tests/pointwise.mlir
  stablehlo/conversions/linalg/tests/random.mlir
  stablehlo/conversions/linalg/tests/reduce.mlir
  stablehlo/conversions/linalg/transforms/CMakeLists.txt
  stablehlo/conversions/linalg/transforms/LegalizeToLinalgUtils.cpp
  stablehlo/conversions/linalg/transforms/LegalizeToLinalgUtils.h
  stablehlo/conversions/linalg/transforms/MapStablehloToScalarOp.h
  stablehlo/conversions/linalg/transforms/PassDetail.h
  stablehlo/conversions/linalg/transforms/Passes.h
  stablehlo/conversions/linalg/transforms/Passes.td
  stablehlo/conversions/linalg/transforms/Rewriters.h
  stablehlo/conversions/linalg/transforms/StablehloLegalizeToLinalg.cpp
  stablehlo/conversions/linalg/transforms/StablehloToArith.cpp
  stablehlo/conversions/linalg/transforms/StablehloToLinalgConvolution.cpp
  stablehlo/conversions/linalg/transforms/StablehloToLinalgDotProduct.cpp
  stablehlo/conversions/linalg/transforms/StablehloToLinalgPointwise.cpp
  stablehlo/conversions/linalg/transforms/StablehloToLinalgRandom.cpp
  stablehlo/conversions/linalg/transforms/StablehloToLinalgReduce.cpp
  stablehlo/conversions/linalg/transforms/TypeConversion.cpp
  stablehlo/conversions/linalg/transforms/TypeConversion.h
  stablehlo/tools/CMakeLists.txt
  stablehlo/tools/StablehloOptMain.cpp
Labels: Integrations

#1845 Integrate LLVM at llvm/llvm-project@c5dd1bbcc37e
  WORKSPACE.bazel
  build_tools/llvm_version.txt
Labels: Integrations

#1847 Rename StableHlo -> Stablehlo in methods
  stablehlo/conversions/linalg/transforms/MapStablehloToScalarOp.h
  stablehlo/conversions/linalg/transforms/Rewriters.h
  stablehlo/conversions/linalg/transforms/StablehloLegalizeToLinalg.cpp
  stablehlo/conversions/linalg/transforms/StablehloToArith.cpp
  stablehlo/conversions/linalg/transforms/StablehloToLinalgConvolution.cpp
  stablehlo/conversions/linalg/transforms/StablehloToLinalgDotProduct.cpp
  stablehlo/conversions/linalg/transforms/StablehloToLinalgPointwise.cpp
  stablehlo/conversions/linalg/transforms/StablehloToLinalgRandom.cpp
  stablehlo/conversions/linalg/transforms/StablehloToLinalgReduce.cpp
Labels: Integrations

#1850 Integrate LLVM at llvm/llvm-project@506c47df00bb
  WORKSPACE.bazel
  build_tools/llvm_version.txt
  stablehlo/tests/print_stablehlo.mlir
Labels: Integrations

#1846 Prevent OOB indexing in StableHLO/MHLO ops.
  BUILD.bazel
  stablehlo/conversions/linalg/transforms/CMakeLists.txt
  stablehlo/conversions/linalg/transforms/PassDetail.h
  stablehlo/conversions/linalg/transforms/Passes.h
  stablehlo/conversions/linalg/transforms/Passes.td
  stablehlo/conversions/linalg/transforms/StablehloLegalizeToLinalg.cpp
  stablehlo/dialect/TypeInference.cpp
  stablehlo/dialect/TypeInference.h
  stablehlo/tests/ops_stablehlo.mlir
Labels: Integrations

#1809 [RFC] Add collective_broadcast to the StableHLO specification
  rfcs/20231017-collective-broadcast.md
Labels: RFC

#1852 Fix markdown lint issues
  rfcs/20231017-collective-broadcast.md
Labels: RFC

#1853 Bump patch version after integrate 0.15.2 -> 0.15.3
  stablehlo/dialect/Version.h
Labels: Integrations

#1854 Bump patch version after integrate 0.15.3 -> 0.15.4
  stablehlo/dialect/Version.h
Labels: Integrations

#1855 Fix clang-tidy error
  stablehlo/conversions/linalg/transforms/MapStablehloToScalarOp.h
Labels: Integrations

#1857 Integrate LLVM at llvm/llvm-project@2b0b0ad7e760
  WORKSPACE.bazel
  build_tools/llvm_version.txt
Labels: Integrations

#1858 Bump patch version after integrate 0.15.4 -> 0.15.5
  stablehlo/dialect/Version.h
Labels: Integrations

#1860 Fix typo in all_reduce constraint comment
  stablehlo/dialect/TypeInference.cpp
Labels: Interpreter

#1861 Integrate LLVM at llvm/llvm-project@5e5a22caf88a
  WORKSPACE.bazel
  build_tools/llvm_version.txt
Labels: Integrations

#1863 Fix 0.15.0 compatibility test to use proper run commands
  stablehlo/tests/stablehlo_legalize_to_vhlo.0_15_0.mlir
Labels: Compatibility

#1865 Clarifying the semantics of `baseline_type` meta function
  docs/spec.md
Labels: Spec

#1828 Serialize MLIR type when instrumenting reference interpreter values
  stablehlo/reference/InterpreterOps.cpp
  stablehlo/reference/InterpreterOps.td
  stablehlo/tests/CheckOps.cpp
  stablehlo/tests/CheckOps.td
Labels: Interpreter

#1866 Integrate LLVM at llvm/llvm-project@511ba45a47d6
  WORKSPACE.bazel
  build_tools/llvm_version.txt
Labels: Integrations
