Repository openxla/stablehlo, pull requests merged in 2023-08, with the labels that each got.

#1707 Patch changes from previous integrate
  stablehlo/dialect/Base.cpp
  stablehlo/dialect/StablehloOps.cpp
  stablehlo/dialect/TypeInference.cpp
  stablehlo/reference/Ops.cpp
Labels: Integrations, Migrate from MHLO

#1708 Patch BUILD.bazel files after integrate
  BUILD.bazel
Labels: Integrations

#1711 Integrate LLVM at llvm/llvm-project@e68ffa373f7f
  WORKSPACE.bazel
  build_tools/llvm_version.txt
Labels: Integrations

#1709 Add interpreter for ReplicaIdOp
  BUILD.bazel
  docs/spec.md
  docs/status.md
  stablehlo/reference/CMakeLists.txt
  stablehlo/reference/InterpreterOps.cpp
  stablehlo/reference/InterpreterOps.h
  stablehlo/reference/InterpreterOps.td
  stablehlo/reference/Ops.cpp
  stablehlo/reference/Ops.h
  stablehlo/reference/Process.h
  stablehlo/tests/interpret_replica_id.mlir
  stablehlo/tests/ops_interpreter.mlir
  stablehlo/tests/ops_stablehlo.mlir
  stablehlo/tools/CMakeLists.txt
  stablehlo/tools/StablehloOptMain.cpp
  stablehlo/tools/StablehloTranslateMain.cpp
Labels: Interpreter

#1713 Patch BUILD.bazel after integrate
  BUILD.bazel
Labels: Integrations

#1700 Using dequant-op-quant for convolution and dot_general
  docs/spec.md
Labels: Spec

#1714 Bump patch version after integrate 0.14.9 -> 0.14.10
  stablehlo/dialect/Version.h
Labels: Integrations

#1717 Typo fixes in the example provided for the spec of CollectivePermute
  docs/spec.md
  stablehlo/dialect/StablehloOps.td
Labels: Spec

#1718 Integrate LLVM at llvm/llvm-project@9b6aaf1dcaf5
  WORKSPACE.bazel
  build_tools/llvm_version.txt
Labels: Integrations

#1719 Bump patch version after integrate 0.14.10 -> 0.14.11
  stablehlo/dialect/Version.h
Labels: Integrations

#1715 Add interpreter for CollectivePermuteOp
  BUILD.bazel
  docs/spec.md
  docs/status.md
  stablehlo/dialect/StablehloOps.td
  stablehlo/dialect/TypeInference.cpp
  stablehlo/reference/CMakeLists.txt
  stablehlo/reference/InterpreterOps.cpp
  stablehlo/reference/InterpreterOps.h
  stablehlo/reference/Ops.cpp
  stablehlo/reference/Ops.h
  stablehlo/reference/Process.cpp
  stablehlo/reference/Process.h
  stablehlo/reference/ProcessGrid.cpp
  stablehlo/reference/ProcessGrid.h
  stablehlo/reference/Tensor.h
  stablehlo/tests/infer_stablehlo.mlir
  stablehlo/tests/interpret_collective_permute.mlir
  stablehlo/tests/ops_stablehlo.mlir
  stablehlo/tools/CMakeLists.txt
  stablehlo/tools/StablehloTranslateMain.cpp
Labels: Interpreter, Migrate to MHLO

#1723 Add interpreter for OutfeedOp
  docs/spec.md
  docs/status.md
  stablehlo/dialect/StablehloOps.td
  stablehlo/reference/InterpreterOps.cpp
  stablehlo/reference/Ops.cpp
  stablehlo/reference/Ops.h
  stablehlo/reference/Process.cpp
  stablehlo/reference/Process.h
  stablehlo/reference/ProcessGrid.cpp
  stablehlo/reference/ProcessGrid.h
  stablehlo/tests/interpret_outfeed.mlir
  stablehlo/tests/ops_interpreter.mlir
  stablehlo/tests/ops_stablehlo.mlir
Labels: Interpreter, Migrate to MHLO

#1721 Add interpreter for AllReduceOp
  docs/spec.md
  docs/status.md
  stablehlo/dialect/StablehloOps.cpp
  stablehlo/dialect/StablehloOps.td
  stablehlo/dialect/TypeInference.cpp
  stablehlo/dialect/TypeInference.h
  stablehlo/reference/Ops.cpp
  stablehlo/reference/Ops.h
  stablehlo/reference/Process.cpp
  stablehlo/reference/Process.h
  stablehlo/reference/ProcessGrid.cpp
  stablehlo/reference/ProcessGrid.h
  stablehlo/reference/Tensor.cpp
  stablehlo/reference/Tensor.h
  stablehlo/tests/interpret_all_reduce.mlir
  stablehlo/tests/ops_stablehlo.mlir
Labels: Interpreter, Migrate to MHLO

#1728 Fix typo in Passes.td
  stablehlo/conversions/tosa/transforms/Passes.td
Labels: Integrations

#1729 fix BUILD.bazel
  BUILD.bazel
Labels: Build

#1724 Port of tensorflow/mlir-hlo@5aa3df6 to avoid invalid access
  stablehlo/dialect/StablehloOps.cpp
Labels: Migrate from MHLO

#1734 Cleanup after a downstream integrate
  BUILD.bazel
  stablehlo/reference/Ops.cpp
  stablehlo/reference/ProcessGrid.cpp
  stablehlo/reference/ProcessGrid.h
  stablehlo/tools/StablehloTranslateMain.cpp
Labels: Integrations

#1735 Bump patch version after integrate 0.14.11 -> 0.14.12
  stablehlo/dialect/Version.h
Labels: Integrations

#1736 Integrate LLVM at llvm/llvm-project@913f21ae5c46
  WORKSPACE.bazel
  build_tools/llvm_version.txt
  stablehlo/dialect/ChloOps.cpp
Labels: Integrations

#1737 Fix race condition in `ProcessGrid::rendezvous`
  stablehlo/reference/ProcessGrid.cpp
  stablehlo/reference/ProcessGrid.h
Labels: Interpreter

#1738 Use `ChannelId` alias instead of `int64_t`
  stablehlo/reference/Ops.cpp
  stablehlo/reference/Ops.h
  stablehlo/reference/Process.cpp
  stablehlo/reference/Process.h
  stablehlo/reference/ProcessGrid.cpp
  stablehlo/reference/ProcessGrid.h
Labels: Interpreter

#1740 Bump patch version after integrate 0.14.12 -> 0.14.13
  stablehlo/dialect/Version.h
Labels: Integrations

#1739 Fix typo in `vhlo.md` instructions
  docs/vhlo.md
Labels: Compatibility

#1743 Integrate LLVM at llvm/llvm-project@cad3130a23da
  WORKSPACE.bazel
  build_tools/llvm_version.txt
  stablehlo/conversions/tosa/tests/binary.mlir
  stablehlo/conversions/tosa/tests/nullary.mlir
  stablehlo/conversions/tosa/tests/ternary.mlir
  stablehlo/conversions/tosa/tests/unary.mlir
  stablehlo/conversions/tosa/transforms/StablehloLegalizeToTosa.cpp
  stablehlo/dialect/VhloOps.cpp
  stablehlo/dialect/VhloTypes.h
  stablehlo/transforms/StablehloLegalizeToVhlo.cpp
  stablehlo/transforms/VhloLegalizeToStablehlo.cpp
Labels: Integrations

#1742 Followup on port of tensorflow/mlir-hlo@5aa3df6
  stablehlo/tests/ops_stablehlo.mlir
Labels: Migrate from MHLO

#1744 Bump patch version after integrate 0.14.13 -> 0.14.14
  stablehlo/dialect/Version.h
Labels: Integrations

#1702 Add specification for per-axis quantization scheme
  docs/spec.md
Labels: Spec

#1727 Add interpreter for AllGatherOp
  docs/spec.md
  docs/status.md
  stablehlo/dialect/StablehloOps.cpp
  stablehlo/dialect/StablehloOps.td
  stablehlo/dialect/TypeInference.cpp
  stablehlo/dialect/TypeInference.h
  stablehlo/reference/Ops.cpp
  stablehlo/reference/Ops.h
  stablehlo/tests/interpret_all_gather.mlir
  stablehlo/tests/ops_stablehlo.mlir
Labels: Interpreter, Migrate to MHLO

#1730 Add interpreter for AllToAllOp
  docs/spec.md
  docs/status.md
  stablehlo/dialect/StablehloOps.td
  stablehlo/dialect/TypeInference.cpp
  stablehlo/reference/Ops.cpp
  stablehlo/reference/Ops.h
  stablehlo/tests/infer_stablehlo.mlir
  stablehlo/tests/interpret_all_to_all.mlir
  stablehlo/tests/ops_stablehlo.mlir
Labels: Interpreter, Migrate to MHLO

#1731 Add interpreter for ReduceScatterOp
  docs/spec.md
  docs/status.md
  stablehlo/dialect/StablehloOps.cpp
  stablehlo/dialect/StablehloOps.td
  stablehlo/dialect/TypeInference.cpp
  stablehlo/dialect/TypeInference.h
  stablehlo/reference/Ops.cpp
  stablehlo/reference/Ops.h
  stablehlo/tests/interpret_reduce_scatter.mlir
  stablehlo/tests/ops_stablehlo.mlir
Labels: Interpreter, Migrate to MHLO

#1749 Integrate LLVM at llvm/llvm-project@f806be5eaae1
  WORKSPACE.bazel
  build_tools/llvm_version.txt
Labels: Integrations

#1751 Clang tidy fix
  stablehlo/reference/Ops.cpp
Labels: Integrations

#1750 [NFC] Explicitly set dialects to usePropertiesForAttributes=0
  stablehlo/dialect/ChloOps.h
  stablehlo/dialect/ChloOps.td
  stablehlo/dialect/StablehloOps.td
  stablehlo/dialect/VhloDialect.td
  stablehlo/reference/InterpreterOps.td
  stablehlo/tests/CheckOps.h
  stablehlo/tests/CheckOps.td
Labels: Integrations

#1752 Remove XLA attribute from test
  stablehlo/tests/ops_stablehlo_roundtrip.mlir
Labels: Integrations

#1754 Bump patch version after integrate 0.14.14 -> 0.14.15
  stablehlo/dialect/Version.h
Labels: Integrations

#1756 Disable multithreaded tests
  stablehlo/tests/interpret_all_gather.mlir
  stablehlo/tests/interpret_all_reduce.mlir
  stablehlo/tests/interpret_all_to_all.mlir
  stablehlo/tests/interpret_collective_permute.mlir
  stablehlo/tests/interpret_outfeed.mlir
  stablehlo/tests/interpret_reduce_scatter.mlir
Labels: Interpreter

#1753 Integrate LLVM at llvm/llvm-project@1ff0bdb86dbf
  WORKSPACE.bazel
  build_tools/llvm_version.txt
Labels: Integrations

#1757 Integrate LLVM at llvm/llvm-project@3823395c9d71
  WORKSPACE.bazel
  build_tools/llvm_version.txt
Labels: Integrations

#1759 Bump patch version after integrate 0.14.15 -> 0.14.16
  stablehlo/dialect/Version.h
Labels: Integrations

#1762 Bump patch version after integrate 0.14.16 -> 0.14.17
  stablehlo/dialect/Version.h
Labels: Integrations

#1748 Add interpreters for TupleOp and GetTupleElementOp
  docs/spec.md
  docs/status.md
  stablehlo/dialect/StablehloOps.td
  stablehlo/dialect/TypeInference.cpp
  stablehlo/reference/InterpreterValue.cpp
  stablehlo/reference/InterpreterValue.h
  stablehlo/reference/Ops.cpp
  stablehlo/reference/Ops.h
  stablehlo/reference/Scope.cpp
  stablehlo/reference/Scope.h
  stablehlo/testdata/igamma_broadcasting_lhs_float32_1_20__rhs_float32_20_20.mlir
  stablehlo/testdata/igamma_broadcasting_lhs_float32_20_20__rhs_float32_1_20.mlir
  stablehlo/testdata/igamma_dtypes_lhs_bfloat16_20_20__rhs_bfloat16_20_20.mlir
  stablehlo/testdata/igamma_dtypes_lhs_float16_20_20__rhs_float16_20_20.mlir
  stablehlo/testdata/igamma_dtypes_lhs_float32_20_20__rhs_float32_20_20.mlir
  stablehlo/testdata/igammac_broadcasting_lhs_float32_1_20__rhs_float32_20_20.mlir
  stablehlo/testdata/igammac_broadcasting_lhs_float32_20_20__rhs_float32_1_20.mlir
  stablehlo/testdata/igammac_dtypes_lhs_bfloat16_20_20__rhs_bfloat16_20_20.mlir
  stablehlo/testdata/igammac_dtypes_lhs_float16_20_20__rhs_float16_20_20.mlir
  stablehlo/testdata/igammac_dtypes_lhs_float32_20_20__rhs_float32_20_20.mlir
  stablehlo/testdata/regularized_incomplete_beta__bfloat16.mlir
  stablehlo/testdata/regularized_incomplete_beta__float16.mlir
  stablehlo/testdata/regularized_incomplete_beta__float32.mlir
  stablehlo/tests/infer_stablehlo.mlir
  stablehlo/tests/interpret_tuple_and_get_tuple_element.mlir
  stablehlo/tests/ops_stablehlo.mlir
Labels: Interpreter, Migrate to MHLO
