Repository openxla/stablehlo, pull requests merged in 2023-04, with the labels that each got.

#1347 refactor to improve evalOp function type checking
  stablehlo/reference/Ops.cpp
Labels: Interpreter

#1363 StableHLO doc review
  docs/compatibility.md
  docs/governance.md
  docs/reference.md
  docs/reference_checklist.md
  docs/roadmap.md
  docs/spec.md
  docs/spec_checklist.md
  docs/type_inference.md
  docs/vhlo.md
Labels: Process

#1374 Order functions alphabetically in Ops.cpp
  stablehlo/reference/Ops.cpp
Labels: Interpreter

#1281 Add interpreter for WhileOp
  docs/spec.md
  docs/status.md
  stablehlo/dialect/StablehloOps.td
  stablehlo/dialect/TypeInference.cpp
  stablehlo/tests/infer_stablehlo.mlir
  stablehlo/tests/interpret_while.mlir
  stablehlo/tests/verify_while.mlir
Labels: Verification, Interpreter, Migrate to MHLO

#1372 Add interpreter for ClzOp
  docs/spec.md
  docs/status.md
  stablehlo/dialect/StablehloOps.td
  stablehlo/reference/Ops.cpp
  stablehlo/reference/Ops.h
  stablehlo/tests/interpret_count_leading_zeros.mlir
Labels: Interpreter

#1342 [RFC] Add Float8E4M3FNUZ and Float8E5M2FNUZ to StableHLO.
  rfcs/20230321-fp8_fnuz.md
Labels: RFC

#1378 Introduce --stablehlo-canonicalize-dynamism
  BUILD.bazel
  stablehlo/dialect/Base.cpp
  stablehlo/dialect/Base.h
  stablehlo/dialect/ChloOps.cpp
  stablehlo/dialect/StablehloOps.cpp
  stablehlo/dialect/StablehloOps.td
  stablehlo/dialect/TypeInference.cpp
  stablehlo/dialect/TypeInference.h
  stablehlo/tests/ops_stablehlo.mlir
  stablehlo/tests/stablehlo_canonicalize_dynamism.mlir
  stablehlo/tests/stablehlo_refine_shapes.mlir
  stablehlo/transforms/CMakeLists.txt
  stablehlo/transforms/Passes.h
  stablehlo/transforms/Passes.td
  stablehlo/transforms/StablehloCanonicalizeDynamism.cpp
  stablehlo/transforms/StablehloRefineShapes.cpp
Labels: Dynamism

#1383 Drop indices_of_shape_operands once they are no longer needed
  stablehlo/dialect/Base.cpp
  stablehlo/dialect/Base.h
  stablehlo/tests/ops_stablehlo.mlir
  stablehlo/tests/stablehlo_canonicalize_dynamism.mlir
  stablehlo/transforms/StablehloCanonicalizeDynamism.cpp
  stablehlo/transforms/StablehloRefineShapes.cpp
Labels: Type inference, Dynamism

#1386 Audit casts to ShapedType and TensorType
  stablehlo/dialect/AssemblyFormat.cpp
  stablehlo/dialect/AssemblyFormat.h
  stablehlo/dialect/Base.cpp
  stablehlo/dialect/Base.h
  stablehlo/dialect/ChloOps.cpp
  stablehlo/dialect/StablehloOps.cpp
  stablehlo/dialect/TypeInference.cpp
  stablehlo/reference/Ops.cpp
  stablehlo/reference/Ops.h
  stablehlo/reference/Tensor.cpp
  stablehlo/reference/Tensor.h
  stablehlo/transforms/StablehloCanonicalizeDynamism.cpp
  stablehlo/transforms/StablehloRefineShapes.cpp
Labels: Verification, Type inference, Interpreter, Dynamism

#1391 Update IsFiniteOp test to use check op
  stablehlo/tests/interpret_is_finite.mlir
Labels: Interpreter

#1398 Unify APIs in Element.h
  stablehlo/reference/Element.cpp
  stablehlo/reference/Element.h
  stablehlo/reference/Ops.cpp
  stablehlo/tests/CheckOps.cpp
Labels: Interpreter

#1143 Sparsity RFC
  rfcs/20230210-sparsity.md
Labels: RFC

#1399 Document RFC status
  rfcs/20230210-sparsity.md
  rfcs/20230309-e4m3b11.md
  rfcs/20230321-fp8_fnuz.md
Labels: Process

#1373 Add interpreter for MapOp
  docs/spec.md
  docs/status.md
  stablehlo/dialect/StablehloOps.td
  stablehlo/dialect/TypeInference.cpp
  stablehlo/reference/Ops.cpp
  stablehlo/reference/Ops.h
  stablehlo/tests/interpret_map.mlir
  stablehlo/tests/ops_stablehlo.mlir
Labels: Interpreter, Migrate to MHLO

#1352 Introduce QuantizedType
  docs/spec.md
Labels: Spec

#1400 Add interpreter for Atan2Op
  docs/spec.md
  docs/status.md
  stablehlo/dialect/StablehloOps.td
  stablehlo/reference/Element.cpp
  stablehlo/reference/Element.h
  stablehlo/reference/Ops.cpp
  stablehlo/reference/Ops.h
  stablehlo/testdata/acos_shape_bfloat16_20_20.mlir
  stablehlo/testdata/acos_shape_float16_20_20.mlir
  stablehlo/testdata/acos_shape_float32_20_20.mlir
  stablehlo/testdata/asin_shape_bfloat16_20_20.mlir
  stablehlo/testdata/asin_shape_float16_20_20.mlir
  stablehlo/testdata/asin_shape_float32_20_20.mlir
  stablehlo/testdata/atan2_broadcasting_lhs_float32_1_20__rhs_float32_20_20.mlir
  stablehlo/testdata/atan2_broadcasting_lhs_float32_20_20__rhs_float32_1_20.mlir
  stablehlo/testdata/atan2_dtypes_lhs_bfloat16_20_20__rhs_bfloat16_20_20.mlir
  stablehlo/testdata/atan2_dtypes_lhs_float16_20_20__rhs_float16_20_20.mlir
  stablehlo/testdata/atan2_dtypes_lhs_float32_20_20__rhs_float32_20_20.mlir
  stablehlo/testdata/atan_shape_bfloat16_20_20.mlir
  stablehlo/testdata/atan_shape_float16_20_20.mlir
  stablehlo/testdata/atan_shape_float32_20_20.mlir
  stablehlo/tests/interpret_atan2.mlir
Labels: Interpreter

#1408 Document open questions in the quantization spec
  docs/spec.md
Labels: Spec

#1382 Add interpreter for SignOp.
  docs/spec.md
  docs/status.md
  stablehlo/dialect/StablehloOps.td
  stablehlo/reference/Element.cpp
  stablehlo/reference/Element.h
  stablehlo/reference/Ops.cpp
  stablehlo/reference/Ops.h
  stablehlo/testdata/sign_shape_bfloat16_20_20.mlir
  stablehlo/testdata/sign_shape_complex64_20_20.mlir
  stablehlo/testdata/sign_shape_float16_20_20.mlir
  stablehlo/testdata/sign_shape_float32_20_20.mlir
  stablehlo/testdata/sign_shape_int16_20_20.mlir
  stablehlo/testdata/sign_shape_int32_20_20.mlir
  stablehlo/testdata/sign_shape_int8_20_20.mlir
  stablehlo/testdata/sign_special_0_dtype_bfloat16.mlir
  stablehlo/testdata/sign_special_0_dtype_float16.mlir
  stablehlo/testdata/sign_special_0_dtype_float32.mlir
  stablehlo/testdata/sign_special_0_dtype_int16.mlir
  stablehlo/testdata/sign_special_0_dtype_int32.mlir
  stablehlo/testdata/sign_special_0_dtype_int8.mlir
  stablehlo/tests/interpret_sign.mlir
Labels: Interpreter

#1395 Streamline the pseudocode describing SignOp
  docs/spec.md
  stablehlo/reference/Element.cpp
  stablehlo/testdata/sign_special_0_dtype_complex64.mlir
  stablehlo/tests/interpret_sign.mlir
Labels: Spec

#1423 Add interpreter for RoundNearestEvenOp
  docs/spec.md
  docs/status.md
  stablehlo/dialect/StablehloOps.td
  stablehlo/reference/Element.cpp
  stablehlo/reference/Element.h
  stablehlo/reference/Ops.cpp
  stablehlo/reference/Ops.h
  stablehlo/testdata/round_rounding_methods_shape_float32_2_5__roundingmethod_1.mlir
  stablehlo/tests/interpret_round_nearest_even.mlir
Labels: Interpreter

#1379 Add Float8E4M3FNUZ and Float8E5M2FNUZ type support.
  docs/bytecode.md
  docs/compatibility.md
  docs/spec.md
  stablehlo/dialect/Base.td
  stablehlo/dialect/Version.h
  stablehlo/dialect/VhloBytecode.cpp
  stablehlo/dialect/VhloDialect.td
  stablehlo/dialect/VhloTypes.cpp
  stablehlo/dialect/VhloTypes.td
  stablehlo/integrations/python/tests/stablehlo.py
  stablehlo/reference/Tensor.cpp
  stablehlo/reference/Types.cpp
  stablehlo/tests/interpret_constant.mlir
  stablehlo/tests/ops_stablehlo.mlir
  stablehlo/tests/ops_stablehlo_roundtrip.mlir
  stablehlo/tests/stablehlo_legalize_to_vhlo.mlir
  stablehlo/tests/vhlo_to_version_downgrade_invalid.0_9_0.mlir
  stablehlo/transforms/VhloToVersion.cpp
Labels: Spec, Interpreter, Compatibility

#1424 Add interpreter for RoundOp
  docs/spec.md
  docs/status.md
  stablehlo/dialect/StablehloOps.td
  stablehlo/reference/Element.cpp
  stablehlo/reference/Element.h
  stablehlo/reference/Ops.cpp
  stablehlo/reference/Ops.h
  stablehlo/testdata/round_dtypes_shape_bfloat16_100_100__roundingmethod_0.mlir
  stablehlo/testdata/round_dtypes_shape_float16_100_100__roundingmethod_0.mlir
  stablehlo/testdata/round_dtypes_shape_float32_100_100__roundingmethod_0.mlir
  stablehlo/testdata/round_rounding_methods_shape_float32_2_5__roundingmethod_0.mlir
  stablehlo/tests/interpret_round_nearest_afz.mlir
Labels: Interpreter

#1427 Add missing coverage tests for power
  stablehlo/tests/interpret_power.mlir
Labels: Interpreter

#1426 Fix llvm commit lint script to use new commit for SHA
  build_tools/github_actions/lint_llvm_commit.sh
Labels: Build

#1428 Add interpreter for ShiftLeftOp
  docs/spec.md
  docs/status.md
  stablehlo/dialect/StablehloOps.td
  stablehlo/reference/Element.cpp
  stablehlo/reference/Element.h
  stablehlo/reference/Ops.cpp
  stablehlo/reference/Ops.h
  stablehlo/testdata/shift_left_dtypes_lhs_int16_20_20__rhs_int16_20_20.mlir
  stablehlo/testdata/shift_left_dtypes_lhs_int32_20_20__rhs_int32_20_20.mlir
  stablehlo/testdata/shift_left_dtypes_lhs_int8_20_20__rhs_int8_20_20.mlir
  stablehlo/testdata/shift_left_dtypes_lhs_uint16_20_20__rhs_uint16_20_20.mlir
  stablehlo/testdata/shift_left_dtypes_lhs_uint32_20_20__rhs_uint32_20_20.mlir
  stablehlo/testdata/shift_left_dtypes_lhs_uint8_20_20__rhs_uint8_20_20.mlir
  stablehlo/tests/interpret_shift_left.mlir
Labels: Interpreter

#1430 Setup for StableHLO 0.10.0, serialization test and doc updates
  docs/bytecode.md
  docs/compatibility.md
  stablehlo/tests/stablehlo_legalize_to_vhlo.0_10_0.mlir
  stablehlo/tests/stablehlo_legalize_to_vhlo.0_10_0.mlir.bc
Labels: Compatibility

#1433 Update `vhlo.md` with contribution guidelines.
  docs/vhlo.md
Labels: Process, Compatibility

#1435 Add missing dependency causing issues in google infra
  BUILD.bazel
Labels: Integrations

#1436 Add interpreter for GetDimensionSizeOp
  docs/spec.md
  docs/status.md
  stablehlo/dialect/StablehloOps.td
  stablehlo/dialect/TypeInference.cpp
  stablehlo/reference/Ops.cpp
  stablehlo/reference/Ops.h
  stablehlo/tests/interpret_get_dimension_size.mlir
  stablehlo/tests/ops_stablehlo.mlir
Labels: Interpreter, Migrate to MHLO

#1429 Add interpreter for ShiftRightLogicalOp
  docs/spec.md
  docs/status.md
  stablehlo/dialect/StablehloOps.td
  stablehlo/reference/Element.cpp
  stablehlo/reference/Element.h
  stablehlo/reference/Ops.cpp
  stablehlo/reference/Ops.h
  stablehlo/testdata/shift_right_logical_dtypes_lhs_int16_20_20__rhs_int16_20_20.mlir
  stablehlo/testdata/shift_right_logical_dtypes_lhs_int32_20_20__rhs_int32_20_20.mlir
  stablehlo/testdata/shift_right_logical_dtypes_lhs_int8_20_20__rhs_int8_20_20.mlir
  stablehlo/testdata/shift_right_logical_dtypes_lhs_uint16_20_20__rhs_uint16_20_20.mlir
  stablehlo/testdata/shift_right_logical_dtypes_lhs_uint32_20_20__rhs_uint32_20_20.mlir
  stablehlo/testdata/shift_right_logical_dtypes_lhs_uint8_20_20__rhs_uint8_20_20.mlir
  stablehlo/tests/interpret_shift_right_logical.mlir
Labels: Interpreter

#1437 enable a few interpreter tests
  stablehlo/testdata/asin_shape_complex64_20_20.mlir
  stablehlo/testdata/atan_shape_complex64_20_20.mlir
  stablehlo/testdata/bessel_i1e_shape_float32_20_20.mlir
  stablehlo/testdata/shift_left_broadcasting_lhs_int32_1_20__rhs_int32_20_20.mlir
  stablehlo/testdata/shift_left_broadcasting_lhs_int32_20_20__rhs_int32_1_20.mlir
Labels: Interpreter

#1431 Add interpreter for ShiftRightArithmeticOp
  docs/spec.md
  docs/status.md
  stablehlo/dialect/StablehloOps.td
  stablehlo/reference/Element.cpp
  stablehlo/reference/Element.h
  stablehlo/reference/Ops.cpp
  stablehlo/reference/Ops.h
  stablehlo/testdata/shift_right_arithmetic_dtypes_lhs_int16_20_20__rhs_int16_20_20.mlir
  stablehlo/testdata/shift_right_arithmetic_dtypes_lhs_int32_20_20__rhs_int32_20_20.mlir
  stablehlo/testdata/shift_right_arithmetic_dtypes_lhs_int8_20_20__rhs_int8_20_20.mlir
  stablehlo/testdata/shift_right_arithmetic_dtypes_lhs_uint16_20_20__rhs_uint16_20_20.mlir
  stablehlo/testdata/shift_right_arithmetic_dtypes_lhs_uint32_20_20__rhs_uint32_20_20.mlir
  stablehlo/testdata/shift_right_arithmetic_dtypes_lhs_uint8_20_20__rhs_uint8_20_20.mlir
  stablehlo/tests/interpret_shift_right_arithmetic.mlir
Labels: Interpreter

#1283 Add interpreter for SortOp
  docs/spec.md
  docs/status.md
  stablehlo/dialect/StablehloOps.td
  stablehlo/dialect/TypeInference.cpp
  stablehlo/reference/Ops.cpp
  stablehlo/reference/Ops.h
  stablehlo/tests/interpret_sort.mlir
  stablehlo/tests/ops_stablehlo.mlir
Labels: Spec, Interpreter, Migrate to MHLO

#1442 Bump patch to 0.10.1 after integrate
  stablehlo/dialect/Version.h
  stablehlo/integrations/python/tests/stablehlo.py
Labels: Build

#1441 Integrate LLVM at llvm/llvm-project@ba38640b9901
  WORKSPACE.bazel
  build_tools/llvm_version.txt
  stablehlo/dialect/AssemblyFormat.cpp
  stablehlo/dialect/ChloOps.cpp
  stablehlo/dialect/StablehloOps.cpp
  stablehlo/dialect/VhloOps.cpp
  stablehlo/reference/Ops.cpp
  stablehlo/transforms/VhloLegalizeToStablehlo.cpp
Labels: Integrations
