Repository openxla/stablehlo, pull requests merged in 2023-05, with the labels that each got.

#1447 Bump patch version 0.10.1 -> 0.10.2
  stablehlo/dialect/Version.h
Labels: Build

#1449 Integrate LLVM at llvm/llvm-project@dc275fd03254
  WORKSPACE.bazel
  build_tools/llvm_version.txt
Labels: Integrations

#1387 Extend indices_of_shape_operands to work for tuple types
  stablehlo/dialect/Base.cpp
  stablehlo/dialect/Base.h
  stablehlo/tests/stablehlo_canonicalize_dynamism.mlir
  stablehlo/tests/stablehlo_refine_shapes.mlir
  stablehlo/transforms/Passes.td
  stablehlo/transforms/StablehloRefineShapes.cpp
Labels: Type inference, Dynamism

#1388 Improve logging in refineReturnTypes
  stablehlo/transforms/StablehloRefineShapes.cpp
Labels: Type inference, Dynamism

#1450 Integrate LLVM at llvm/llvm-project@a91cb9ce39dc
  WORKSPACE.bazel
  build_tools/llvm_version.txt
  stablehlo/dialect/Serialization.cpp
Labels: Integrations

#1417 Add interpreter for CbrtOp
  docs/spec.md
  docs/status.md
  stablehlo/dialect/StablehloOps.td
  stablehlo/reference/Element.cpp
  stablehlo/reference/Element.h
  stablehlo/reference/Ops.cpp
  stablehlo/reference/Ops.h
  stablehlo/testdata/cbrt_shape_bfloat16_20_20.mlir
  stablehlo/testdata/cbrt_shape_float32_20_20.mlir
  stablehlo/tests/interpret_cbrt.mlir
Labels: Interpreter

#1451 Refactor matchInts to use APSInt instead of APInt
  stablehlo/dialect/Base.cpp
  stablehlo/dialect/Base.h
  stablehlo/transforms/StablehloCanonicalizeDynamism.cpp
  stablehlo/transforms/StablehloRefineShapes.cpp
Labels: Type inference, Dynamism

#1453 Drop support for index element types in Eval patterns
  stablehlo/transforms/StablehloRefineShapes.cpp
Labels: Type inference, Dynamism

#1457 Bump patch version 0.11.0 -> 0.11.1
  stablehlo/dialect/Version.h
Labels: Build

#1458 Integrate LLVM at llvm/llvm-project@8f966cedea59
  WORKSPACE.bazel
  build_tools/llvm_version.txt
Labels: Integrations

#1402 Add interpreter for Log1pOp.
  docs/spec.md
  docs/status.md
  stablehlo/dialect/StablehloOps.td
  stablehlo/reference/Element.cpp
  stablehlo/reference/Element.h
  stablehlo/reference/Ops.cpp
  stablehlo/reference/Ops.h
  stablehlo/testdata/atanh_shape_bfloat16_20_20.mlir
  stablehlo/testdata/atanh_shape_float32_20_20.mlir
  stablehlo/testdata/cumlogsumexp_axis_by_fun_shape_float32_8_9__associative_scan_reductions_axis_0_reverse_False.mlir
  stablehlo/testdata/cumlogsumexp_axis_by_fun_shape_float32_8_9__associative_scan_reductions_axis_1_reverse_False.mlir
  stablehlo/testdata/cumlogsumexp_axis_by_fun_shape_float32_8_9__axis_0_reverse_False.mlir
  stablehlo/testdata/cumlogsumexp_axis_by_fun_shape_float32_8_9__axis_1_reverse_False.mlir
  stablehlo/testdata/cumlogsumexp_dtype_by_fun_shape_float16_8_9__associative_scan_reductions_axis_0_reverse_False.mlir
  stablehlo/testdata/cumlogsumexp_dtype_by_fun_shape_float32_8_9__associative_scan_reductions_axis_0_reverse_False.mlir
  stablehlo/testdata/cumlogsumexp_dtype_by_fun_shape_float32_8_9__axis_0_reverse_False.mlir
  stablehlo/testdata/cumlogsumexp_reverse_shape_float32_8_9__associative_scan_reductions_axis_0_reverse_True.mlir
  stablehlo/testdata/cumlogsumexp_reverse_shape_float32_8_9__axis_0_reverse_True.mlir
  stablehlo/testdata/digamma_shape_float32_20_20.mlir
  stablehlo/testdata/erf_inv_shape_float32_20_20.mlir
  stablehlo/testdata/lgamma_shape_float32_20_20.mlir
  stablehlo/testdata/log1p_shape_bfloat16_20_20.mlir
  stablehlo/testdata/log1p_shape_complex64_20_20.mlir
  stablehlo/testdata/log1p_shape_float32_20_20.mlir
  stablehlo/tests/interpret_log_plus_one.mlir
Labels: Interpreter

#1411 Add interpreter for Expm1Op.
  docs/spec.md
  docs/status.md
  stablehlo/dialect/StablehloOps.td
  stablehlo/reference/Element.cpp
  stablehlo/reference/Element.h
  stablehlo/reference/Ops.cpp
  stablehlo/reference/Ops.h
  stablehlo/testdata/expm1_shape_bfloat16_20_20.mlir
  stablehlo/testdata/expm1_shape_complex64_20_20.mlir
  stablehlo/tests/interpret_exponential_minus_one.mlir
Labels: Interpreter

#1414 Add interpreter for ComplexOp.
  docs/spec.md
  docs/status.md
  stablehlo/dialect/StablehloOps.td
  stablehlo/dialect/TypeInference.cpp
  stablehlo/reference/Element.cpp
  stablehlo/reference/Element.h
  stablehlo/reference/Ops.cpp
  stablehlo/reference/Ops.h
  stablehlo/testdata/complex_broadcast_lhs_float32_3_1__rhs_float32_3_2.mlir
  stablehlo/testdata/complex_broadcast_lhs_float32_3_2__rhs_float32_3_1.mlir
  stablehlo/testdata/complex_dtypes_lhs_float32_3_4__rhs_float32_3_4.mlir
  stablehlo/tests/infer_stablehlo.mlir
  stablehlo/tests/interpret_complex.mlir
  stablehlo/tests/ops_stablehlo.mlir
Labels: Interpreter

#1418 Enable passing interpreter tests
  stablehlo/testdata/asinh_shape_bfloat16_20_20.mlir
  stablehlo/testdata/asinh_shape_float32_20_20.mlir
  stablehlo/testdata/atanh_shape_complex64_20_20.mlir
  stablehlo/testdata/conj_dtypes_operand_complex64_3_4__kwargs.mlir
  stablehlo/testdata/conj_dtypes_operand_float32_3_4__kwargs.mlir
  stablehlo/testdata/conj_kwargs_operand_float32_3_4__kwargs____input_dtype___class_numpy_float32.mlir
  stablehlo/testdata/shift_right_arithmetic_broadcasting_lhs_int32_1_20__rhs_int32_20_20.mlir
  stablehlo/testdata/shift_right_arithmetic_broadcasting_lhs_int32_20_20__rhs_int32_1_20.mlir
  stablehlo/testdata/shift_right_logical_broadcasting_lhs_int32_1_20__rhs_int32_20_20.mlir
  stablehlo/testdata/shift_right_logical_broadcasting_lhs_int32_20_20__rhs_int32_1_20.mlir
  stablehlo/testdata/sinh_shape_float32_20_20.mlir
Labels: Interpreter

#1462 Add note on version bumping to compatibility.md
  docs/compatibility.md
Labels: Process, Compatibility

#1465 Bump patch version 0.11.1 -> 0.11.2
  stablehlo/dialect/Version.h
Labels: Build

#1468 Integrate LLVM at llvm/llvm-project@14f0776550b5
  WORKSPACE.bazel
  build_tools/llvm_version.txt
  stablehlo/dialect/Base.h
  stablehlo/dialect/ChloOps.cpp
  stablehlo/dialect/StablehloOps.cpp
  stablehlo/tests/TestUtils.cpp
  stablehlo/tests/infer_chlo.mlir
  stablehlo/tests/infer_stablehlo.mlir
  stablehlo/tests/ops_chlo.mlir
  stablehlo/tests/ops_stablehlo.mlir
  stablehlo/tests/verify_reduce.mlir
  stablehlo/tests/verify_reduce_window.mlir
  stablehlo/tests/verify_scatter.mlir
  stablehlo/tests/verify_select_and_scatter.mlir
  stablehlo/transforms/StablehloRefineShapes.cpp
Labels: Integrations

#1470 Add missing checks/tests for supported f8 types
  stablehlo/dialect/Base.td
  stablehlo/reference/Tensor.cpp
  stablehlo/reference/Types.cpp
  stablehlo/tests/interpret_constant.mlir
  stablehlo/tests/ops_stablehlo.mlir
  stablehlo/tests/ops_stablehlo_roundtrip.mlir
Labels: Interpreter, Migrate from MHLO

#1471 Bump patch version after integrate 0.11.2 -> 0.11.3
  stablehlo/dialect/Version.h
Labels: Integrations

#1474 Clarify the checklist wording and provide examples
  docs/reference_checklist.md
Labels: Interpreter

#1446 Specification for quantized AddOp
  docs/spec.md
Labels: Spec

#1371 Add interpreter for BatchNormInferenceOp
  docs/spec.md
  docs/status.md
  stablehlo/dialect/StablehloOps.td
  stablehlo/dialect/TypeInference.cpp
  stablehlo/reference/Ops.cpp
  stablehlo/reference/Ops.h
  stablehlo/tests/infer_stablehlo.mlir
  stablehlo/tests/interpret_batch_norm_inference.mlir
  stablehlo/tests/ops_stablehlo.mlir
Labels: Interpreter, Migrate to MHLO

#1481 Add API to get minimum supported StableHLO version
  stablehlo/api/PortableApi.cpp
  stablehlo/api/PortableApi.h
  stablehlo/integrations/python/PortableApi.cpp
  stablehlo/integrations/python/tests/stablehlo.py
Labels: Integrations, Compatibility

#1482 Integrate LLVM at llvm/llvm-project@8faffa3cd3e1
  WORKSPACE.bazel
  build_tools/llvm_version.txt
Labels: Integrations

#1486 Bump patch version after integrate 0.11.3 -> 0.11.4
  stablehlo/dialect/Version.h
Labels: Integrations

#1485 Fix issues identified during integrate
  BUILD.bazel
  stablehlo/dialect/TypeInference.cpp
  stablehlo/dialect/TypeInference.h
  stablehlo/integrations/python/tests/stablehlo.py
  stablehlo/reference/CMakeLists.txt
  stablehlo/reference/Ops.cpp
  stablehlo/reference/Tensor.cpp
Labels: Integrations

#1483 Update serialization cookbook to include Python APIs
  docs/bytecode.md
  docs/compatibility.md
  stablehlo/api/PortableApi.h
Labels: Integrations, Compatibility

#1444 Add interpreter for CholeskyOp
  docs/spec.md
  docs/status.md
  stablehlo/dialect/StablehloOps.td
  stablehlo/dialect/TypeInference.cpp
  stablehlo/reference/Ops.cpp
  stablehlo/reference/Ops.h
  stablehlo/reference/Sizes.h
  stablehlo/tests/interpret_cholesky.mlir
  stablehlo/tests/ops_stablehlo.mlir
Labels: Interpreter, Migrate to MHLO

#1487 Fix CholeskyOp breakage
  stablehlo/reference/Ops.cpp
Labels: Interpreter

#1493 Slightly reword compatibility.md
  docs/compatibility.md
Labels: Compatibility

#1495 Integrate LLVM at llvm/llvm-project@33da608ecc0f
  WORKSPACE.bazel
  build_tools/llvm_version.txt
Labels: Integrations

#1499 Integrate LLVM at llvm/llvm-project@e96123dfeabc
  WORKSPACE.bazel
  build_tools/llvm_version.txt
  stablehlo/tests/infer_stablehlo.mlir
  stablehlo/tests/legalize_stablehlo_to_vhlo_invalid.mlir
  stablehlo/tests/ops_sparse.mlir
  stablehlo/tests/ops_stablehlo.mlir
  stablehlo/tests/print_stablehlo.mlir
Labels: Integrations

#1501 Incorporate tosa/ tests into our test infrastructure
  CMakeLists.txt
  build_tools/github_actions/ci_build_cmake.sh
  build_tools/github_actions/ci_build_cmake_code_coverage.sh
  stablehlo/conversions/tosa/tests/CMakeLists.txt
  stablehlo/conversions/tosa/tests/binary.mlir
  stablehlo/conversions/tosa/tests/lit.cfg.py
  stablehlo/conversions/tosa/tests/nullary.mlir
  stablehlo/conversions/tosa/tests/ternary.mlir
  stablehlo/conversions/tosa/tests/unary.mlir
  stablehlo/integrations/python/tests/CMakeLists.txt
  stablehlo/testdata/CMakeLists.txt
  stablehlo/tests/CMakeLists.txt
Labels: Integrations

#1502 Integrate tosa/ into the Bazel build
  BUILD.bazel
  stablehlo/conversions/tosa/CMakeLists.txt
  stablehlo/conversions/tosa/tests/BUILD.bazel
  stablehlo/conversions/tosa/transforms/BUILD.bazel
  stablehlo/conversions/tosa/transforms/CMakeLists.txt
Labels: Integrations

#1503 Rename some files in tosa/ to follow filename conventions
  BUILD.bazel
  stablehlo/conversions/tosa/transforms/CMakeLists.txt
  stablehlo/conversions/tosa/transforms/LegalizeStablehlo.cpp
  stablehlo/conversions/tosa/transforms/LegalizeStablehlo.pdll
  stablehlo/conversions/tosa/transforms/Passes.h
  stablehlo/conversions/tosa/transforms/Passes.td
  stablehlo/conversions/tosa/transforms/PrepareStablehlo.cpp
  stablehlo/tools/StablehloOptMain.cpp
Labels: Integrations

#1504 Rename tosa/ passes to follow pass name conventions
  BUILD.bazel
  stablehlo/conversions/tosa/tests/binary.mlir
  stablehlo/conversions/tosa/tests/nullary.mlir
  stablehlo/conversions/tosa/tests/ternary.mlir
  stablehlo/conversions/tosa/tests/unary.mlir
  stablehlo/conversions/tosa/transforms/CMakeLists.txt
  stablehlo/conversions/tosa/transforms/Passes.h
  stablehlo/conversions/tosa/transforms/Passes.td
  stablehlo/conversions/tosa/transforms/StablehloLegalizeToTosa.cpp
  stablehlo/conversions/tosa/transforms/StablehloLegalizeToTosa.pdll
  stablehlo/conversions/tosa/transforms/StablehloPrepareForTosa.cpp
  stablehlo/tools/StablehloOptMain.cpp
Labels: Integrations

#1506 Belatedly bump patch version after integrate 0.11.4 -> 0.11.5
  stablehlo/dialect/Version.h
Labels: Integrations

#1507 Bump patch version after integrate 0.11.5 -> 0.11.6
  stablehlo/dialect/Version.h
Labels: Integrations

#1505 Fix issues identified during integrate
  BUILD.bazel
Labels: Integrations, Migrate from MHLO

#1511 Use bytecodeVersion = 1 when serializing MLIR bytecode
  stablehlo/api/PortableApi.cpp
  stablehlo/dialect/Serialization.cpp
Labels: Integrations

#1510 Integrate LLVM at llvm/llvm-project@f7e2678bb706
  WORKSPACE.bazel
  build_tools/llvm_version.txt
Labels: Integrations

#1512 Actually use the BytecodeWriterConfig in writeBytecodeToFile
  stablehlo/api/PortableApi.cpp
  stablehlo/dialect/Serialization.cpp
Labels: Compatibility

#1516 Add producer to StableHLO portable artifacts.
  stablehlo/api/PortableApi.cpp
  stablehlo/api/PortableApi.h
  stablehlo/dialect/Serialization.cpp
  stablehlo/tools/StablehloTranslateMain.cpp
  stablehlo/transforms/VhloToVersion.cpp
Labels: Compatibility

#1519 Add option to stablehlo-translate to generate bytecode without debug info
  stablehlo/tools/StablehloTranslateMain.cpp
Labels: Compatibility

#1520 Add API to determine bytecode format version of StableHLO release
  BUILD.bazel
  stablehlo/dialect/CMakeLists.txt
  stablehlo/dialect/Serialization.cpp
  stablehlo/dialect/Version.cpp
  stablehlo/dialect/Version.h
Labels: Compatibility

#1513 Bump patch version after integrate 0.11.6 -> 0.11.7
  stablehlo/dialect/Version.h
Labels: Integrations

#1515 Update the link to serialization APIs in compatibility.md
  docs/compatibility.md
Labels: Compatibility

#1524 Update bytecode artifacts to remove debuginfo and include StableHLO producer string
  stablehlo/tests/stablehlo_legalize_to_vhlo.0_10_0.mlir
  stablehlo/tests/stablehlo_legalize_to_vhlo.0_10_0.mlir.bc
  stablehlo/tests/stablehlo_legalize_to_vhlo.0_11_0.mlir
  stablehlo/tests/stablehlo_legalize_to_vhlo.0_11_0.mlir.bc
  stablehlo/tests/stablehlo_legalize_to_vhlo.0_9_0.mlir
  stablehlo/tests/stablehlo_legalize_to_vhlo.0_9_0.mlir.bc
Labels: Compatibility

#1522 Update bytecode docs to mention MLIR Bytecode Format and StableHLO releases
  docs/vhlo.md
Labels: Compatibility

#1525 Add stop-gap static forward compatibility tests
  stablehlo/tests/stablehlo_legalize_to_vhlo.0_10_0.mlir
  stablehlo/tests/stablehlo_legalize_to_vhlo.0_11_0.mlir
  stablehlo/tests/stablehlo_legalize_to_vhlo.0_9_0.mlir
Labels: Compatibility

#1526 Integrate LLVM at llvm/llvm-project@27eadeee6b45
  WORKSPACE.bazel
  build_tools/llvm_version.txt
Labels: Integrations

#1529 Fix build error on macOS
  stablehlo/reference/Element.cpp
Labels: Build

#1527 Fix issues identified during integrate
  BUILD.bazel
  stablehlo/tools/CMakeLists.txt
Labels: Integrations, Migrate from MHLO

#1521 Update CustomCallOp status to `yes` and update ODS
  docs/spec.md
  docs/status.md
  stablehlo/dialect/StablehloOps.td
Labels: Interpreter

#1467 Simplify verification of ReduceOp and ReduceWindowOp
  stablehlo/dialect/TypeInference.cpp
Labels: Verification

#1532 Simplify evalConvertOp
  stablehlo/reference/Element.cpp
  stablehlo/reference/Element.h
  stablehlo/reference/Ops.cpp
Labels: Interpreter

#1393 Add interpreter for BatchNormTrainingOp
  BUILD.bazel
  docs/spec.md
  docs/status.md
  stablehlo/dialect/StablehloOps.td
  stablehlo/dialect/TypeInference.cpp
  stablehlo/reference/CMakeLists.txt
  stablehlo/reference/Ops.cpp
  stablehlo/reference/Ops.h
  stablehlo/reference/Tensor.h
  stablehlo/tests/infer_stablehlo.mlir
  stablehlo/tests/interpret_batch_norm_training.mlir
  stablehlo/tests/ops_stablehlo.mlir
Labels: Interpreter, Migrate to MHLO

#1540 Integrate LLVM at llvm/llvm-project@e837f4b7
  WORKSPACE.bazel
  build_tools/llvm_version.txt
Labels: Integrations

#1537 Improve documentation for getMinimumVersion
  stablehlo/api/PortableApi.h
Labels: Compatibility

#1536 Move chlo::TopKOp type inference into TypeInference.h
  BUILD.bazel
  stablehlo/dialect/CMakeLists.txt
  stablehlo/dialect/ChloOps.cpp
  stablehlo/dialect/TypeInference.cpp
  stablehlo/dialect/TypeInference.h
  stablehlo/tests/ops_chlo.mlir
Labels: Type inference, Dynamism

#1394 Add interpreter for BatchNormGradOp
  docs/spec.md
  docs/status.md
  stablehlo/dialect/StablehloOps.td
  stablehlo/dialect/TypeInference.cpp
  stablehlo/reference/Ops.cpp
  stablehlo/reference/Ops.h
  stablehlo/tests/infer_stablehlo.mlir
  stablehlo/tests/interpret_batch_norm_grad.mlir
  stablehlo/tests/ops_stablehlo.mlir
Labels: Interpreter, Migrate to MHLO

#1543 Compress the code a little bit
  stablehlo/reference/Ops.cpp
Labels: Interpreter

#1548 Bump patch version after integrate 0.12.0 -> 0.12.1
  stablehlo/dialect/Version.h
Labels: Integrations

#1555 Use func.func and func.return in the spec
  docs/spec.md
Labels: Spec

#1553 Simplify evalWhileOp
  stablehlo/reference/Ops.cpp
Labels: Interpreter

#1558 Integrate LLVM at llvm/llvm-project@f81f32adc9a8
  WORKSPACE.bazel
  build_tools/llvm_version.txt
Labels: Integrations

#1550 Remove an implementation-defined test for GatherOp
  stablehlo/tests/interpret_gather.mlir
Labels: Interpreter

#1560 Update vhlo.md to include specific RUN lines for testing
  docs/vhlo.md
Labels: Compatibility
