Repository openxla/stablehlo, pull requests merged in 2023-02, with the labels that each got.

#1014 Clean up GitHub workflows
  .github/actions/setup-build/action.yml
  .github/workflows/buildAndTestCMake.yml
  .github/workflows/buildBazel.yml
  .github/workflows/lint.yml
  .github/workflows/markdown_lint.yml
Labels: Process

#1024 Integrate LLVM at llvm/llvm-project@f58de2125caf
  WORKSPACE.bazel
  build_tools/llvm_version.txt
Labels: Integrations

#1032 Update lint_llvm_commit.sh to also verify SHA256
  WORKSPACE.bazel
  build_tools/github_actions/lint_llvm_commit.sh
Labels: Build

#961 Handle bounds in the Select shape function
  stablehlo/dialect/Base.cpp
  stablehlo/tests/infer_stablehlo.mlir
Labels: Type inference, Dynamism, Migrate to MHLO

#1035 Also rename legalize_stablehlo_to_vhlo.mlir
  stablehlo/tests/stablehlo_legalize_to_vhlo.mlir
Labels: Compatibility

#1034 Migrate away from using MLIR Attributes in `evalTransposeOp`
  stablehlo/reference/Interpreter.cpp
  stablehlo/reference/Ops.cpp
  stablehlo/reference/Ops.h
Labels: Interpreter

#1039 Standardize formatting in Ops.cpp and Interpreter.cpp
  stablehlo/reference/Interpreter.cpp
  stablehlo/reference/Ops.cpp
Labels: Interpreter

#1043 Update CI to use faster runners
  .github/workflows/buildAndTestCMake.yml
  .github/workflows/buildBazel.yml
  .github/workflows/lint.yml
  .github/workflows/markdown_lint.yml
Labels: Build

#1044 Update llvm lint tool with flag to disable SHA256 check
  build_tools/github_actions/lint_llvm_commit.sh
Labels: Build

#1041 Enable specializing dynamically-shaped StableHLO programs to static shapes
  BUILD.bazel
  stablehlo/dialect/StablehloOps.cpp
  stablehlo/dialect/TypeInference.cpp
  stablehlo/dialect/TypeInference.h
  stablehlo/tests/stablehlo_refine_shapes.mlir
  stablehlo/transforms/CMakeLists.txt
  stablehlo/transforms/Passes.h
  stablehlo/transforms/Passes.td
  stablehlo/transforms/StablehloRefineShapes.cpp
Labels: Type inference, Dynamism

#1046 Handle unranked input types in `inferMostSpecificTypeComponents`
  stablehlo/dialect/Base.cpp
Labels: Type inference

#849 Fork Attributes and Types for VHLO
  BUILD.bazel
  stablehlo/dialect/CMakeLists.txt
  stablehlo/dialect/Register.cpp
  stablehlo/dialect/Version.h
  stablehlo/dialect/VhloAttrs.td
  stablehlo/dialect/VhloBase.td
  stablehlo/dialect/VhloBytecode.cpp
  stablehlo/dialect/VhloEnums.td
  stablehlo/dialect/VhloOps.cpp
  stablehlo/dialect/VhloOps.h
  stablehlo/dialect/VhloOps.td
  stablehlo/dialect/VhloTypes.cpp
  stablehlo/dialect/VhloTypes.h
  stablehlo/dialect/VhloTypes.td
  stablehlo/tests/legalize_stablehlo_to_vhlo_invalid.mlir
  stablehlo/tests/stablehlo_legalize_to_vhlo.mlir
  stablehlo/tests/vhlo_to_version_upgrade.mlir
  stablehlo/transforms/Passes.h
  stablehlo/transforms/Passes.td
  stablehlo/transforms/StablehloLegalizeToVhlo.cpp
  stablehlo/transforms/TypeConversion.cpp
  stablehlo/transforms/TypeConversion.h
  stablehlo/transforms/VhloLegalizeToStablehlo.cpp
  stablehlo/transforms/VhloToVersion.cpp
Labels: Compatibility

#1006 Add interpreter for ReverseOp
  docs/spec.md
  docs/status.md
  stablehlo/dialect/StablehloOps.td
  stablehlo/dialect/TypeInference.cpp
  stablehlo/reference/Interpreter.cpp
  stablehlo/reference/Ops.cpp
  stablehlo/reference/Ops.h
  stablehlo/tests/interpret_reverse.mlir
  stablehlo/tests/ops_stablehlo.mlir
Labels: Interpreter, Migrate to MHLO

#1057 Add .bazelignore
  .bazelignore
Labels: Build

#1054 Change return type for shape function of bounds
  stablehlo/dialect/Base.cpp
  stablehlo/dialect/Base.h
Labels: Type inference, Dynamism, Migrate to MHLO

#1050 Update interpreter testing guideline with coverage criterion
  docs/reference.md
Labels: Interpreter

#1040 Fix the notations for dynamic_update_slice and dynamic_slice
  docs/spec.md
Labels: Spec

#1052 Use public runners on forked repos
  .github/workflows/buildAndTestCMake.yml
  .github/workflows/buildBazel.yml
  .github/workflows/lint.yml
  .github/workflows/markdown_lint.yml
Labels: Build

#1059 Addressed a few clang-tidy suggestions
  stablehlo/transforms/StablehloRefineShapes.cpp
Labels: Process

#1053 Move VhloTypeDefs.cpp.inc into VhloTypes.cpp
  BUILD.bazel
  stablehlo/dialect/CMakeLists.txt
  stablehlo/dialect/VhloOps.cpp
  stablehlo/dialect/VhloOps.h
  stablehlo/dialect/VhloTypes.cpp
  stablehlo/dialect/VhloTypes.h
Labels: Compatibility

#1064 Move and merge inferRngOp
  stablehlo/dialect/StablehloOps.cpp
  stablehlo/dialect/StablehloOps.td
  stablehlo/dialect/TypeInference.cpp
  stablehlo/dialect/TypeInference.h
Labels: Verification, Type inference

#1071 Revert #958: Verify compare_type for compare_op
  stablehlo/dialect/StablehloOps.cpp
  stablehlo/dialect/TypeInference.cpp
  stablehlo/dialect/TypeInference.h
  stablehlo/tests/ops_stablehlo.mlir
  stablehlo/tests/print_stablehlo.mlir
  stablehlo/tests/stablehlo_legalize_to_vhlo.mlir
Labels: Process

#1073 Fix signature of `extraClassDefinition` for `UniformQuantizedV1Type`
  stablehlo/dialect/VhloTypes.td
Labels: Compatibility

#925 Add VHLO support for FP8
  stablehlo/dialect/VhloBytecode.cpp
  stablehlo/dialect/VhloDialect.td
  stablehlo/dialect/VhloTypes.cpp
  stablehlo/dialect/VhloTypes.td
  stablehlo/tests/stablehlo_legalize_to_vhlo.mlir
  stablehlo/tests/vhlo_to_version_attrtype_invalid.mlir
  stablehlo/tests/vhlo_to_version_downgrade_invalid.mlir
Labels: Compatibility

#1074 Add copyright tag to bazel configuration files
  .bazelignore
  .bazelrc
  .bazelversion
Labels: Process

#1075 Delete .bazelversion
  .bazelversion
Labels: Build

#1076 Link frontend contract tickets in the spec
  docs/spec.md
Labels: Spec

#996 Add interpreter for SliceOp
  docs/spec.md
  docs/status.md
  stablehlo/dialect/StablehloOps.td
  stablehlo/dialect/TypeInference.cpp
  stablehlo/reference/Interpreter.cpp
  stablehlo/reference/Ops.cpp
  stablehlo/reference/Ops.h
  stablehlo/tests/interpret_slice.mlir
  stablehlo/tests/ops_stablehlo.mlir
Labels: Interpreter, Migrate to MHLO

#1081 Add Input constraint labels
  docs/spec.md
Labels: Spec

#1084 Integrate LLVM at llvm/llvm-project@27aeb58ce4d1
  WORKSPACE.bazel
  build_tools/llvm_version.txt
Labels: Integrations

#899 Fork FuncOp and CallOp to VHLO
  BUILD.bazel
  stablehlo/dialect/Register.cpp
  stablehlo/dialect/VhloAttrs.td
  stablehlo/dialect/VhloBytecode.cpp
  stablehlo/dialect/VhloOps.cpp
  stablehlo/dialect/VhloOps.h
  stablehlo/dialect/VhloOps.td
  stablehlo/dialect/VhloTypes.cpp
  stablehlo/dialect/VhloTypes.td
  stablehlo/tests/stablehlo_legalize_to_vhlo.mlir
  stablehlo/tests/vhlo_to_version_attrtype_invalid.mlir
  stablehlo/tests/vhlo_to_version_downgrade_invalid.mlir
  stablehlo/tests/vhlo_to_version_upgrade.mlir
  stablehlo/transforms/CMakeLists.txt
  stablehlo/transforms/MapStablehloToVhlo.h
  stablehlo/transforms/Passes.td
  stablehlo/transforms/StablehloLegalizeToVhlo.cpp
  stablehlo/transforms/TypeConversion.cpp
  stablehlo/transforms/TypeConversion.h
  stablehlo/transforms/VhloLegalizeToStablehlo.cpp
  stablehlo/transforms/VhloToVersion.cpp
Labels: Compatibility

#1088 Don't load Tensor dialect in StableHLO dialect constructor
  stablehlo/dialect/StablehloOps.cpp
Labels: Integrations

#1042 Standardize the usage of braces in control flow statements
  stablehlo/dialect/AssemblyFormat.cpp
  stablehlo/dialect/Base.cpp
  stablehlo/dialect/BroadcastUtils.cpp
  stablehlo/dialect/ChloOps.cpp
  stablehlo/dialect/StablehloBytecode.cpp
  stablehlo/dialect/StablehloOps.cpp
  stablehlo/dialect/TypeInference.cpp
  stablehlo/dialect/Version.cpp
  stablehlo/dialect/VhloBytecode.cpp
  stablehlo/dialect/VhloOps.cpp
  stablehlo/reference/Interpreter.cpp
  stablehlo/reference/Tensor.cpp
  stablehlo/tests/TestUtils.cpp
  stablehlo/transforms/VhloToVersion.cpp
Labels: Process

#1094 Integrate LLVM at llvm/llvm-project@f100ec2517e9
  WORKSPACE.bazel
  build_tools/llvm_version.txt
Labels: Integrations

#1095 Use const reference for loop variable to avoid copy
  stablehlo/dialect/StablehloOps.cpp
Labels: Build

#1146 Update the ODS with input constraints from the spec
  docs/reference_checklist.md
Labels: Spec

#1147 Allow -f fix for lint_markdown.sh
  build_tools/github_actions/lint_markdown.sh
Labels: Process

#1148 Sort BUILD.bazel file
  BUILD.bazel
Labels: Build

#1158 Link recently added frontend contract tickets in the spec
  docs/spec.md
Labels: Spec

#1093 Implement Region evaluation
  BUILD.bazel
  stablehlo/reference/CMakeLists.txt
  stablehlo/reference/Interpreter.cpp
  stablehlo/reference/Interpreter.h
  stablehlo/reference/Ops.cpp
  stablehlo/reference/Ops.h
  stablehlo/reference/Scope.cpp
  stablehlo/reference/Scope.h
  stablehlo/tests/interpret_while.mlir
  stablehlo/tools/CMakeLists.txt
  stablehlo/tools/StablehloInterpreterMain.cpp
Labels: Interpreter

#1142 Add VHLO Python/C Bindings
  BUILD.bazel
  stablehlo/dialect/CMakeLists.txt
  stablehlo/integrations/c/CMakeLists.txt
  stablehlo/integrations/c/VhloDialect.cpp
  stablehlo/integrations/c/VhloDialect.h
  stablehlo/integrations/python/CMakeLists.txt
  stablehlo/integrations/python/VhloModule.cpp
  stablehlo/integrations/python/mlir/dialects/VhloOps.td
  stablehlo/integrations/python/mlir/dialects/vhlo.py
  stablehlo/integrations/python/tests/CMakeLists.txt
  stablehlo/integrations/python/tests/vhlo.py
Labels: Integrations

#1096 Remove the undefined AllReduceOp build()
  stablehlo/dialect/StablehloOps.td
Labels: Migrate from MHLO

#1159 Update ODS documentation for yet unspecced ops
  stablehlo/dialect/StablehloOps.td
Labels: Integrations

#1051 Add interpreter for BroadcastInDimOp
  docs/spec.md
  docs/status.md
  stablehlo/dialect/StablehloOps.td
  stablehlo/dialect/TypeInference.cpp
  stablehlo/reference/Ops.cpp
  stablehlo/reference/Ops.h
  stablehlo/tests/interpret_broadcast_in_dim.mlir
  stablehlo/tests/ops_stablehlo.mlir
Labels: Interpreter

#1005 Add interpreter for PadOp
  docs/spec.md
  docs/status.md
  stablehlo/dialect/StablehloOps.td
  stablehlo/dialect/TypeInference.cpp
  stablehlo/reference/Ops.cpp
  stablehlo/reference/Ops.h
  stablehlo/tests/interpret_pad.mlir
  stablehlo/tests/ops_stablehlo.mlir
Labels: Interpreter, Migrate to MHLO

#998 Add interpreter for DynamicUpdateSliceOp
  docs/spec.md
  docs/status.md
  stablehlo/dialect/StablehloOps.td
  stablehlo/dialect/TypeInference.cpp
  stablehlo/reference/Ops.cpp
  stablehlo/reference/Ops.h
  stablehlo/tests/interpret_dynamic_update_slice.mlir
  stablehlo/tests/ops_stablehlo.mlir
Labels: Interpreter, Migrate to MHLO

#1162 Integrate LLVM at llvm/llvm-project@d3b0fba6084d
  WORKSPACE.bazel
  build_tools/llvm_version.txt
Labels: Integrations

#1166 Remove default values for VHLO versions in Enums / Attrs / Types / Ops
  stablehlo/dialect/VhloAttrs.td
  stablehlo/dialect/VhloEnums.td
  stablehlo/dialect/VhloOps.td
  stablehlo/dialect/VhloTypes.td
Labels: Compatibility

#1167 Add support for DynamicConvOp to --stablehlo-refine-shapes
  stablehlo/tests/stablehlo_refine_shapes.mlir
  stablehlo/transforms/StablehloRefineShapes.cpp
Labels: Type inference, Dynamism

#1168 Organize ongoing work items in workstreams and milestones
  README.md
  docs/roadmap.md
Labels: Process

#1169 Prototype a mechanism to customize shape refinement for CustomCallOp
  stablehlo/tests/stablehlo_refine_shapes.mlir
  stablehlo/transforms/StablehloRefineShapes.cpp
Labels: Type inference, Dynamism

#1172 Print escaped string to preserve binary data
  stablehlo/dialect/VhloAttrs.td
  stablehlo/dialect/VhloOps.cpp
  stablehlo/tests/stablehlo_legalize_to_vhlo.mlir
Labels: Compatibility

#1080 Add interpreter for DynamicSliceOp
  docs/spec.md
  docs/status.md
  stablehlo/dialect/StablehloOps.td
  stablehlo/dialect/TypeInference.cpp
  stablehlo/reference/Ops.cpp
  stablehlo/reference/Ops.h
  stablehlo/tests/interpret_dynamic_slice.mlir
  stablehlo/tests/ops_stablehlo.mlir
Labels: Spec, Interpreter, Migrate to MHLO

#1175 Integrate LLVM at llvm/llvm-project@4f15267d3dd7
  WORKSPACE.bazel
  build_tools/llvm_version.txt
Labels: Integrations

#1177 Minor typo fix (match parameter names in function signature and function definition)
  stablehlo/reference/Ops.h
Labels: Process

#1029 Move and merge verifier of Set/GetDimensionSizeOp
  stablehlo/dialect/StablehloOps.cpp
  stablehlo/dialect/StablehloOps.td
  stablehlo/dialect/TypeInference.cpp
  stablehlo/dialect/TypeInference.h
Labels: Verification, Type inference

#1087 Add interpreter for SelectOp
  docs/spec.md
  docs/status.md
  stablehlo/dialect/StablehloOps.td
  stablehlo/dialect/TypeInference.cpp
  stablehlo/reference/Ops.cpp
  stablehlo/reference/Ops.h
  stablehlo/tests/interpret_select.mlir
  stablehlo/tests/ops_stablehlo.mlir
Labels: Interpreter

#999 Add interpreter for ClampOp
  docs/spec.md
  docs/status.md
  stablehlo/dialect/StablehloOps.td
  stablehlo/dialect/TypeInference.cpp
  stablehlo/reference/Ops.cpp
  stablehlo/reference/Ops.h
  stablehlo/tests/interpret_clamp.mlir
  stablehlo/tests/ops_stablehlo.mlir
Labels: Interpreter

#1185 Replace all uses of llvm_unreachable with llvm::report_fatal_error
  stablehlo/dialect/Base.cpp
  stablehlo/dialect/StablehloOps.cpp
  stablehlo/dialect/Version.cpp
  stablehlo/dialect/VhloAttrs.td
  stablehlo/dialect/VhloBytecode.cpp
  stablehlo/dialect/VhloOps.td
  stablehlo/dialect/VhloTypes.td
  stablehlo/integrations/c/ChloAttributes.cpp
  stablehlo/integrations/c/StablehloAttributes.cpp
Labels: Process

#1079 Add interpreter for ExpOp
  docs/spec.md
  docs/status.md
  stablehlo/dialect/StablehloOps.td
  stablehlo/reference/Element.cpp
  stablehlo/reference/Element.h
  stablehlo/reference/Ops.cpp
  stablehlo/reference/Ops.h
  stablehlo/tests/interpret_exponential.mlir
Labels: Interpreter

#1197 Integrate LLVM at llvm/llvm-project@8b3091b4b485
  WORKSPACE.bazel
  build_tools/llvm_version.txt
Labels: Integrations

#1068 Add interpreter for SqrtOp.
  docs/spec.md
  docs/status.md
  stablehlo/dialect/StablehloOps.td
  stablehlo/reference/Element.cpp
  stablehlo/reference/Element.h
  stablehlo/reference/Ops.cpp
  stablehlo/reference/Ops.h
  stablehlo/tests/interpret_sqrt.mlir
Labels: Interpreter

#1086 Add interpreter for LogOp
  docs/spec.md
  docs/status.md
  stablehlo/dialect/StablehloOps.td
  stablehlo/reference/Element.cpp
  stablehlo/reference/Element.h
  stablehlo/reference/Ops.cpp
  stablehlo/reference/Ops.h
  stablehlo/tests/interpret_log.mlir
Labels: Interpreter

#1184 Audit VhloOps.td
  docs/spec.md
  stablehlo/dialect/StablehloOps.td
  stablehlo/dialect/VhloDialect.td
  stablehlo/dialect/VhloOps.td
  stablehlo/integrations/python/tests/vhlo.py
  stablehlo/tests/vhlo_to_version_attrtype_invalid.mlir
  stablehlo/tests/vhlo_to_version_upgrade.mlir
Labels: Compatibility

#1188 Audit VhloEnums.td
  stablehlo/dialect/VhloEnums.td
Labels: Compatibility

#1190 Rename VHLO_DenseIntOrFPElementsAttr to VHLO_TensorAttr
  stablehlo/dialect/VhloAttrs.td
  stablehlo/dialect/VhloBytecode.cpp
  stablehlo/dialect/VhloOps.cpp
  stablehlo/tests/stablehlo_legalize_to_vhlo.mlir
  stablehlo/tests/vhlo_to_version_upgrade.mlir
  stablehlo/transforms/StablehloLegalizeToVhlo.cpp
  stablehlo/transforms/VhloLegalizeToStablehlo.cpp
  stablehlo/transforms/VhloToVersion.cpp
Labels: Compatibility

#1189 Audit VhloTypes.td
  stablehlo/dialect/VhloBytecode.cpp
  stablehlo/dialect/VhloOps.cpp
  stablehlo/dialect/VhloTypes.cpp
  stablehlo/dialect/VhloTypes.td
  stablehlo/tests/stablehlo_legalize_to_vhlo.mlir
  stablehlo/tests/vhlo_to_version_upgrade.mlir
  stablehlo/transforms/VhloToVersion.cpp
Labels: Compatibility

#1191 Minor refactoring for FuncOp-related attributes
  stablehlo/dialect/VhloAttrs.td
Labels: Compatibility

#1193 Replace VHLO_UnitAttr with VHLO_BooleanAttr
  stablehlo/dialect/VhloAttrs.td
  stablehlo/dialect/VhloBytecode.cpp
  stablehlo/tests/stablehlo_legalize_to_vhlo.mlir
  stablehlo/transforms/StablehloLegalizeToVhlo.cpp
  stablehlo/transforms/VhloLegalizeToStablehlo.cpp
Labels: Compatibility

#1173 Introduce Index class
  BUILD.bazel
  stablehlo/reference/Axes.cpp
  stablehlo/reference/Axes.h
  stablehlo/reference/CMakeLists.txt
  stablehlo/reference/Index.cpp
  stablehlo/reference/Index.h
  stablehlo/reference/Ops.cpp
  stablehlo/reference/Ops.h
  stablehlo/reference/Sizes.cpp
  stablehlo/reference/Sizes.h
  stablehlo/reference/Tensor.cpp
  stablehlo/reference/Tensor.h
Labels: Interpreter

#1194 Inline VHLO_ConvDimensionNumbersAttr and friends
  stablehlo/dialect/VhloAttrs.td
  stablehlo/dialect/VhloBytecode.cpp
  stablehlo/dialect/VhloOps.td
  stablehlo/tests/stablehlo_legalize_to_vhlo.mlir
  stablehlo/tests/vhlo_to_version_downgrade_invalid.mlir
  stablehlo/tests/vhlo_to_version_upgrade.mlir
  stablehlo/transforms/StablehloLegalizeToVhlo.cpp
  stablehlo/transforms/VhloLegalizeToStablehlo.cpp
  stablehlo/transforms/VhloToVersion.cpp
Labels: Compatibility

#1195 Audit VhloAttrs.td
  stablehlo/dialect/VhloAttrs.td
  stablehlo/dialect/VhloBytecode.cpp
  stablehlo/dialect/VhloOps.cpp
  stablehlo/transforms/StablehloLegalizeToVhlo.cpp
  stablehlo/transforms/VhloLegalizeToStablehlo.cpp
Labels: Compatibility

#1179 Add support for folding SignOp in --stablehlo-refine-shapes
  stablehlo/tests/stablehlo_refine_shapes.mlir
  stablehlo/transforms/StablehloRefineShapes.cpp
Labels: Type inference, Dynamism

#1180 Add support for collective ops in --stablehlo-refine-shapes
  stablehlo/tests/stablehlo_refine_shapes.mlir
  stablehlo/transforms/StablehloRefineShapes.cpp
Labels: Type inference, Dynamism

#1198 Stop using BooleanV1Type in IntegerV1Attr
  stablehlo/dialect/VhloBytecode.cpp
Labels: Compatibility

#1200 Integrate LLVM at llvm/llvm-project@88bd2601c013
  WORKSPACE.bazel
  build_tools/llvm_version.txt
Labels: Integrations

#1085 Add interpreter for RsqrtOp.
  docs/spec.md
  docs/status.md
  stablehlo/dialect/StablehloOps.td
  stablehlo/reference/Element.cpp
  stablehlo/reference/Element.h
  stablehlo/reference/Ops.cpp
  stablehlo/reference/Ops.h
  stablehlo/tests/interpret_rsqrt.mlir
Labels: Interpreter

#1008 Add interpreter for DivideOp
  docs/spec.md
  docs/status.md
  stablehlo/dialect/StablehloOps.td
  stablehlo/reference/Element.cpp
  stablehlo/reference/Element.h
  stablehlo/reference/Ops.cpp
  stablehlo/reference/Ops.h
  stablehlo/tests/interpret_divide.mlir
Labels: Interpreter

#1205 Reformat BUILD.bazel
  BUILD.bazel
Labels: Build

#1026 Replace `FileCheck` based testing with Check dialect
  BUILD.bazel
  docs/reference.md
  stablehlo/reference/Element.cpp
  stablehlo/reference/Element.h
  stablehlo/reference/Ops.cpp
  stablehlo/reference/Ops.h
  stablehlo/tests/CMakeLists.txt
  stablehlo/tests/CheckOps.cpp
  stablehlo/tests/CheckOps.h
  stablehlo/tests/CheckOps.td
  stablehlo/tests/interpret_abs.mlir
  stablehlo/tests/interpret_add.mlir
  stablehlo/tests/interpret_and.mlir
  stablehlo/tests/interpret_broadcast_in_dim.mlir
  stablehlo/tests/interpret_ceil.mlir
  stablehlo/tests/interpret_clamp.mlir
  stablehlo/tests/interpret_constant.mlir
  stablehlo/tests/interpret_cosine.mlir
  stablehlo/tests/interpret_divide.mlir
  stablehlo/tests/interpret_dynamic_slice.mlir
  stablehlo/tests/interpret_dynamic_update_slice.mlir
  stablehlo/tests/interpret_exponential.mlir
  stablehlo/tests/interpret_floor.mlir
  stablehlo/tests/interpret_if.mlir
  stablehlo/tests/interpret_iota.mlir
  stablehlo/tests/interpret_log.mlir
  stablehlo/tests/interpret_maximum.mlir
  stablehlo/tests/interpret_minimum.mlir
  stablehlo/tests/interpret_multiply.mlir
  stablehlo/tests/interpret_negate.mlir
  stablehlo/tests/interpret_not.mlir
  stablehlo/tests/interpret_or.mlir
  stablehlo/tests/interpret_pad.mlir
  stablehlo/tests/interpret_reshape.mlir
  stablehlo/tests/interpret_reverse.mlir
  stablehlo/tests/interpret_rsqrt.mlir
  stablehlo/tests/interpret_select.mlir
  stablehlo/tests/interpret_sine.mlir
  stablehlo/tests/interpret_slice.mlir
  stablehlo/tests/interpret_sqrt.mlir
  stablehlo/tests/interpret_subtract.mlir
  stablehlo/tests/interpret_tanh.mlir
  stablehlo/tests/interpret_transpose.mlir
  stablehlo/tests/interpret_while.mlir
  stablehlo/tests/interpret_xor.mlir
  stablehlo/tools/CMakeLists.txt
  stablehlo/tools/StablehloInterpreterMain.cpp
Labels: Interpreter

#1201 Update checklist to review shape inference
  docs/reference_checklist.md
Labels: Spec

#1144 Add interpreter for RealOp
  docs/spec.md
  docs/status.md
  stablehlo/dialect/StablehloOps.td
  stablehlo/dialect/TypeInference.cpp
  stablehlo/reference/Element.cpp
  stablehlo/reference/Element.h
  stablehlo/reference/Ops.cpp
  stablehlo/reference/Ops.h
  stablehlo/tests/interpret_real.mlir
  stablehlo/tests/ops_stablehlo.mlir
Labels: Interpreter

#1145 Add interpreter for ImagOp
  docs/spec.md
  docs/status.md
  stablehlo/dialect/StablehloOps.td
  stablehlo/dialect/TypeInference.cpp
  stablehlo/reference/Element.cpp
  stablehlo/reference/Element.h
  stablehlo/reference/Ops.cpp
  stablehlo/reference/Ops.h
  stablehlo/tests/interpret_imag.mlir
  stablehlo/tests/ops_stablehlo.mlir
Labels: Interpreter

#1209 Simplify evalConcatenateOp
  stablehlo/reference/Ops.cpp
Labels: Interpreter

#1208 Fix a typo in the spec of IfOp
  docs/spec.md
Labels: Spec

#1092 Add interpreter for RemOp
  docs/spec.md
  docs/status.md
  stablehlo/dialect/StablehloOps.td
  stablehlo/reference/Element.cpp
  stablehlo/reference/Element.h
  stablehlo/reference/Ops.cpp
  stablehlo/reference/Ops.h
  stablehlo/tests/interpret_rem.mlir
Labels: Interpreter

#1171 Add interpreter for CaseOp
  docs/spec.md
  docs/status.md
  stablehlo/dialect/StablehloOps.td
  stablehlo/dialect/TypeInference.cpp
  stablehlo/reference/Ops.cpp
  stablehlo/reference/Ops.h
  stablehlo/tests/interpret_case.mlir
  stablehlo/tests/ops_stablehlo.mlir
Labels: Spec, Verification, Interpreter, Migrate to MHLO

#1210 Add index info in interpreter-mismatch error message
  stablehlo/tests/CheckOps.cpp
Labels: Interpreter

#1154 Create Element.h constructors to get Element with primitive value
  stablehlo/reference/Element.cpp
  stablehlo/reference/Element.h
  stablehlo/reference/Ops.cpp
Labels: Interpreter

#1223 Integrate LLVM at llvm/llvm-project@bc8de519ea6d4
  WORKSPACE.bazel
  build_tools/llvm_version.txt
  stablehlo/dialect/ChloOps.td
  stablehlo/dialect/StablehloOps.td
  stablehlo/dialect/VhloDialect.td
  stablehlo/tests/CheckOps.td
Labels: Integrations

#1211 Remove all references to 0.3.0 and 0.4.0
  stablehlo/dialect/Version.cpp
  stablehlo/dialect/Version.h
  stablehlo/dialect/VhloAttrs.td
  stablehlo/dialect/VhloDialect.td
  stablehlo/dialect/VhloEnums.td
  stablehlo/dialect/VhloOps.td
  stablehlo/dialect/VhloTypes.td
  stablehlo/tests/stablehlo_legalize_to_vhlo.mlir
  stablehlo/tests/vhlo_to_version_attrtype_invalid.mlir
  stablehlo/tests/vhlo_to_version_downgrade.mlir
  stablehlo/tests/vhlo_to_version_downgrade_invalid.mlir
  stablehlo/tests/vhlo_to_version_invalid_target_future.mlir
  stablehlo/tests/vhlo_to_version_invalid_target_minimum.mlir
  stablehlo/tests/vhlo_to_version_upgrade.mlir
  stablehlo/transforms/MapStablehloToVhlo.h
  stablehlo/transforms/VhloLegalizeToStablehlo.cpp
  stablehlo/transforms/VhloToVersion.cpp
Labels: Compatibility

#1224 Mark ReturnOp as having an interpreter
  docs/status.md
Labels: Interpreter

#1213 Refactor StableHLO <=> VHLO
  stablehlo/transforms/StablehloLegalizeToVhlo.cpp
  stablehlo/transforms/VhloLegalizeToStablehlo.cpp
Labels: Compatibility

#1214 Remove OptionalAttr from VHLO
  stablehlo/dialect/VhloOps.td
  stablehlo/integrations/python/tests/vhlo.py
  stablehlo/tests/stablehlo_legalize_to_vhlo.mlir
  stablehlo/transforms/StablehloLegalizeToVhlo.cpp
  stablehlo/transforms/VhloLegalizeToStablehlo.cpp
Labels: Compatibility

#1235 Use _v1 in VHLO mnemonics
  stablehlo/dialect/VhloAttrs.td
  stablehlo/dialect/VhloEnums.td
  stablehlo/dialect/VhloOps.td
  stablehlo/dialect/VhloTypes.td
  stablehlo/integrations/python/tests/vhlo.py
  stablehlo/tests/stablehlo_legalize_to_vhlo.mlir
Labels: Compatibility
