Repository openxla/stablehlo, pull requests merged in 2023-10, with the labels that each got.

#1787 Bump patch version after integrate 0.14.21 -> 0.14.22
  stablehlo/dialect/Version.h
Labels: Integrations

#1789 Integrate LLVM at llvm/llvm-project@3661a48a8473
  WORKSPACE.bazel
  build_tools/llvm_version.txt
Labels: Integrations

#1788 Fixing order of tests introduced in #1782
  stablehlo/tests/ops_stablehlo.mlir
Labels: Integrations, Migrate from MHLO

#1791 Integrate LLVM at llvm/llvm-project@173fd67a124d
  WORKSPACE.bazel
  build_tools/llvm_version.txt
  stablehlo/conversions/tosa/transforms/StablehloLegalizeToTosa.pdll
Labels: Integrations

#1793 Bump patch version after integrate 0.14.23 -> 0.14.24
  stablehlo/dialect/Version.h
Labels: Integrations

#1795 Integrate LLVM at llvm/llvm-project@2a1f1b5fde0a
  WORKSPACE.bazel
  build_tools/llvm_version.txt
  stablehlo/tests/print_stablehlo.mlir
Labels: Integrations

#1798 Integrate remainder of llvm/llvm-project@2a1f1b5fde0a
  stablehlo/tests/print_stablehlo.mlir
Labels: Integrations

#1804 Bump patch version after integrate 0.14.24 -> 0.14.25
  stablehlo/dialect/Version.h
Labels: Integrations

#1784 Add reference interpreter probe instrumentation
  BUILD.bazel
  stablehlo/reference/CMakeLists.txt
  stablehlo/reference/InterpreterOps.cpp
  stablehlo/reference/InterpreterOps.h
  stablehlo/reference/InterpreterOps.td
  stablehlo/reference/NumPy.cpp
  stablehlo/reference/NumPy.h
  stablehlo/reference/Ops.cpp
  stablehlo/reference/Ops.h
  stablehlo/reference/Tensor.h
  stablehlo/tests/BUILD.bazel
  stablehlo/tests/CMakeLists.txt
  stablehlo/tests/CheckOps.cpp
  stablehlo/tests/CheckOps.h
  stablehlo/tests/CheckOps.td
  stablehlo/tests/interpret_probe.mlir
  stablehlo/tools/StablehloTranslateMain.cpp
Labels: Integrations

#1805 Integrate LLVM at llvm/llvm-project@b15b84610f63
  WORKSPACE.bazel
  build_tools/llvm_version.txt
Labels: Integrations

#1806 Fix clang tidy, remove unused dependencies
  BUILD.bazel
  stablehlo/reference/CMakeLists.txt
  stablehlo/reference/InterpreterOps.h
  stablehlo/tests/BUILD.bazel
  stablehlo/tests/CMakeLists.txt
Labels: Integrations

#1807 Integrate LLVM at llvm/llvm-project@97217d188469
  WORKSPACE.bazel
  build_tools/llvm_version.txt
  stablehlo/reference/NumPy.cpp
Labels: Integrations

#1808 Bump patch version after integrate 0.14.25 -> 0.14.26
  stablehlo/dialect/Version.h
Labels: Integrations

#1811 Bump patch version after integrate 0.14.26 -> 0.14.27
  stablehlo/dialect/Version.h
Labels: Integrations

#1814 Integrate LLVM at llvm/llvm-project@c122b9727a27
  WORKSPACE.bazel
  build_tools/llvm_version.txt
Labels: Integrations

#1816 Bump patch version after integrate 0.14.27 -> 0.14.28
  stablehlo/dialect/Version.h
Labels: Integrations

#1813 fix vhlo DictionaryAttr's printer with separated comma
  stablehlo/dialect/VhloOps.cpp
  stablehlo/tests/stablehlo_legalize_to_vhlo.mlir
Labels: Prettyprinting

#1810 Build changes to allow cleaner downstream integrations
  BUILD.bazel
  WORKSPACE.bazel
  stablehlo/conversions/tosa/tests/BUILD.bazel
  stablehlo/conversions/tosa/tests/lit.site.cfg.py.in
  stablehlo/testdata/BUILD.bazel
  stablehlo/testdata/lit.site.cfg.py.in
  stablehlo/tests/BUILD.bazel
  stablehlo/tests/lit.site.cfg.py.in
Labels: Build
