Repository openxla/stablehlo, pull requests merged in 2023-01, with the labels that each got.

#876 Add missing constraint for selectAndScatter op
  docs/spec.md
Labels: Spec

#880 Integrate LLVM at llvm/llvm-project@9cd113a2a8fa
  build_tools/llvm_version.txt
Labels: Integrations

#824 Handle Dynamic Bounds in Shape Function of DynamicUpdateSliceOp
  stablehlo/dialect/TypeInference.cpp
  stablehlo/tests/infer_stablehlo.mlir
Labels: Type inference, Dynamism, Migrate to MHLO

#883 Reinstate util functions in TypeInference.h
  stablehlo/dialect/TypeInference.cpp
  stablehlo/dialect/TypeInference.h
Labels: Type inference, Migrate from MHLO

#882 Expose verifyConvolutionAttributes in TypeInference.h
  stablehlo/dialect/TypeInference.cpp
Labels: Verification, Migrate from MHLO

#890 Also allow one item in precision_config
  stablehlo/dialect/TypeInference.cpp
  stablehlo/tests/ops_stablehlo.mlir
  stablehlo/tests/verify_conv.mlir
Labels: Verification, Migrate from MHLO

#881 Fix typos in infer_stablehlo.mlir tests
  stablehlo/tests/infer_stablehlo.mlir
Labels: Type inference

#892 Remove AllShapesMatch from DynamicUpdateSliceOp
  stablehlo/dialect/StablehloOps.td
  stablehlo/tests/ops_stablehlo.mlir
Labels: Verification

#889 Integrate LLVM at llvm/llvm-project@7504e9a19346
  build_tools/llvm_version.txt
Labels: Integrations

#901 Fix clang-format lint action to skip deleted files
  build_tools/github_actions/lint_clang_format.sh
Labels: Integrations

#896 Remove outdated #defines in Passes.h
  stablehlo/transforms/Passes.h
Labels: Compatibility

#895 Rename .cpp files for legalize passes to match pass names
  stablehlo/transforms/CMakeLists.txt
  stablehlo/transforms/StablehloLegalizeToVhlo.cpp
  stablehlo/transforms/VhloLegalizeToStablehlo.cpp
Labels: Compatibility

#894 Make CHLO ops inlinable
  stablehlo/dialect/CMakeLists.txt
  stablehlo/dialect/ChloOps.cpp
  stablehlo/tests/transform_chlo.mlir
Labels: Integrations

#893 Relax dimension checks in TriangularSolveOp
  stablehlo/dialect/TypeInference.cpp
  stablehlo/tests/ops_stablehlo.mlir
Labels: Verification

#891 Consistently use HLO_StaticShapeTensor
  stablehlo/dialect/Base.td
  stablehlo/dialect/StablehloOps.td
Labels: Verification

#897 Simplify some dimension checks by using verifyCompatibleDims
  stablehlo/dialect/TypeInference.cpp
Labels: Verification

#898 Create inferFooOp functions for some infeasible ops
  stablehlo/dialect/TypeInference.cpp
  stablehlo/dialect/TypeInference.h
  stablehlo/tests/ops_stablehlo.mlir
Labels: Type inference

#904 Update spec status for convolution op: `revisit` to `yes`
  docs/status.md
Labels: Spec

#910 Fix typo in spec.md
  docs/spec.md
Labels: Spec

#841 Lint cleanup for list indentation
  .markdownlint.yaml
  docs/bytecode.md
  docs/reference.md
  docs/spec.md
  docs/status.md
  docs/type_inference.md
  rfcs/20220912-compatibility.md
Labels: Process

#912 Integrate LLVM at llvm/llvm-project@d414c2ad0cac
  build_tools/llvm_version.txt
  stablehlo/dialect/AssemblyFormat.h
Labels: Integrations

#887 Handle bounds in the CholeskyOp shape function
  stablehlo/dialect/TypeInference.cpp
  stablehlo/tests/infer_stablehlo.mlir
Labels: Type inference, Dynamism, Migrate to MHLO

#905 Make precision config optional in VHLO
  stablehlo/dialect/VhloAttrs.td
  stablehlo/dialect/VhloOps.td
  stablehlo/tests/legalize_stablehlo_to_vhlo.mlir
Labels: Compatibility

#915 Replace makeArrayRef with ArrayRef in Python bindings
  stablehlo/integrations/c/StablehloAttributes.cpp
Labels: Integrations

#919 Verify exponent and mantissa in ReducePrecisionOp
  stablehlo/dialect/StablehloOps.cpp
  stablehlo/dialect/TypeInference.cpp
  stablehlo/dialect/TypeInference.h
  stablehlo/tests/ops_stablehlo.mlir
Labels: Verification

#923 Rename grid to "process grid"
  docs/spec.md
Labels: Spec

#909 Handle bounds in the WhileOp shape function
  stablehlo/tests/infer_stablehlo.mlir
Labels: Type inference, Dynamism

#913 Infer bounds for SortOp.
  stablehlo/dialect/TypeInference.cpp
  stablehlo/tests/infer_stablehlo.mlir
Labels: Type inference, Dynamism, Migrate to MHLO

#928 Verify dimensions in ReverseOp
  docs/status.md
  stablehlo/dialect/StablehloOps.cpp
  stablehlo/dialect/StablehloOps.td
  stablehlo/dialect/TypeInference.cpp
  stablehlo/dialect/TypeInference.h
  stablehlo/tests/ops_stablehlo.mlir
Labels: Verification, Migrate to MHLO

#920 Handle bounds for ScatterOp shape function
  stablehlo/tests/infer_stablehlo.mlir
Labels: Type inference, Dynamism, Migrate to MHLO

#922 Relax remaining dimension checks to better support dynamism
  stablehlo/dialect/TypeInference.cpp
  stablehlo/tests/ops_stablehlo.mlir
Labels: Verification, Dynamism, Migrate to MHLO

#917 Handle bounds in the SelectAndScatterOp shape function
  stablehlo/tests/infer_stablehlo.mlir
Labels: Type inference, Dynamism, Migrate to MHLO

#877 Added missing detail for remainder op
  docs/spec.md
Labels: Spec

#902 Support bounds in hlo_test_infer.get_return_type_components rewrite pattern.
  stablehlo/tests/TestUtils.cpp
  stablehlo/tests/infer_stablehlo.mlir
Labels: Type inference

#937 Remove remaining usages of llvm::Optional
  stablehlo/dialect/Base.cpp
  stablehlo/dialect/Base.h
  stablehlo/dialect/ChloOps.cpp
  stablehlo/dialect/StablehloOps.cpp
  stablehlo/dialect/StablehloOps.h
  stablehlo/dialect/TypeInference.cpp
  stablehlo/dialect/TypeInference.h
  stablehlo/integrations/c/ChloAttributes.cpp
  stablehlo/integrations/c/StablehloAttributes.cpp
  stablehlo/integrations/c/StablehloAttributes.h
  stablehlo/reference/Index.h
Labels: Integrations

#921 Infer bounds for AllToAllOp.
  stablehlo/dialect/TypeInference.cpp
  stablehlo/tests/infer_stablehlo.mlir
Labels: Type inference, Dynamism, Migrate to MHLO

#916 Handle bounds in the ReduceWindowOp shape function
  stablehlo/dialect/TypeInference.cpp
  stablehlo/tests/infer_stablehlo.mlir
Labels: Type inference, Dynamism, Migrate to MHLO

#900 Infer bounds for BatchNorm* Ops.
  stablehlo/dialect/StablehloOps.cpp
  stablehlo/dialect/StablehloOps.td
  stablehlo/dialect/TypeInference.cpp
  stablehlo/dialect/TypeInference.h
  stablehlo/tests/infer_stablehlo.mlir
  stablehlo/tests/ops_stablehlo.mlir
Labels: Type inference, Dynamism, Migrate to MHLO

#940 Mention that mardkownlint does not check ol indentation
  .markdownlint.yaml
Labels: Process

#939 Integrate LLVM at llvm/llvm-project@b3eb004ca78f
  build_tools/llvm_version.txt
  stablehlo/dialect/ChloOps.cpp
  stablehlo/dialect/StablehloOps.cpp
Labels: Integrations

#924 Update ODS to sync supported types to the spec
  docs/status.md
  stablehlo/dialect/StablehloOps.td
  stablehlo/tests/ops_stablehlo_roundtrip.mlir
  stablehlo/tests/print_stablehlo.mlir
Labels: Verification, Migrate to MHLO

#816 Add interpreter testing guidelines
  docs/reference.md
Labels: Process

#941 Add github action to run markdownlint on pull requests
  .github/workflows/markdown_lint.yml
Labels: Process

#945 Reorganize VHLO .td files
  stablehlo/dialect/VhloAttrs.td
  stablehlo/dialect/VhloDialect.td
  stablehlo/dialect/VhloOps.td
  stablehlo/dialect/VhloTypes.td
Labels: Migrate from MHLO, Compatibility

#933 Add new intro and build steps for readme
  README.md
  build_tools/README.md
Labels: Process

#946 Update infer_stablehlo.mlir
  stablehlo/tests/infer_stablehlo.mlir
Labels: Migrate to MHLO

#947 Add "Constraints" column to Inputs/Outputs
  docs/spec.md
Labels: Spec

#942 Verify that start_indices have the same type in DynamicSliceOp
  docs/status.md
  stablehlo/dialect/TypeInference.cpp
  stablehlo/tests/ops_stablehlo.mlir
Labels: Verification, Migrate to MHLO

#948 Integrate LLVM at llvm/llvm-project@afca08a567e3
  build_tools/llvm_version.txt
Labels: Integrations

#935 Fix Reduce op bounds inference for scalar results
  stablehlo/dialect/TypeInference.cpp
  stablehlo/tests/infer_stablehlo.mlir
Labels: Type inference, Dynamism

#953 Make build instructions repeatable
  README.md
Labels: Process

#950 Add local code coverage generation tooling
  build_tools/github_actions/ci_build_stablehlo_code_coverage.sh
  build_tools/github_actions/llvm_gcov.sh
Labels: Build

#936 Update dialects to use the folder adaptors
  docs/reference.md
  stablehlo/dialect/ChloOps.cpp
  stablehlo/dialect/ChloOps.td
  stablehlo/dialect/StablehloOps.cpp
  stablehlo/dialect/StablehloOps.td
  stablehlo/dialect/VhloDialect.td
Labels: Integrations

#957 Integrate LLVM at llvm/llvm-project@171e7b831227
  build_tools/llvm_version.txt
Labels: Integrations

#927 Verify dimension in GetDimensionSizeOp
  docs/spec.md
  docs/status.md
  stablehlo/dialect/StablehloOps.cpp
  stablehlo/tests/ops_stablehlo.mlir
Labels: Verification, Migrate to MHLO

#908 Handle bounds of Gather op
  stablehlo/dialect/TypeInference.cpp
  stablehlo/tests/infer_stablehlo.mlir
Labels: Type inference, Dynamism, Migrate to MHLO

#819 Handle bounds among branches
  stablehlo/dialect/Base.cpp
  stablehlo/dialect/Base.h
  stablehlo/dialect/TypeInference.cpp
  stablehlo/tests/infer_stablehlo.mlir
Labels: Type inference, Dynamism, Migrate to MHLO

#930 Handle bounds in `TriangularSolveOp` shape function
  stablehlo/dialect/TypeInference.cpp
  stablehlo/tests/infer_stablehlo.mlir
Labels: Type inference, Dynamism, Migrate to MHLO

#960 Remove InferReturnTypeComponents test pattern from hlo_test_infer.
  stablehlo/tests/TestUtils.cpp
  stablehlo/tests/infer_chlo.mlir
  stablehlo/tests/infer_stablehlo.mlir
Labels: Process, Migrate to MHLO

#788 Create a Bazel build
  .bazelrc
  .bazelversion
  .github/actions/setup-build/action.yml
  .github/workflows/buildAndTestCMake.yml
  .github/workflows/buildBazel.yml
  .github/workflows/lint.yml
  .gitignore
  BUILD
  WORKSPACE
  build_tools/github_actions/ci_build_bazel.sh
  build_tools/github_actions/lint_llvm_commit.sh
Labels: Build

#911 Handle bounds in the FftOp shape function
  stablehlo/dialect/TypeInference.cpp
  stablehlo/tests/infer_stablehlo.mlir
Labels: Type inference, Dynamism, Migrate to MHLO

#958 Verify compare_type for compare_op.
  stablehlo/dialect/StablehloOps.cpp
  stablehlo/dialect/TypeInference.cpp
  stablehlo/dialect/TypeInference.h
  stablehlo/tests/legalize_stablehlo_to_vhlo.mlir
  stablehlo/tests/ops_stablehlo.mlir
  stablehlo/tests/print_stablehlo.mlir
Labels: Verification

#1003 Integrate LLVM at llvm/llvm-project@c4c5e79dd4b4
  WORKSPACE
  build_tools/llvm_version.txt
  stablehlo/dialect/AssemblyFormat.cpp
  stablehlo/dialect/AssemblyFormat.h
Labels: Integrations

#951 Interpreter implementation and review guidelines
  docs/interpreter_checklist.md
  docs/reference.md
Labels: Interpreter

#1007 Update eval signature for re-usability
  stablehlo/reference/Interpreter.cpp
  stablehlo/reference/Ops.cpp
  stablehlo/reference/Ops.h
Labels: Interpreter

#1015 Mark ReducePrecisionOp as [Pure]
  stablehlo/dialect/StablehloOps.td
Labels: Migrate from MHLO

#1016 Support ReduceWindowOp creation with a Region
  stablehlo/dialect/StablehloOps.cpp
  stablehlo/dialect/StablehloOps.td
Labels: Migrate from MHLO

#1018 Document TorchIndexSelectOp
  stablehlo/dialect/StablehloOps.td
Labels: Migrate from MHLO

#1023 Rename BUILD -> BUILD.bazel
  BUILD.bazel
  WORKSPACE.bazel
  build_tools/github_actions/lint_llvm_commit.sh
Labels: Build

#1017 Fix reifyGatherShape to return tensors of index
  stablehlo/dialect/StablehloOps.cpp
  stablehlo/tests/infer_stablehlo.mlir
Labels: Type inference, Dynamism, Migrate from MHLO

#1011 Remove type inference for ReturnOp
  docs/status.md
  stablehlo/dialect/StablehloOps.cpp
  stablehlo/dialect/StablehloOps.td
  stablehlo/dialect/TypeInference.cpp
  stablehlo/dialect/TypeInference.h
Labels: Type inference

#1012 Improve type inference for DynamicGatherOp
  stablehlo/dialect/TypeInference.cpp
  stablehlo/tests/infer_stablehlo.mlir
Labels: Type inference, Dynamism

#1025 Update reference_checklist: Add constraint labels in ODS
  docs/reference_checklist.md
Labels: Spec

#1019 Update signature of `infer<Op>` function for re-usability
  stablehlo/dialect/StablehloOps.cpp
  stablehlo/dialect/TypeInference.cpp
  stablehlo/dialect/TypeInference.h
Labels: Interpreter, Migrate to MHLO
