Repository openxla/stablehlo, pull requests merged in 2024-12, with the labels that each got.

#2651 Bump patch version after integrate 1.8.4 -> 1.8.5
  stablehlo/dialect/Version.cpp
  stablehlo/dialect/Version.h
Labels: Integrations

#2656 Integrate LLVM at llvm/llvm-project@bd92e4620433
  WORKSPACE.bazel
  build_tools/llvm_version.txt
  docs/interpreter_status.md
  stablehlo/tests/transforms/stablehlo_convert_to_signless.mlir
  stablehlo/transforms/StablehloAggressiveFolder.cpp
Labels: Integrations

#2661 Integrate LLVM at llvm/llvm-project@2ccf7ed277df
  BUILD.bazel
  WORKSPACE.bazel
  build_tools/llvm_version.txt
  stablehlo/dialect/Serialization.cpp
  stablehlo/dialect/Serialization.h
  stablehlo/dialect/TypeInference.cpp
  stablehlo/dialect/TypeInference.h
  stablehlo/tests/print_types_invalid.mlir
  stablehlo/tests/transforms/stablehlo_refine_parameters.mlir
  stablehlo/tests/vhlo/vhlo_emit_version_api.1_1_0.mlir
  stablehlo/tests/vhlo/vhlo_emit_version_api.1_1_0.mlir.bc
  stablehlo/tools/StablehloTranslateMain.cpp
  stablehlo/transforms/StablehloRefineArguments.cpp
Labels: Integrations

#2662 Bump patch version after integrate 1.8.6 -> 1.8.7
  stablehlo/dialect/Version.h
Labels: Integrations

#2660 Add StableHLO to linalg conversions to python bindings
  BUILD.bazel
  stablehlo/integrations/c/StablehloPasses.cpp
Labels: Transformations

#2666 Integrate LLVM at llvm/llvm-project@0876c11ceeb0
  WORKSPACE.bazel
  build_tools/llvm_version.txt
Labels: Integrations

#2671 Add 'large' test qualifier for lit tests
  stablehlo/testdata/BUILD.bazel
  stablehlo/testdata/igamma_float64_20_20_float64_20_20_chlo.large.mlir
  stablehlo/testdata/igammac_float64_20_20_float64_20_20_chlo.large.mlir
  stablehlo/testdata/quantized/conv_general_dilated_tf_conversion_path_3d_lhs_float32_1_4_28_28_1__rhs_float32_2_3_3_1_16__windowst-8282934958224398022_qi8.large.mlir
  stablehlo/testdata/quantized/conv_general_dilated_tf_conversion_path_3d_lhs_float32_1_4_28_28_1__rhs_float32_2_3_3_1_16__windowst8524424959485066052_qi8.large.mlir
Labels: Build

#2636 Add StableHLO complex log1p operation. Add pass stablehlo-complex-math-expander
  BUILD.bazel
  build_tools/math/README.md
  build_tools/math/generate_ChloDecompositionPatternsMath.py
  build_tools/math/generate_tests.py
  docs/generated/stablehlo_passes.md
  docs/spec.md
  stablehlo/tests/math/log_plus_one_complex128.mlir
  stablehlo/tests/math/log_plus_one_complex64.mlir
  stablehlo/tests/math/log_plus_one_float32.mlir
  stablehlo/tests/math/log_plus_one_float64.mlir
  stablehlo/tests/stablehlo_complex_math_expander.mlir
  stablehlo/transforms/CMakeLists.txt
  stablehlo/transforms/ChloDecompositionPatternsMath.td
  stablehlo/transforms/Passes.h
  stablehlo/transforms/Passes.td
  stablehlo/transforms/StablehloComplexMathExpander.cpp
  stablehlo/transforms/StablehloComplexMathExpanderPatterns.td
Labels: CHLO

#2674 Integrate LLVM at llvm/llvm-project@e86910337f98
  .github/workflows/buildAndTestCMake.yml
  .github/workflows/publishWheelRelease.yml
  WORKSPACE.bazel
  build_tools/llvm_version.txt
  stablehlo/integrations/python/CMakeLists.txt
  stablehlo/integrations/python/CheckModule.cpp
  stablehlo/integrations/python/ChloModule.cpp
  stablehlo/integrations/python/StablehloApi.cpp
  stablehlo/integrations/python/StablehloApi.h
  stablehlo/integrations/python/StablehloModule.cpp
  stablehlo/integrations/python/VhloModule.cpp
  stablehlo/tests/ops_chlo.mlir
Labels: Integrations

#2676 Cleaning up tests in chlo_ops.mlir backported twice
  stablehlo/tests/ops_chlo.mlir
Labels: Integrations

#2677 Bump patch version after integrate 1.8.8 -> 1.8.9
  stablehlo/dialect/Version.cpp
  stablehlo/dialect/Version.h
Labels: Integrations

#2675 Add refinement test for if/case
  stablehlo/tests/transforms/stablehlo_refine_shapes.mlir
Labels: Dynamism
