Repository openxla/stablehlo, pull requests merged in 2024-06, with the labels that each got.

#2125 Add support of float type in specialization of ConvertOp
  docs/generated/stablehlo_passes.md
  stablehlo/tests/stablehlo_aggressive_folder.mlir
  stablehlo/tests/stablehlo_refine_shapes.mlir
  stablehlo/transforms/Passes.h
  stablehlo/transforms/Passes.td
  stablehlo/transforms/StablehloAggressiveFolder.cpp
Labels: Transformations

#2374 Bump patch version after integrate 1.1.1 -> 1.1.2
  stablehlo/dialect/Version.h
Labels: Integrations

#2375 Integrate LLVM at llvm/llvm-project@765206e05045
  WORKSPACE.bazel
  build_tools/llvm_version.txt
Labels: Integrations

#2378 Fix the return type of python generator function
  stablehlo/integrations/python/stablehlo/savedmodel/stablehlo_to_tf_saved_model.py
Labels: Integrations

#2381 Move interpreter probe pass to reference
  BUILD.bazel
  build_tools/github_actions/ci_build_docs.sh
  docs/_toc.yaml
  docs/generated/interpreter_passes.md
  docs/generated/stablehlo_passes.md
  stablehlo/conversions/linalg/transforms/CMakeLists.txt
  stablehlo/reference/CMakeLists.txt
  stablehlo/reference/InterpreterInstrumentWithProbe.cpp
  stablehlo/reference/InterpreterOps.td
  stablehlo/reference/InterpreterPasses.h
  stablehlo/reference/InterpreterPasses.td
  stablehlo/tests/stablehlo_probe_instrumentation.mlir
  stablehlo/tools/CMakeLists.txt
  stablehlo/tools/StablehloOptMain.cpp
  stablehlo/transforms/CMakeLists.txt
  stablehlo/transforms/Passes.td
Labels: Cleanup/Refactoring, Transformations

#2382 Bump patch version after integrate 1.1.2 -> 1.1.3
  stablehlo/dialect/Version.h
Labels: Integrations

#2383 Port mhlo-quant-legalize-to-int pass to StableHLO
  BUILD.bazel
  docs/generated/stablehlo_passes.md
  stablehlo/tests/stablehlo_legalize_quant_to_int.mlir
  stablehlo/transforms/CMakeLists.txt
  stablehlo/transforms/Passes.td
  stablehlo/transforms/StablehloLegalizeQuantToInt.cpp
Labels: Quantization

#2393 Bump patch version after integrate 1.1.3 -> 1.1.4
  stablehlo/dialect/Version.h
Labels: Integrations, Build

#2357 Improve the accuracy of asin for complex inputs using modified Hull et al algorithm
  BUILD.bazel
  build_tools/math/README.md
  build_tools/math/generate_ChloDecompositionPatternsMath.py
  build_tools/math/generate_tests.py
  stablehlo/tests/BUILD.bazel
  stablehlo/tests/CheckOps.cpp
  stablehlo/tests/CheckOps.h
  stablehlo/tests/CheckOps.td
  stablehlo/tests/chlo/chlo_legalize_to_stablehlo.mlir
  stablehlo/tests/math/asin_complex128.mlir
  stablehlo/tests/math/asin_complex64.mlir
  stablehlo/tests/math/asin_float32.mlir
  stablehlo/tests/math/asin_float64.mlir
  stablehlo/tests/math/ulp_difference_float32.mlir
  stablehlo/tests/math/ulp_difference_float64.mlir
  stablehlo/tools/StablehloTranslateMain.cpp
  stablehlo/transforms/ChloDecompositionPatterns.td
  stablehlo/transforms/ChloDecompositionPatternsMath.td
  stablehlo/transforms/ChloLegalizeToStablehlo.cpp
Labels: CHLO

#2397 Integrate LLVM at llvm/llvm-project@e83adfe59632
  WORKSPACE.bazel
  build_tools/llvm_version.txt
Labels: Integrations

#2395 Fix legalization of quantized Min/Max op to Int ops
  stablehlo/tests/stablehlo_legalize_quant_to_int.mlir
  stablehlo/transforms/StablehloLegalizeQuantToInt.cpp
Labels: Quantization

#2398 Integrate LLVM at llvm/llvm-project@52d87de7a42d
  WORKSPACE.bazel
  build_tools/llvm_version.txt
  stablehlo/tests/TestUtils.cpp
  stablehlo/transforms/StablehloCanonicalizeDynamism.cpp
  stablehlo/transforms/StablehloRefineShapes.cpp
Labels: Integrations

#2399 Lint fixes driven by internal intregation
  build_tools/math/generate_ChloDecompositionPatternsMath.py
  build_tools/math/generate_tests.py
  stablehlo/integrations/python/tests/stablehlo.py
Labels: Integrations

#2404 Add testdata files for quantized stablohlo programs
  stablehlo/reference/Api.cpp
  stablehlo/testdata/quantized/abs_shape_float32_20_20_qi8.mlir
  stablehlo/testdata/quantized/add_qi8.mlir
  stablehlo/testdata/quantized/cbrt_shape_float32_20_20_qi8.mlir
  stablehlo/testdata/quantized/ceil_qi8.mlir
  stablehlo/testdata/quantized/ceil_shape_float32_20_20_qi8.mlir
  stablehlo/testdata/quantized/cos_shape_float32_20_20_qi8.mlir
  stablehlo/testdata/quantized/cosine_qi8.mlir
  stablehlo/testdata/quantized/div_dtypes_lhs_float32_2__rhs_float32_2_qi8.mlir
  stablehlo/testdata/quantized/div_singularity_0_by_0_lhs_float32_2__rhs_float32_2_qi8.mlir
  stablehlo/testdata/quantized/div_singularity_inf_by_inf_lhs_float32_1__rhs_float32_1_qi8.mlir
  stablehlo/testdata/quantized/div_singularity_negative_by_0_lhs_float32_2__rhs_float32_2_qi8.mlir
  stablehlo/testdata/quantized/div_singularity_positive_by_0_lhs_float32_2__rhs_float32_2_qi8.mlir
  stablehlo/testdata/quantized/exp_shape_float32_20_20_qi8.mlir
  stablehlo/testdata/quantized/expm1_shape_float32_20_20_qi8.mlir
  stablehlo/testdata/quantized/floor_qi8.mlir
  stablehlo/testdata/quantized/floor_shape_float32_20_20_qi8.mlir
  stablehlo/testdata/quantized/integer_pow_dtypes_shape_float32_20_30__y_2_qi8.mlir
  stablehlo/testdata/quantized/log1p_shape_float32_20_20_qi8.mlir
  stablehlo/testdata/quantized/log_shape_float32_20_20_qi8.mlir
  stablehlo/testdata/quantized/mul_dtypes_lhs_float32_20_20__rhs_float32_20_20_qi8.mlir
  stablehlo/testdata/quantized/multiply_qi8.mlir
  stablehlo/testdata/quantized/neg_shape_float32_20_20_qi8.mlir
  stablehlo/testdata/quantized/negate_qi8.mlir
  stablehlo/testdata/quantized/sign_shape_float32_20_20_qi8.mlir
  stablehlo/testdata/quantized/sign_special_0_dtype_float32_qi8.mlir
  stablehlo/testdata/quantized/sin_shape_float32_20_20_qi8.mlir
  stablehlo/testdata/quantized/sine_qi8.mlir
  stablehlo/testdata/quantized/sqrt_shape_float32_20_20_qi8.mlir
  stablehlo/testdata/quantized/sub_dtypes_lhs_float32_20_20__rhs_float32_20_20_qi8.mlir
  stablehlo/testdata/quantized/subtract_qi8.mlir
  stablehlo/testdata/quantized/tanh_qi8.mlir
  stablehlo/testdata/quantized/tanh_shape_float32_20_20_qi8.mlir
Labels: Quantization

#2406 Use built-in function to check for emptiness
  stablehlo/tests/CheckOps.cpp
Labels: Cleanup/Refactoring

#2407 Integrate LLVM at llvm/llvm-project@c07be08df573
  WORKSPACE.bazel
  build_tools/llvm_version.txt
Labels: Integrations

#2408 Bump patch version after integrate 1.1.5 -> 1.1.6
  stablehlo/dialect/Version.h
Labels: Integrations

#2410 Integrate LLVM at llvm/llvm-project@5cd0ba30f53d
  WORKSPACE.bazel
  build_tools/llvm_version.txt
Labels: Integrations

#2412 Bump patch version after integrate 1.1.6 -> 1.1.7
  stablehlo/dialect/Version.h
Labels: Integrations

#2097 [RFC] Standardize CustomCallOp to extend backend_config to take a DictionaryAttr
  docs/spec.md
  rfcs/20240312-standardize-customcallop.md
Labels: RFC

#2417 Remove spurious symbol on lit error checks
  stablehlo/tests/ops_stablehlo.mlir
Labels: Cleanup/Refactoring

#2403 [RFC] Add support for int2 in StableHLO
  rfcs/20240620-int2.md
Labels: Spec, RFC

#2099 [RFC] Standardize Collective (AllGatherOp, AllReduceOp, AllToAllOp) ops to support variadic operand/result
  docs/spec.md
  rfcs/20240312-standardize-collective-ops.md
Labels: RFC

#2416 Use ConfinedAttr to verify attr range is positve or nonnegative
  stablehlo/dialect/StablehloOps.cpp
  stablehlo/dialect/StablehloOps.td
  stablehlo/dialect/TypeInference.cpp
  stablehlo/dialect/TypeInference.h
  stablehlo/tests/ops_stablehlo.mlir
  stablehlo/tests/verify_convolution.mlir
  stablehlo/tests/verify_dynamic_conv.mlir
Labels: Verification, Migrate to MHLO
