Repository openxla/stablehlo, pull requests merged in 2024-04, with the labels that each got.

#1792 [RFC] Add hybrid quantized convolution and dot_general for weight-only quantization
  rfcs/20231005-hybrid-quantization.md
Labels: RFC

#2040 Add StableHLO dialect version for bytecode
  BUILD.bazel
  stablehlo/dialect/CMakeLists.txt
  stablehlo/dialect/StablehloBytecode.cpp
  stablehlo/dialect/StablehloOps.cpp
  stablehlo/dialect/StablehloOps.h
Labels: Compatibility

#2081 Quantization Verifiers : Add/update custom verifiers for quantized constraints
  stablehlo/dialect/StablehloOps.cpp
  stablehlo/dialect/StablehloOps.td
  stablehlo/dialect/TypeInference.cpp
  stablehlo/dialect/TypeInference.h
  stablehlo/tests/ops_stablehlo.mlir
  stablehlo/tests/ops_stablehlo_quantized.mlir
Labels: Verification, Migrate to MHLO

#1964 Add interpreter for ConvolutionOp
  docs/spec.md
  docs/status.md
  stablehlo/reference/Index.cpp
  stablehlo/reference/Index.h
  stablehlo/reference/Ops.cpp
  stablehlo/reference/Ops.h
  stablehlo/tests/interpret/convolution.mlir
Labels: Interpreter

#2204 ReverseOp : remove HLO_CompatibleOperandsAndResultType trait
  stablehlo/dialect/StablehloOps.cpp
  stablehlo/dialect/StablehloOps.td
  stablehlo/dialect/TypeInference.cpp
  stablehlo/dialect/TypeInference.h
Labels: Verification, Type inference, Quantization

#2171 Update spec and verifier for convolution op according to the RFC for hybrid quantized op
  docs/spec.md
  stablehlo/dialect/TypeInference.cpp
  stablehlo/tests/ops_stablehlo_quantized.mlir
Labels: Verification, Quantization

#2212 Add prettier printing for constant operations
  stablehlo/dialect/StablehloOps.cpp
  stablehlo/dialect/StablehloOps.td
  stablehlo/tests/shape_legalize_to_stablehlo.mlir
  stablehlo/tests/stablehlo_canonicalize_dynamism.mlir
Labels: Prettyprinting

#2116 Remove shape operand change from Dynamism RFC
  rfcs/20230704-dynamism-101.md
Labels: RFC

#2217 Remove unnecessary {RankedTensor,Shaped}Type casts
  stablehlo/conversions/linalg/transforms/StablehloLegalizeToLinalg.cpp
  stablehlo/conversions/linalg/transforms/StablehloToLinalgConvolution.cpp
  stablehlo/conversions/linalg/transforms/StablehloToLinalgDotProduct.cpp
  stablehlo/conversions/tosa/transforms/StablehloLegalizeToTosa.cpp
  stablehlo/dialect/StablehloOps.cpp
Labels: Cleanup/Refactoring

#2218 Simplify getResult().getType() to just getType()
  stablehlo/conversions/linalg/transforms/StablehloLegalizeToLinalg.cpp
  stablehlo/conversions/linalg/transforms/StablehloToLinalgConvolution.cpp
  stablehlo/conversions/linalg/transforms/StablehloToLinalgRandom.cpp
  stablehlo/conversions/tosa/transforms/StablehloLegalizeToTosa.cpp
  stablehlo/transforms/ChloLegalizeToStablehlo.cpp
  stablehlo/transforms/ShapeLegalizeToStablehlo.cpp
Labels: Cleanup/Refactoring

#2207 Add a note: Type Inference for Quantization is not always feasible
  docs/status.md
Labels: Quantization

#2211 Relax constraint `num_bits(storage_type) < num_bits(expressed_type)`
  docs/spec.md
Labels: Quantization

#2232 Tutorial: JAX Export to StableHLO
  build_tools/github_actions/lint_check_license.sh
  build_tools/github_actions/lint_whitespace_checks.sh
  docs/_toc.yaml
  docs/tutorials/jax-export.ipynb
Labels: Documentation

#2224 Enable testdata for convolution ops
  stablehlo/reference/Ops.cpp
  stablehlo/testdata/conv_general_dilated_conv1d_lhs_float32_2_3_10__rhs_float32_3_3_5__windowstrides__1___padding___0_0_3336387849681708224.mlir
  stablehlo/testdata/conv_general_dilated_conv_tranpose1d_same_padding_lhs_float32_1_16_2__rhs_float32_3_2_2__windowstrid-2801039169040378295.mlir
  stablehlo/testdata/conv_general_dilated_conv_tranpose1d_valid_padding_lhs_float32_1_16_2__rhs_float32_3_2_2__windowstri-8415303397313720110.mlir
  stablehlo/testdata/conv_general_dilated_conv_tranpose2d_same_padding_lhs_float32_1_16_16_2__rhs_float32_2_3_2_2__window-296817466026258822.mlir
  stablehlo/testdata/conv_general_dilated_conv_tranpose2d_valid_padding_lhs_float32_1_16_16_2__rhs_float32_2_3_2_2__windo216554503587864094.mlir
  stablehlo/testdata/conv_general_dilated_depthwise1d_dilated_lhs_float32_2_3_9__rhs_float32_12_1_3__windowstrides__1___p4726467912149865720.mlir
  stablehlo/testdata/conv_general_dilated_depthwise1d_lhs_float32_2_3_9__rhs_float32_12_1_3__windowstrides__1___padding__2025442285785167829.mlir
  stablehlo/testdata/conv_general_dilated_depthwise2d_dilated_lhs_float32_2_3_9_9__rhs_float32_12_1_3_3__windowstrides__1-5299255563318388077.mlir
  stablehlo/testdata/conv_general_dilated_depthwise2d_lhs_float32_2_3_9_9__rhs_float32_12_1_3_3__windowstrides__1_1__padd-5494580149111736437.mlir
  stablehlo/testdata/conv_general_dilated_dilations_lhs_float32_2_3_9_10__rhs_float32_3_3_4_5__windowstrides__1_1__paddin-940783895638600378.mlir
  stablehlo/testdata/conv_general_dilated_dilations_lhs_float32_2_3_9_10__rhs_float32_3_3_4_5__windowstrides__1_1__paddin7803468828575064957.mlir
  stablehlo/testdata/conv_general_dilated_dilations_lhs_float32_2_3_9_10__rhs_float32_3_3_4_5__windowstrides__1_1__paddin8362069580368565836.mlir
  stablehlo/testdata/conv_general_dilated_dimension_numbers_lhs_float32_2_3_9_10__rhs_float32_4_5_3_3__windowstrides__1_1-8327739261064575227.mlir
  stablehlo/testdata/conv_general_dilated_dimension_numbers_lhs_float32_2_9_10_3__rhs_float32_4_5_3_3__windowstrides__1_1-6479296361709234045.mlir
  stablehlo/testdata/conv_general_dilated_dtype_precision_lhs_float32_2_3_9_10__rhs_float32_3_3_4_5__windowstrides__1_1__-1572008590406220780.mlir
  stablehlo/testdata/conv_general_dilated_dtype_precision_lhs_float32_2_3_9_10__rhs_float32_3_3_4_5__windowstrides__1_1__-4848375839726769119.mlir
  stablehlo/testdata/conv_general_dilated_dtype_precision_lhs_float32_2_3_9_10__rhs_float32_3_3_4_5__windowstrides__1_1__-6463715315589295392.mlir
  stablehlo/testdata/conv_general_dilated_dtype_precision_lhs_float32_2_3_9_10__rhs_float32_3_3_4_5__windowstrides__1_1__-7128650963837464321.mlir
  stablehlo/testdata/conv_general_dilated_group_counts_lhs_float32_2_6_9_10__rhs_float32_6_3_4_5__windowstrides__1_1__pad-2212136815070163245.mlir
  stablehlo/testdata/conv_general_dilated_group_counts_lhs_float32_4_3_9_10__rhs_float32_6_3_4_5__windowstrides__1_1__pad2141518546713332984.mlir
  stablehlo/testdata/conv_general_dilated_padding_lhs_float32_2_3_9_10__rhs_float32_3_3_4_5__windowstrides__1_1__padding_-5318452038191342786.mlir
  stablehlo/testdata/conv_general_dilated_padding_lhs_float32_2_3_9_10__rhs_float32_3_3_4_5__windowstrides__1_1__padding_5050050053143756869.mlir
  stablehlo/testdata/conv_general_dilated_preferred_lhs_float32_2_3_9_10__rhs_float32_3_3_4_5__windowstrides__1_1__paddin-8230831430534381289.mlir
  stablehlo/testdata/conv_general_dilated_preferred_lhs_float32_2_3_9_10__rhs_float32_3_3_4_5__windowstrides__1_1__paddin2430556623423240398.mlir
  stablehlo/testdata/conv_general_dilated_preferred_lhs_int32_2_3_9_10__rhs_int32_3_3_4_5__windowstrides__1_1__padding___-7077764382968112509.mlir
  stablehlo/testdata/conv_general_dilated_preferred_lhs_int32_2_3_9_10__rhs_int32_3_3_4_5__windowstrides__1_1__padding___8425439145703732762.mlir
  stablehlo/testdata/conv_general_dilated_rhs_oob_after_dilation_lhs_float32_2_3_9_10__rhs_float32_3_3_4_5__windowstrides2604570134889024577.mlir
  stablehlo/testdata/conv_general_dilated_rhs_oob_after_pading_lhs_float32_1_3_2_2__rhs_float32_64_3_7_7__windowstrides__5476883256254674781.mlir
  stablehlo/testdata/conv_general_dilated_rhs_oob_lhs_float32_2_3_9_10__rhs_float32_3_3_10_5__windowstrides__1_1__padding-7028470013130116023.mlir
  stablehlo/testdata/conv_general_dilated_rhs_oob_same_padding_lhs_float32_1_1_16_1__rhs_float32_4_1_1_2__windowstrides__-5378230060959849233.mlir
  stablehlo/testdata/conv_general_dilated_tf_conversion_path_1d_lhs_float32_1_28_1__rhs_float32_3_1_16__windowstrides__1_-3327288011231887622.mlir
  stablehlo/testdata/conv_general_dilated_tf_conversion_path_1d_lhs_float32_1_28_1__rhs_float32_3_1_16__windowstrides__1_-3622729120410096886.mlir
  stablehlo/testdata/conv_general_dilated_tf_conversion_path_1d_lhs_float32_1_28_1__rhs_float32_3_1_16__windowstrides__1_-6986955039250405512.mlir
  stablehlo/testdata/conv_general_dilated_tf_conversion_path_1d_lhs_float32_1_28_1__rhs_float32_3_1_16__windowstrides__1_-9029857704645127306.mlir
  stablehlo/testdata/conv_general_dilated_tf_conversion_path_2d_lhs_float32_1_1_28_28__rhs_float32_3_3_1_16__windowstride-2949258448720886117.mlir
  stablehlo/testdata/conv_general_dilated_tf_conversion_path_2d_lhs_float32_1_1_28_28__rhs_float32_3_3_1_16__windowstride-3150713558304940791.mlir
  stablehlo/testdata/conv_general_dilated_tf_conversion_path_2d_lhs_float32_1_1_28_28__rhs_float32_3_3_1_16__windowstride-4268834939663085007.mlir
  stablehlo/testdata/conv_general_dilated_tf_conversion_path_2d_lhs_float32_1_1_28_28__rhs_float32_3_3_1_16__windowstride-4823547473556881342.mlir
  stablehlo/testdata/conv_general_dilated_tf_conversion_path_2d_lhs_float32_1_1_28_28__rhs_float32_3_3_1_16__windowstride6887804375295982821.mlir
  stablehlo/testdata/conv_general_dilated_tf_conversion_path_2d_lhs_float32_1_28_28_1__rhs_float32_3_3_1_16__windowstride-5370080226275098061.mlir
  stablehlo/testdata/conv_general_dilated_tf_conversion_path_2d_lhs_float32_1_28_28_1__rhs_float32_3_3_1_16__windowstride3500806609840728678.mlir
  stablehlo/testdata/conv_general_dilated_tf_conversion_path_2d_lhs_float32_1_28_28_1__rhs_float32_3_3_1_16__windowstride5787494791845602941.mlir
  stablehlo/testdata/conv_general_dilated_tf_conversion_path_2d_lhs_float32_1_28_28_1__rhs_float32_3_3_1_16__windowstride6312536791243051545.mlir
  stablehlo/testdata/conv_general_dilated_tf_conversion_path_2d_lhs_float32_1_28_28_1__rhs_float32_3_3_1_16__windowstride8472832706066243053.mlir
  stablehlo/testdata/conv_general_dilated_tf_conversion_path_3d_lhs_float32_1_4_28_28_1__rhs_float32_2_3_3_1_16__windowst-8282934958224398022.mlir
  stablehlo/testdata/conv_general_dilated_tf_conversion_path_3d_lhs_float32_1_4_28_28_1__rhs_float32_2_3_3_1_16__windowst3167308923230843499.mlir
  stablehlo/testdata/conv_general_dilated_tf_conversion_path_3d_lhs_float32_1_4_28_28_1__rhs_float32_2_3_3_1_16__windowst6072174321640638276.mlir
  stablehlo/testdata/conv_general_dilated_tf_conversion_path_3d_lhs_float32_1_4_28_28_1__rhs_float32_2_3_3_1_16__windowst8524424959485066052.mlir
  stablehlo/testdata/conv_general_dilated_window_strides_lhs_float32_2_3_9_10__rhs_float32_3_3_4_5__windowstrides__2_3__p-3051008093469972974.mlir
Labels: Interpreter

#2240 Add compile_commands flag to README
  README.md
Labels: Build, Documentation

#2245 Rename variables to simplify refactoring
  stablehlo/reference/Ops.cpp
Labels: Interpreter, Cleanup/Refactoring

#2246 Remove "eval" prefix from ops
  stablehlo/reference/Ops.cpp
  stablehlo/reference/Ops.h
Labels: Interpreter, Cleanup/Refactoring

#2247 Integrate LLVM at llvm/llvm-project@2a47ee070145
  WORKSPACE.bazel
  build_tools/llvm_version.txt
Labels: Integrations

#2239 Update conv docs and tests per interpreter guideline
  stablehlo/dialect/StablehloOps.td
  stablehlo/dialect/TypeInference.cpp
  stablehlo/tests/infer_stablehlo.mlir
  stablehlo/tests/ops_stablehlo.mlir
  stablehlo/tests/verify_conv.mlir
Labels: Verification, Type inference

#2158 Add a note at type_inference.md for adding custom verifier if return type inference is not feasible
  docs/type_inference.md
Labels: Verification

#2249 Make TF tests optional in python CI build script.
  .github/workflows/buildAndTestCMake.yml
  .github/workflows/publishWheelRelease.yml
  CMakeLists.txt
  build_tools/github_actions/ci_build_cmake.sh
  stablehlo/integrations/python/tests/CMakeLists.txt
Labels: Integrations, Build

#2250 Add StableHLO to SavedModel Tutorial
  docs/_toc.yaml
  docs/tutorials/savedmodel-embed.ipynb
Labels: Integrations, Documentation

#2256 Fix link in JAX tutorial
  docs/tutorials/jax-export.ipynb
Labels: Documentation

#2257 Update PyTorch example to support 2.3.0
  docs/tutorials/pytorch-export.ipynb
Labels: Documentation

#2251 Include command to build StableHLO with python bindings
  README.md
Labels: Build, Documentation
