Repository openxla/stablehlo, pull requests merged in 2024-03, with the labels that each got.

#2064 Add shape refinement pass for DotOp
  stablehlo/dialect/StablehloOps.cpp
  stablehlo/dialect/TypeInference.cpp
  stablehlo/dialect/TypeInference.h
  stablehlo/tests/stablehlo_refine_shapes.mlir
  stablehlo/transforms/StablehloRefineShapes.cpp
Labels: Dynamism

#2089 Fix typo in `ide.md`
  docs/ide.md
Labels: Cleanup/Refactoring

#1883 Extensibility RFC
  rfcs/20230609-extensibility.md
Labels: RFC

#2062 Add a python API for reference interpreter
  BUILD.bazel
  stablehlo/integrations/python/CMakeLists.txt
  stablehlo/integrations/python/StablehloModule.cpp
  stablehlo/integrations/python/tests/stablehlo.py
  stablehlo/reference/Api.cpp
  stablehlo/reference/Api.h
  stablehlo/reference/CMakeLists.txt
  stablehlo/reference/Tensor.cpp
  stablehlo/reference/Tensor.h
  stablehlo/tools/StablehloTranslateMain.cpp
Labels: Interpreter, Integrations

#2110 Fix indentation
  CMakePresets.json
Labels: Integrations

#2117 Fix formatting on spec examples
  docs/spec.md
  stablehlo/dialect/StablehloOps.td
Labels: Cleanup/Refactoring

#2119 Clean up hasRank checks
  stablehlo/conversions/linalg/transforms/LegalizeToLinalgUtils.cpp
  stablehlo/conversions/linalg/transforms/StablehloLegalizeToLinalg.cpp
  stablehlo/conversions/linalg/transforms/StablehloToLinalgPointwise.cpp
  stablehlo/conversions/tosa/transforms/StablehloLegalizeToTosa.pdll
  stablehlo/dialect/Base.cpp
  stablehlo/dialect/StablehloOps.cpp
  stablehlo/dialect/TypeInference.cpp
  stablehlo/tests/ops_stablehlo.mlir
  stablehlo/tests/verify_reduce.mlir
  stablehlo/transforms/StablehloRefineShapes.cpp
Labels: Cleanup/Refactoring

#2124 Integrate LLVM at llvm/llvm-project@7ac7d418ac2b
  BUILD.bazel
  WORKSPACE.bazel
  build_tools/llvm_version.txt
Labels: Integrations

#2126 Add terminating newline
  examples/python/stablehlo_add.py
Labels: Cleanup/Refactoring

#2050 Execution semantics of Stablehlo quantized operations
  docs/spec.md
Labels: Spec

#2128 Fix typo in error message
  stablehlo/dialect/TypeInference.cpp
Labels: Cleanup/Refactoring

#2131 Update `BUILD.bazel` target name
  examples/c++/BUILD.bazel
Labels: Cleanup/Refactoring

#2133 Bump patch version after integrate 0.19.3 -> 0.19.4
  stablehlo/dialect/Version.h
Labels: Integrations

#2134 Integrate LLVM at llvm/llvm-project@3cf169ca160e
  WORKSPACE.bazel
  build_tools/llvm_version.txt
Labels: Integrations

#2137 Bump patch version after integrate 0.19.4 -> 0.19.5
  stablehlo/dialect/Version.h
Labels: Integrations

#2140 Remove `RankedTensorType` verification check for `TriangularSolveOp`
  stablehlo/dialect/TypeInference.cpp
Labels: Verification, Dynamism

#2141 Remove `RankedTensorType` verification check for `CholeskyOp`
  stablehlo/dialect/TypeInference.cpp
Labels: Verification, Dynamism

#2136 Add spec warning about shape mismatches
  docs/spec.md
Labels: Spec

#2127 AddOp: Remove HLO_CompatibleOperandsAndResultType Trait, add custom verifier
  stablehlo/dialect/StablehloOps.cpp
  stablehlo/dialect/StablehloOps.td
  stablehlo/dialect/TypeInference.cpp
  stablehlo/dialect/TypeInference.h
  stablehlo/tests/infer_stablehlo.mlir
  stablehlo/tests/ops_stablehlo.mlir
  stablehlo/tests/print_types_invalid.mlir
  stablehlo/tests/stablehlo_refine_shapes.mlir
Labels: Verification, Migrate to MHLO

#2112 Add SameOperandsAndResultElementType Trait for type(operand) = type (result) ops
  stablehlo/dialect/StablehloOps.td
Labels: Verification, Migrate to MHLO
