Repository openxla/stablehlo, pull requests merged in 2024-08, with the labels that each got.

#2480 Minor spec fix : correct variadic result notation for all_gather and all_reduce ops
  docs/spec.md
Labels: Cleanup/Refactoring

#2481 Collectives Ops : Match example from the StableHLO op description comment with example from the spec
  docs/spec.md
  stablehlo/dialect/StablehloOps.td
Labels: Cleanup/Refactoring

#2490 Integrate LLVM at llvm/llvm-project@4c5ef6690040
  WORKSPACE.bazel
  build_tools/llvm_version.txt
Labels: Integrations

#2478 New StablehloLegalizeQDQToQuantizedOpPass
  BUILD.bazel
  docs/generated/stablehlo_passes.md
  stablehlo/tests/transforms/stablehlo_legalize_qdq_to_quantized_op.mlir
  stablehlo/transforms/CMakeLists.txt
  stablehlo/transforms/Passes.h
  stablehlo/transforms/Passes.td
  stablehlo/transforms/StablehloLegalizeQDQToQuantizedOp.cpp
Labels: Transformations

#2467 Implement Dot Algorithms RFC
  docs/spec.md
  stablehlo/conversions/linalg/tests/dot-product.mlir
  stablehlo/conversions/linalg/transforms/StablehloToLinalgDotProduct.cpp
  stablehlo/dialect/StablehloAttrs.td
  stablehlo/dialect/StablehloBytecode.cpp
  stablehlo/dialect/StablehloEnums.td
  stablehlo/dialect/StablehloOps.cpp
  stablehlo/dialect/StablehloOps.td
  stablehlo/dialect/TypeInference.cpp
  stablehlo/dialect/TypeInference.h
  stablehlo/reference/Ops.cpp
  stablehlo/tests/interpret/dot_general.mlir
  stablehlo/tests/ops_stablehlo.mlir
  stablehlo/transforms/StablehloLegalizeDeprecatedOpsPatterns.td
Labels: Spec, RFC

#2503 DotGeneralOp interpreter updates
  stablehlo/reference/Element.cpp
  stablehlo/reference/Element.h
  stablehlo/reference/Ops.cpp
Labels: Interpreter

#2498 Integrate LLVM at llvm/llvm-project@f9031f00f2c9
  WORKSPACE.bazel
  build_tools/llvm_version.txt
Labels: Integrations

#2506 Add a test for non quantized type (DotGeneralOp mismatched operand and result types scenario)
  stablehlo/tests/interpret/dot_general.mlir
Labels: Interpreter

#2502 Quantized Test Data files : GatherOp
  stablehlo/testdata/quantized/gather_batchdims_shape__1__2__start_indices_shape__1__2__slice_sizes__1__1__enable_xla_True_qi8.mlir
  stablehlo/testdata/quantized/gather_batchdims_shape__2__3__3__start_indices_shape__2__3__slice_sizes__1__3__2__enable_xla_True_qi8.mlir
  stablehlo/testdata/quantized/gather_batchdims_shape__2__6__3__start_indices_shape__2__3__slice_sizes__1__3__3__enable_xla_True_qi8.mlir
  stablehlo/testdata/quantized/gather_batchdims_shape__3__10__start_indices_shape__3__2__slice_sizes__1__5__enable_xla_True_qi8.mlir
  stablehlo/testdata/quantized/gather_batchdims_shape__4__6__start_indices_shape__4__2__slice_sizes__1__3__enable_xla_True_qi8.mlir
  stablehlo/testdata/quantized/gather_from_slicing_name___0_1___enable_xla_True_qi8.mlir
  stablehlo/testdata/quantized/gather_from_slicing_name___0___enable_xla_True_qi8.mlir
  stablehlo/testdata/quantized/gather_from_slicing_name___2_5_5___enable_xla_True_qi8.mlir
  stablehlo/testdata/quantized/gather_from_slicing_name___5_-2_300___enable_xla_True_qi8.mlir
  stablehlo/testdata/quantized/gather_from_slicing_name______2_____enable_xla_True_qi8.mlir
  stablehlo/testdata/quantized/gather_from_take_indices_name__1__axis_0_enable_xla_True_mode_clip_qi8.mlir
  stablehlo/testdata/quantized/gather_from_take_indices_name__1__axis_1_enable_xla_True_mode_clip_qi8.mlir
  stablehlo/testdata/quantized/gather_from_take_indices_name__1__axis_2_enable_xla_True_mode_clip_qi8.mlir
  stablehlo/testdata/quantized/gather_from_take_indices_name__2__axis_0_enable_xla_True_mode_clip_qi8.mlir
  stablehlo/testdata/quantized/gather_from_take_indices_name__2__axis_1_enable_xla_True_mode_clip_qi8.mlir
  stablehlo/testdata/quantized/gather_from_take_indices_name__2__axis_2_enable_xla_True_mode_clip_qi8.mlir
  stablehlo/testdata/quantized/gather_from_take_indices_name__3__axis_0_enable_xla_True_mode_clip_qi8.mlir
  stablehlo/testdata/quantized/gather_from_take_indices_name__3__axis_1_enable_xla_True_mode_clip_qi8.mlir
  stablehlo/testdata/quantized/gather_from_take_indices_name__3__axis_2_enable_xla_True_mode_clip_qi8.mlir
  stablehlo/testdata/quantized/gather_from_take_indices_name__4__axis_0_enable_xla_True_mode_clip_qi8.mlir
  stablehlo/testdata/quantized/gather_from_take_indices_name__4__axis_1_enable_xla_True_mode_clip_qi8.mlir
  stablehlo/testdata/quantized/gather_from_take_indices_name__4__axis_2_enable_xla_True_mode_clip_qi8.mlir
  stablehlo/testdata/quantized/gather_from_take_indices_name__5_oob__axis_0_enable_xla_True_mode_clip_qi8.mlir
  stablehlo/testdata/quantized/gather_from_take_indices_name__5_oob__axis_1_enable_xla_True_mode_clip_qi8.mlir
  stablehlo/testdata/quantized/gather_from_take_indices_name__5_oob__axis_2_enable_xla_True_mode_clip_qi8.mlir
  stablehlo/testdata/quantized/gather_from_take_indices_name__6_neg__axis_0_enable_xla_True_mode_clip_qi8.mlir
  stablehlo/testdata/quantized/gather_from_take_indices_name__6_neg__axis_1_enable_xla_True_mode_clip_qi8.mlir
  stablehlo/testdata/quantized/gather_from_take_indices_name__6_neg__axis_2_enable_xla_True_mode_clip_qi8.mlir
  stablehlo/testdata/quantized/gather_from_take_indices_name__7_neg__axis_0_enable_xla_True_mode_clip_qi8.mlir
  stablehlo/testdata/quantized/gather_from_take_indices_name__7_neg__axis_1_enable_xla_True_mode_clip_qi8.mlir
  stablehlo/testdata/quantized/gather_from_take_indices_name__7_neg__axis_2_enable_xla_True_mode_clip_qi8.mlir
  stablehlo/testdata/quantized/gather_from_take_indices_name__8_neg_oob__axis_0_enable_xla_True_mode_clip_qi8.mlir
  stablehlo/testdata/quantized/gather_from_take_indices_name__8_neg_oob__axis_1_enable_xla_True_mode_clip_qi8.mlir
  stablehlo/testdata/quantized/gather_from_take_indices_name__8_neg_oob__axis_2_enable_xla_True_mode_clip_qi8.mlir
  stablehlo/testdata/quantized/gather_qi8.mlir
  stablehlo/testdata/quantized/gather_shape__10__5__idxs_shape__3__1__dnums_GatherDimensionNumbers_offset_dims__1____collapsed_slic5975718671559903784_qi8.mlir
  stablehlo/testdata/quantized/gather_shape__10__6__idxs_shape__2__2__dnums_GatherDimensionNumbers_offset_dims__1____collapsed_slic-7762956558939593001_qi8.mlir
  stablehlo/testdata/quantized/gather_shape__10___idxs_shape__3__1__dnums_GatherDimensionNumbers_offset_dims__1____collapsed_slice_-4284776541264791777_qi8.mlir
  stablehlo/testdata/quantized/gather_shape__5___idxs_shape__2__1__dnums_GatherDimensionNumbers_offset_dims_____collapsed_slice_dim-7698694031974320657_qi8.mlir
Labels: Quantization

#2499 Quantized Test Data files : ConvolutionOp
  stablehlo/testdata/quantized/conv_general_dilated_conv1d_lhs_float32_2_3_10__rhs_float32_3_3_5__windowstrides__1___padding___0_0_3336387849681708224_qi8.mlir
  stablehlo/testdata/quantized/conv_general_dilated_conv_tranpose1d_same_padding_lhs_float32_1_16_2__rhs_float32_3_2_2__windowstrid-2801039169040378295_qi8.mlir
  stablehlo/testdata/quantized/conv_general_dilated_conv_tranpose1d_valid_padding_lhs_float32_1_16_2__rhs_float32_3_2_2__windowstri-8415303397313720110_qi8.mlir
  stablehlo/testdata/quantized/conv_general_dilated_conv_tranpose2d_same_padding_lhs_float32_1_16_16_2__rhs_float32_2_3_2_2__window-296817466026258822_qi8.mlir
  stablehlo/testdata/quantized/conv_general_dilated_conv_tranpose2d_valid_padding_lhs_float32_1_16_16_2__rhs_float32_2_3_2_2__windo216554503587864094_qi8.mlir
  stablehlo/testdata/quantized/conv_general_dilated_depthwise1d_dilated_lhs_float32_2_3_9__rhs_float32_12_1_3__windowstrides__1___p4726467912149865720_qi8.mlir
  stablehlo/testdata/quantized/conv_general_dilated_depthwise1d_lhs_float32_2_3_9__rhs_float32_12_1_3__windowstrides__1___padding__2025442285785167829_qi8.mlir
  stablehlo/testdata/quantized/conv_general_dilated_depthwise2d_dilated_lhs_float32_2_3_9_9__rhs_float32_12_1_3_3__windowstrides__1-5299255563318388077_qi8.mlir
  stablehlo/testdata/quantized/conv_general_dilated_depthwise2d_lhs_float32_2_3_9_9__rhs_float32_12_1_3_3__windowstrides__1_1__padd-5494580149111736437_qi8.mlir
  stablehlo/testdata/quantized/conv_general_dilated_dilations_lhs_float32_2_3_9_10__rhs_float32_3_3_4_5__windowstrides__1_1__paddin-940783895638600378_qi8.mlir
  stablehlo/testdata/quantized/conv_general_dilated_dilations_lhs_float32_2_3_9_10__rhs_float32_3_3_4_5__windowstrides__1_1__paddin7803468828575064957_qi8.mlir
  stablehlo/testdata/quantized/conv_general_dilated_dilations_lhs_float32_2_3_9_10__rhs_float32_3_3_4_5__windowstrides__1_1__paddin8362069580368565836_qi8.mlir
  stablehlo/testdata/quantized/conv_general_dilated_dimension_numbers_lhs_float32_2_3_9_10__rhs_float32_4_5_3_3__windowstrides__1_1-8327739261064575227_qi8.mlir
  stablehlo/testdata/quantized/conv_general_dilated_dimension_numbers_lhs_float32_2_9_10_3__rhs_float32_4_5_3_3__windowstrides__1_1-6479296361709234045_qi8.mlir
  stablehlo/testdata/quantized/conv_general_dilated_dtype_precision_lhs_float32_2_3_9_10__rhs_float32_3_3_4_5__windowstrides__1_1__-1572008590406220780_qi8.mlir
  stablehlo/testdata/quantized/conv_general_dilated_dtype_precision_lhs_float32_2_3_9_10__rhs_float32_3_3_4_5__windowstrides__1_1__-4848375839726769119_qi8.mlir
  stablehlo/testdata/quantized/conv_general_dilated_dtype_precision_lhs_float32_2_3_9_10__rhs_float32_3_3_4_5__windowstrides__1_1__-6463715315589295392_qi8.mlir
  stablehlo/testdata/quantized/conv_general_dilated_dtype_precision_lhs_float32_2_3_9_10__rhs_float32_3_3_4_5__windowstrides__1_1__-7128650963837464321_qi8.mlir
  stablehlo/testdata/quantized/conv_general_dilated_group_counts_lhs_float32_2_6_9_10__rhs_float32_6_3_4_5__windowstrides__1_1__pad-2212136815070163245_qi8.mlir
  stablehlo/testdata/quantized/conv_general_dilated_group_counts_lhs_float32_4_3_9_10__rhs_float32_6_3_4_5__windowstrides__1_1__pad2141518546713332984_qi8.mlir
  stablehlo/testdata/quantized/conv_general_dilated_padding_lhs_float32_2_3_9_10__rhs_float32_3_3_4_5__windowstrides__1_1__padding_-5318452038191342786_qi8.mlir
  stablehlo/testdata/quantized/conv_general_dilated_padding_lhs_float32_2_3_9_10__rhs_float32_3_3_4_5__windowstrides__1_1__padding_5050050053143756869_qi8.mlir
  stablehlo/testdata/quantized/conv_general_dilated_preferred_lhs_float32_2_3_9_10__rhs_float32_3_3_4_5__windowstrides__1_1__paddin-8230831430534381289_qi8.mlir
  stablehlo/testdata/quantized/conv_general_dilated_preferred_lhs_float32_2_3_9_10__rhs_float32_3_3_4_5__windowstrides__1_1__paddin2430556623423240398_qi8.mlir
  stablehlo/testdata/quantized/conv_general_dilated_rhs_oob_after_pading_lhs_float32_1_3_2_2__rhs_float32_64_3_7_7__windowstrides__5476883256254674781_qi8.mlir
  stablehlo/testdata/quantized/conv_general_dilated_rhs_oob_same_padding_lhs_float32_1_1_16_1__rhs_float32_4_1_1_2__windowstrides__-5378230060959849233_qi8.mlir
  stablehlo/testdata/quantized/conv_general_dilated_tf_conversion_path_1d_lhs_float32_1_28_1__rhs_float32_3_1_16__windowstrides__1_-3327288011231887622_qi8.mlir
  stablehlo/testdata/quantized/conv_general_dilated_tf_conversion_path_1d_lhs_float32_1_28_1__rhs_float32_3_1_16__windowstrides__1_-3622729120410096886_qi8.mlir
  stablehlo/testdata/quantized/conv_general_dilated_tf_conversion_path_1d_lhs_float32_1_28_1__rhs_float32_3_1_16__windowstrides__1_-6986955039250405512_qi8.mlir
  stablehlo/testdata/quantized/conv_general_dilated_tf_conversion_path_1d_lhs_float32_1_28_1__rhs_float32_3_1_16__windowstrides__1_-9029857704645127306_qi8.mlir
  stablehlo/testdata/quantized/conv_general_dilated_tf_conversion_path_2d_lhs_float32_1_1_28_28__rhs_float32_3_3_1_16__windowstride-2949258448720886117_qi8.mlir
  stablehlo/testdata/quantized/conv_general_dilated_tf_conversion_path_2d_lhs_float32_1_1_28_28__rhs_float32_3_3_1_16__windowstride-3150713558304940791_qi8.mlir
  stablehlo/testdata/quantized/conv_general_dilated_tf_conversion_path_2d_lhs_float32_1_1_28_28__rhs_float32_3_3_1_16__windowstride-4268834939663085007_qi8.mlir
  stablehlo/testdata/quantized/conv_general_dilated_tf_conversion_path_2d_lhs_float32_1_1_28_28__rhs_float32_3_3_1_16__windowstride-4823547473556881342_qi8.mlir
  stablehlo/testdata/quantized/conv_general_dilated_tf_conversion_path_2d_lhs_float32_1_1_28_28__rhs_float32_3_3_1_16__windowstride6887804375295982821_qi8.mlir
  stablehlo/testdata/quantized/conv_general_dilated_tf_conversion_path_2d_lhs_float32_1_28_28_1__rhs_float32_3_3_1_16__windowstride-5370080226275098061_qi8.mlir
  stablehlo/testdata/quantized/conv_general_dilated_tf_conversion_path_2d_lhs_float32_1_28_28_1__rhs_float32_3_3_1_16__windowstride3500806609840728678_qi8.mlir
  stablehlo/testdata/quantized/conv_general_dilated_tf_conversion_path_2d_lhs_float32_1_28_28_1__rhs_float32_3_3_1_16__windowstride5787494791845602941_qi8.mlir
  stablehlo/testdata/quantized/conv_general_dilated_tf_conversion_path_2d_lhs_float32_1_28_28_1__rhs_float32_3_3_1_16__windowstride6312536791243051545_qi8.mlir
  stablehlo/testdata/quantized/conv_general_dilated_tf_conversion_path_2d_lhs_float32_1_28_28_1__rhs_float32_3_3_1_16__windowstride8472832706066243053_qi8.mlir
  stablehlo/testdata/quantized/conv_general_dilated_tf_conversion_path_3d_lhs_float32_1_4_28_28_1__rhs_float32_2_3_3_1_16__windowst-8282934958224398022_qi8.mlir
  stablehlo/testdata/quantized/conv_general_dilated_tf_conversion_path_3d_lhs_float32_1_4_28_28_1__rhs_float32_2_3_3_1_16__windowst8524424959485066052_qi8.mlir
  stablehlo/testdata/quantized/conv_general_dilated_window_strides_lhs_float32_2_3_9_10__rhs_float32_3_3_4_5__windowstrides__2_3__p-3051008093469972974_qi8.mlir
Labels: Quantization

#2500 Quantized Test Data files : DotGeneralOp
  stablehlo/testdata/quantized/convolution_qi8.mlir
  stablehlo/testdata/quantized/dot_general_batch_dimensions_lhs_float32_8_4_3_3_4__rhs_float32_4_8_3_4_2__dimensionnumbers____4_3___3_2_____0_1___1_0_qi8.mlir
  stablehlo/testdata/quantized/dot_general_dtypes_and_precision_lhs_float32_1_3_4__rhs_float32_1_4_3__dimensionnumbers____2_1___1_2-3746161505671304111_qi8.mlir
  stablehlo/testdata/quantized/dot_general_dtypes_and_precision_lhs_float32_1_3_4__rhs_float32_1_4_3__dimensionnumbers____2_1___1_2-601699960869302464_qi8.mlir
  stablehlo/testdata/quantized/dot_general_dtypes_and_precision_lhs_float32_1_3_4__rhs_float32_1_4_3__dimensionnumbers____2_1___1_26892231390636518787_qi8.mlir
  stablehlo/testdata/quantized/dot_general_dtypes_and_precision_lhs_float32_1_3_4__rhs_float32_1_4_3__dimensionnumbers____2_1___1_2_____0____0_qi8.mlir
Labels: Quantization

#2509 Bump patch version after integrate 1.6.1 -> 1.6.2
  stablehlo/dialect/Version.h
Labels: Integrations

#2510 Integrate LLVM at llvm/llvm-project@65281570afd7
  WORKSPACE.bazel
  build_tools/llvm_version.txt
Labels: Integrations

#2514 Move python bindings to portable apis that use C-API datatypes.
  build_tools/math/generate_ChloDecompositionPatternsMath.py
  stablehlo/conversions/tosa/tests/lit.cfg.py
  stablehlo/integrations/python/StablehloApi.cpp
  stablehlo/integrations/python/tests/stablehlo.py
Labels: Integrations

#2515 Bump patch version after integrate 1.6.2 -> 1.6.3
  stablehlo/dialect/Version.h
Labels: Integrations

#2516 Integrate LLVM at llvm/llvm-project@f142f8afe21b
  WORKSPACE.bazel
  build_tools/llvm_version.txt
Labels: Integrations

#2518 Add StableHLOCreateCompatibilityExpanderPass
  BUILD.bazel
  docs/generated/stablehlo_passes.md
  stablehlo/tests/transforms/stablehlo_create_compatibility_expander.mlir
  stablehlo/transforms/CMakeLists.txt
  stablehlo/transforms/Passes.h
  stablehlo/transforms/Passes.td
  stablehlo/transforms/StablehloCreateCompatibilityExpander.cpp
  stablehlo/transforms/StablehloCreateCompatibilityExpanderPatterns.td
Labels: Transformations

#2517 Remove deprecated serialization APIs
  stablehlo/integrations/python/StablehloApi.cpp
Labels: Integrations

#2519 Bump patch version after integrate 1.6.3 -> 1.6.4
  stablehlo/dialect/Version.h
Labels: Integrations
