Repository openxla/stablehlo, pull requests merged in 2024-05, with the labels that each got.

#2273 Fix formatting for spec table
  docs/spec.md
Labels: Cleanup/Refactoring

#2234 Fix the bitness of addition/subtraction in quantize op
  docs/spec.md
Labels: Quantization

#1882 [RFC] Increase StableHLO Compatibility Guarantees
  rfcs/20230623-compatibility.md
Labels: RFC

#2272 iota op spec : replace "result_index" with "output_index"
  docs/spec.md
Labels: Cleanup/Refactoring

#2277 Bump patch version after integrate 0.19.9 -> 0.19.10
  stablehlo/dialect/Version.h
Labels: Integrations

#2266 Integrate LLVM at llvm/llvm-project@2914a11e3fad
  WORKSPACE.bazel
  build_tools/llvm_version.txt
Labels: Integrations

#2275 Interpreter support for dynamic programs
  BUILD.bazel
  stablehlo/integrations/python/tests/stablehlo.py
  stablehlo/reference/Api.cpp
  stablehlo/reference/CMakeLists.txt
  stablehlo/transforms/PassPipelines.cpp
  stablehlo/transforms/Passes.h
Labels: Interpreter, Dynamism

#2203 Verify StableHLO Quantized Types
  BUILD.bazel
  docs/spec.md
  stablehlo/dialect/Base.cpp
  stablehlo/dialect/Base.h
  stablehlo/dialect/Base.td
  stablehlo/dialect/TypeInference.cpp
  stablehlo/reference/CMakeLists.txt
  stablehlo/reference/InterpreterOps.cpp
  stablehlo/tests/BUILD.bazel
  stablehlo/tests/CMakeLists.txt
  stablehlo/tests/CheckOps.cpp
  stablehlo/tests/ops_stablehlo.mlir
  stablehlo/tests/ops_stablehlo_quantized.mlir
  stablehlo/tests/verify_reduce.mlir
  stablehlo/tests/verify_reduce_window.mlir
  stablehlo/tests/verify_scatter.mlir
  stablehlo/tests/verify_select_and_scatter.mlir
Labels: Verification, Quantization

#2270 dynamic_iota op spec
  docs/spec.md
  docs/status.md
  stablehlo/dialect/StablehloOps.td
  stablehlo/dialect/TypeInference.cpp
  stablehlo/reference/Ops.cpp
  stablehlo/reference/Ops.h
  stablehlo/tests/interpret/dynamic_iota.mlir
Labels: Spec, Interpreter

#2300 Update table formatting and fix typos
  docs/spec.md
Labels: Cleanup/Refactoring

#2284 dynamic_reshape op spec
  docs/spec.md
  docs/status.md
  stablehlo/dialect/StablehloOps.td
  stablehlo/dialect/TypeInference.cpp
  stablehlo/reference/Ops.cpp
  stablehlo/reference/Ops.h
  stablehlo/tests/interpret/dynamic_reshape.mlir
  stablehlo/tests/ops_stablehlo.mlir
  stablehlo/tests/ops_stablehlo_quantized.mlir
Labels: Spec, Verification, Type inference, Interpreter

#2299 Add link to StableHLO page on official OpenXLA website
  README.md
Labels: Documentation

#2295 Remove TraceOp from StableHLO
  docs/interpreter_status.md
  docs/spec.md
  docs/status.md
  stablehlo/dialect/StablehloOps.td
  stablehlo/dialect/VhloOps.td
  stablehlo/reference/Ops.cpp
  stablehlo/tests/print_stablehlo.mlir
  stablehlo/tests/vhlo/stablehlo_legalize_to_vhlo.0_10_0.mlir
  stablehlo/tests/vhlo/stablehlo_legalize_to_vhlo.0_10_0.mlir.bc
  stablehlo/tests/vhlo/stablehlo_legalize_to_vhlo.0_11_0.mlir
  stablehlo/tests/vhlo/stablehlo_legalize_to_vhlo.0_11_0.mlir.bc
  stablehlo/tests/vhlo/stablehlo_legalize_to_vhlo.0_12_0.mlir
  stablehlo/tests/vhlo/stablehlo_legalize_to_vhlo.0_12_0.mlir.bc
  stablehlo/tests/vhlo/stablehlo_legalize_to_vhlo.0_13_0.mlir
  stablehlo/tests/vhlo/stablehlo_legalize_to_vhlo.0_13_0.mlir.bc
  stablehlo/tests/vhlo/stablehlo_legalize_to_vhlo.0_14_0.mlir
  stablehlo/tests/vhlo/stablehlo_legalize_to_vhlo.0_14_0.mlir.bc
  stablehlo/tests/vhlo/stablehlo_legalize_to_vhlo.0_15_0.mlir
  stablehlo/tests/vhlo/stablehlo_legalize_to_vhlo.0_15_0.mlir.bc
  stablehlo/tests/vhlo/stablehlo_legalize_to_vhlo.0_16_0.mlir
  stablehlo/tests/vhlo/stablehlo_legalize_to_vhlo.0_16_0.mlir.bc
  stablehlo/tests/vhlo/stablehlo_legalize_to_vhlo.0_17_0.mlir
  stablehlo/tests/vhlo/stablehlo_legalize_to_vhlo.0_17_0.mlir.bc
  stablehlo/tests/vhlo/stablehlo_legalize_to_vhlo.0_18_0.mlir
  stablehlo/tests/vhlo/stablehlo_legalize_to_vhlo.0_18_0.mlir.bc
  stablehlo/tests/vhlo/stablehlo_legalize_to_vhlo.0_19_0.mlir
  stablehlo/tests/vhlo/stablehlo_legalize_to_vhlo.0_19_0.mlir.bc
  stablehlo/tests/vhlo/stablehlo_legalize_to_vhlo.0_9_0.mlir
  stablehlo/tests/vhlo/stablehlo_legalize_to_vhlo.0_9_0.mlir.bc
  stablehlo/tests/vhlo/stablehlo_legalize_to_vhlo.mlir
  stablehlo/transforms/MapStablehloToVhlo.h
  stablehlo/transforms/StablehloInstrumentWithProbe.cpp
  stablehlo/transforms/StablehloLegalizeDeprecatedOps.cpp
Labels: Spec, Compatibility, Cleanup/Refactoring

#2309 Spec dynamic_gather
  docs/spec.md
  docs/status.md
  stablehlo/dialect/StablehloOps.td
  stablehlo/dialect/TypeInference.cpp
  stablehlo/reference/Ops.cpp
  stablehlo/tests/interpret/dynamic_gather.mlir
  stablehlo/tests/ops_stablehlo.mlir
Labels: Spec, Dynamism

#2320 dynamic_gather::slice_size cannot be of Index type
  stablehlo/dialect/Base.td
  stablehlo/dialect/StablehloOps.td
Labels: Spec, Dynamism

#2321 Fix typo on dynamic_gather
  docs/spec.md
  stablehlo/dialect/StablehloOps.td
  stablehlo/dialect/TypeInference.cpp
  stablehlo/tests/interpret/dynamic_gather.mlir
Labels: Cleanup/Refactoring

#2315 dynamic_broadcast_in_dim op spec
  docs/spec.md
  docs/status.md
  stablehlo/dialect/StablehloOps.td
  stablehlo/dialect/TypeInference.cpp
  stablehlo/reference/Ops.cpp
  stablehlo/tests/interpret/dynamic_broadcast_in_dim.mlir
  stablehlo/tests/ops_stablehlo.mlir
  stablehlo/tests/ops_stablehlo_quantized.mlir
Labels: Spec, Verification, Interpreter, Dynamism

#2331 Add vhlo version log for v0.20.0
  stablehlo/dialect/VhloDialect.td
Labels: Compatibility, Documentation

#2283 [RFC] StableHLO v1.0 Opset Deprecations & Cleanups
  docs/spec.md
  rfcs/20240503-opset-deprecations.md
Labels: RFC

#2334 Fix incorrect reference for DynamicGather spec
  docs/spec.md
  stablehlo/dialect/StablehloOps.td
Labels: Spec, Cleanup/Refactoring, Documentation

#2333 Add versioning note to spec
  README.md
  docs/spec.md
Labels: Spec, Compatibility

#2327 Address remaining feedbacks from #2312
  docs/spec.md
  docs/status.md
  stablehlo/dialect/Base.td
  stablehlo/dialect/StablehloOps.td
  stablehlo/dialect/VhloOps.td
  stablehlo/reference/Ops.cpp
  stablehlo/tests/interpret/convolution.mlir
  stablehlo/tests/interpret/dynamic_conv.mlir
  stablehlo/tests/verify_dynamic_conv.mlir
  stablehlo/transforms/StablehloLegalizeToVhlo.cpp
  stablehlo/transforms/VhloLegalizeToStablehlo.cpp
  stablehlo/transforms/VhloToVersion.cpp
  stablehlo/transforms/VhloToVersionPatterns.td
Labels: Spec, Prettyprinting, Cleanup/Refactoring

#2335 Inline `StableHLO_ConvolutionAttributes` to tablegen
  stablehlo/dialect/StablehloAttrs.td
  stablehlo/dialect/StablehloOps.td
Labels: Cleanup/Refactoring

#2339 Remove obsolete comments
  stablehlo/dialect/VhloOps.td
Labels: Cleanup/Refactoring

#2338 Integrate LLVM at llvm/llvm-project@a6d7828f4c50
  WORKSPACE.bazel
  build_tools/llvm_version.txt
Labels: Integrations

#2342 Add StableHLO v1.0 Compatibility Updates
  README.md
  docs/compatibility.md
Labels: Documentation

#2343 Update constraint comment for consistency
  stablehlo/dialect/TypeInference.cpp
Labels: Cleanup/Refactoring

#2132 Add EvalIotaOp pattern to StablehloAggressiveFolder
  stablehlo/tests/stablehlo_aggressive_folder.mlir
  stablehlo/transforms/StablehloAggressiveFolder.cpp
Labels: Transformations

#2365 Integrate LLVM at llvm/llvm-project@9b79acedd689
  WORKSPACE.bazel
  build_tools/llvm_version.txt
Labels: Integrations

#2369 Make target-version required arg for `stablehlo_to_tf_saved_model` API
  stablehlo/integrations/python/stablehlo/savedmodel/stablehlo_to_tf_saved_model.py
  stablehlo/integrations/python/tests/stablehlo_to_tf_saved_model_test.py
Labels: Cleanup/Refactoring
