Repository openxla/stablehlo, pull requests merged in 2024-07, with the labels that each got.

#2421 Integrate LLVM at llvm/llvm-project@8598bcb9934d
  WORKSPACE.bazel
  build_tools/llvm_version.txt
Labels: Integrations

#2420 Cleanup StableHLO bytecode patches used for temporary pjrt compatibility
  stablehlo/conversions/linalg/transforms/StablehloLegalizeToLinalg.cpp
  stablehlo/dialect/AssemblyFormat.cpp
  stablehlo/dialect/AssemblyFormat.h
  stablehlo/dialect/StablehloAttrs.td
  stablehlo/dialect/StablehloBytecode.cpp
  stablehlo/dialect/StablehloOps.cpp
  stablehlo/dialect/StablehloOps.h
  stablehlo/dialect/StablehloOps.td
  stablehlo/tests/ops_stablehlo_roundtrip.mlir
  stablehlo/transforms/StablehloAggressiveSimplification.cpp
Labels: Compatibility, Cleanup/Refactoring

#2401 Python binding for stablehlo.register_passes
  BUILD.bazel
  stablehlo/integrations/c/CMakeLists.txt
  stablehlo/integrations/c/StablehloPasses.cpp
  stablehlo/integrations/c/StablehloPasses.h
  stablehlo/integrations/python/CMakeLists.txt
  stablehlo/integrations/python/StablehloModule.cpp
  stablehlo/integrations/python/tests/stablehlo.py
Labels: Transformations

#2096 [RFC] Add algorithm to dot_general's parameters in the StableHLO specification
  rfcs/20240315-algorithm-support.md
Labels: RFC

#2413 Adding multi-operation quantization tests
  stablehlo/testdata/quantized/integer_pow_dtypes_shape_float32_20_30__y_3_qi8.mlir
  stablehlo/testdata/quantized/integer_pow_dtypes_shape_float32_20_30__y_4_qi8.mlir
  stablehlo/testdata/quantized/integer_pow_overflow_shape_float32_20_30__y_127_qi8.mlir
Labels: Quantization

#2423 Bump patch version after integrate 1.1.7 -> 1.1.8
  stablehlo/dialect/Version.h
Labels: Integrations

#2428 Fix quant verification labels
  docs/spec.md
  stablehlo/dialect/Base.cpp
  stablehlo/tests/ops_stablehlo_quantized.mlir
Labels: Quantization

#2101 [RFC] Add TanOp to the StableHLO specification
  rfcs/20240312-tanop.md
Labels: RFC

#2438 Add better printing in reference interpreter, add tolerance to check almost eq
  stablehlo/reference/CMakeLists.txt
  stablehlo/reference/Element.cpp
  stablehlo/reference/Element.h
  stablehlo/reference/Tensor.cpp
  stablehlo/tests/CheckOps.cpp
  stablehlo/tests/CheckOps.h
  stablehlo/tests/CheckOps.td
  stablehlo/tests/interpret/check.mlir
  stablehlo/tests/interpret/printing.mlir
  stablehlo/tools/StablehloTranslateMain.cpp
Labels: Interpreter

#2444 Integrate LLVM at llvm/llvm-project@0913547d0e39
  WORKSPACE.bazel
  build_tools/llvm_version.txt
Labels: Integrations

#2448 MInor lint fix
  stablehlo/reference/Tensor.cpp
Labels: Cleanup/Refactoring

#2443 Make "Rendezvous" variadic
  stablehlo/reference/Ops.cpp
  stablehlo/reference/Process.cpp
  stablehlo/reference/Process.h
  stablehlo/reference/ProcessGrid.cpp
  stablehlo/reference/ProcessGrid.h
Labels: Interpreter

#2454 Integrate LLVM at llvm/llvm-project@dd7d81ea49bf
  WORKSPACE.bazel
  build_tools/llvm_version.txt
Labels: Integrations

#2455 Bump patch version after integrate 1.4.1 -> 1.4.2
  stablehlo/dialect/Version.h
Labels: Integrations

#2463 Integrate LLVM at llvm/llvm-project@84658fb82b67
  WORKSPACE.bazel
  build_tools/llvm_version.txt
  stablehlo/conversions/linalg/transforms/TypeConversion.cpp
  stablehlo/tests/vhlo/stablehlo_legalize_to_vhlo.0_18_0.mlir.bc
  stablehlo/tests/vhlo/stablehlo_legalize_to_vhlo.0_19_0.mlir.bc
  stablehlo/tests/vhlo/stablehlo_legalize_to_vhlo.0_20_0.mlir.bc
  stablehlo/tests/vhlo/stablehlo_legalize_to_vhlo.1_0_0.mlir.bc
  stablehlo/tests/vhlo/stablehlo_legalize_to_vhlo.1_1_0.mlir.bc
  stablehlo/tests/vhlo/stablehlo_legalize_to_vhlo.1_2_0.mlir.bc
  stablehlo/tests/vhlo/stablehlo_legalize_to_vhlo.1_3_0.mlir.bc
  stablehlo/tests/vhlo/stablehlo_legalize_to_vhlo.1_4_0.mlir.bc
  stablehlo/transforms/StablehloLegalizeQuantToInt.cpp
Labels: Integrations

#2464 Bump patch version after integrate 1.4.2 -> 1.4.3
  stablehlo/dialect/Version.h
Labels: Integrations

#2458 Merge qdq and quant-to-int passes
  BUILD.bazel
  docs/generated/stablehlo_passes.md
  stablehlo/tests/ops_stablehlo_quantized.mlir
  stablehlo/tests/stablehlo_legalize_quant_to_int.mlir
  stablehlo/tests/stablehlo_legalize_quantized_op_to_qdq.mlir
  stablehlo/transforms/CMakeLists.txt
  stablehlo/transforms/PassPipelines.cpp
  stablehlo/transforms/Passes.h
  stablehlo/transforms/Passes.td
  stablehlo/transforms/StablehloLegalizeQuantToMath.cpp
  stablehlo/transforms/StablehloLegalizeQuantizedOpToQDQ.cpp
Labels: Quantization

#2459 Support qdq decomposition of TanOp
  stablehlo/tests/stablehlo_legalize_quant_to_int.mlir
  stablehlo/transforms/StablehloLegalizeQuantizedOpToQDQ.cpp
Labels: Quantization

#2460 Remove type-inference dependency while creating qdq pattarns
  stablehlo/transforms/StablehloLegalizeQuantToMath.cpp
  stablehlo/transforms/StablehloLegalizeQuantizedOpToQDQ.cpp
Labels: Quantization

#2461 Support qdq decomposition of DotGeneralOp and ConvolutionOp
  stablehlo/tests/stablehlo_legalize_quant_to_int.mlir
  stablehlo/tests/stablehlo_legalize_quantized_op_to_qdq.mlir
  stablehlo/transforms/StablehloLegalizeQuantToMath.cpp
  stablehlo/transforms/StablehloLegalizeQuantizedOpToQDQ.cpp
Labels: Quantization

#2462 Remove the `qunt-to-math` pass limitation of Dot/Conv op result type
  stablehlo/tests/stablehlo_legalize_quant_to_int.mlir
  stablehlo/transforms/StablehloLegalizeQuantToMath.cpp
Labels: Quantization
