Repository openxla/stablehlo, pull requests merged in 2024-10, with the labels that each got.

#2567 Integrate LLVM at llvm/llvm-project@ac2a2816e3fe
  WORKSPACE.bazel
  build_tools/llvm_version.txt
  examples/c++/ExampleAdd.cpp
  stablehlo/conversions/tosa/transforms/StablehloQuantLegalizeToTosaRescale.cpp
  stablehlo/conversions/tosa/transforms/TosaRescaleLegalizeToStablehlo.cpp
  stablehlo/dialect/Base.cpp
  stablehlo/dialect/ChloOps.h
  stablehlo/dialect/Register.cpp
  stablehlo/dialect/StablehloOps.cpp
  stablehlo/dialect/StablehloOps.h
  stablehlo/dialect/TypeInference.cpp
  stablehlo/dialect/VhloTypes.cpp
  stablehlo/reference/Api.cpp
  stablehlo/tests/CheckOps.h
  stablehlo/tests/ops_stablehlo_quantized.mlir
  stablehlo/tools/StablehloTranslateMain.cpp
  stablehlo/transforms/Passes.h
  stablehlo/transforms/Passes.td
  stablehlo/transforms/StablehloLegalizeQDQToQuantizedOp.cpp
  stablehlo/transforms/StablehloLegalizeQuantToMath.cpp
  stablehlo/transforms/StablehloLegalizeQuantizedOpToQDQ.cpp
Labels: Integrations

#2568 apply patch for compatibility expander to support gather/scatter batc…
  stablehlo/tests/transforms/stablehlo_create_compatibility_expander.mlir
  stablehlo/transforms/StablehloCompatibilityExpander.cpp
  stablehlo/transforms/StablehloCreateCompatibilityExpander.cpp
Labels: Transformations

#2579 Bump 4w compat to v1.7.0 release Sept 05, 2024
  stablehlo/dialect/Version.cpp
Labels: Compatibility

#2584 Bump WEEK_12 compat to v1.3.0
  stablehlo/dialect/Version.cpp
Labels: Compatibility

#2587 Integrate LLVM at llvm/llvm-project@efcfa6e71168
  WORKSPACE.bazel
  build_tools/llvm_version.txt
Labels: Integrations

#2591 Bump patch version after integrate 1.7.8 -> 1.7.9
  stablehlo/dialect/Version.h
Labels: Integrations

#2605 Bump patch version after integrate 1.8.0 -> 1.8.1
  stablehlo/dialect/Version.h
Labels: Integrations

#2606 Integrate LLVM at llvm/llvm-project@ac4bd74190fe
  WORKSPACE.bazel
  build_tools/llvm_version.txt
Labels: Integrations

#2600 Add stablehlo-translate interpreter arg passing, complex types in reference APIs
  BUILD.bazel
  stablehlo/reference/Tensor.cpp
  stablehlo/tests/interpret/api_input_arguments.mlir
  stablehlo/tools/StablehloTranslateMain.cpp
Labels: Interpreter

#2610 Bump patch version after integrate 1.8.1 -> 1.8.2
  stablehlo/dialect/Version.h
Labels: Integrations

#2608 Add MHLO simplifications to StableHLO
  stablehlo/tests/transforms/stablehlo_aggressive_simplification.mlir
  stablehlo/transforms/Passes.td
  stablehlo/transforms/StablehloAggressiveSimplification.cpp
  stablehlo/transforms/StablehloAggressiveSimplificationPatterns.td
Labels: Transformations
