Repository openxla/stablehlo, pull requests merged in 2024-02, with the labels that each got.

#1977 Integrate LLVM at llvm/llvm-project@ca7fd2549238
  WORKSPACE.bazel
  build_tools/llvm_version.txt
Labels: Integrations

#1881 Dynamism RFC
  rfcs/20230704-dynamism-101.md
Labels: RFC

#1988 Bump patch version after integrate 0.17.6 -> 0.17.7
  stablehlo/dialect/Version.h
Labels: Integrations

#1990 Avoid duplicating extra class declarations
  stablehlo/dialect/ChloOps.td
  stablehlo/dialect/StablehloOps.td
Labels: Migrate to MHLO, Cleanup/Refactoring

#1983 Add interpreter for CollectiveBroadcastOp
  docs/status.md
  stablehlo/reference/Ops.cpp
  stablehlo/reference/Ops.h
  stablehlo/reference/ProcessGrid.cpp
  stablehlo/tests/interpret/collective_broadcast.mlir
Labels: Interpreter

#1993 Use default visibility for symbols
  stablehlo/tests/interpret/all_gather.mlir
  stablehlo/tests/interpret/all_reduce.mlir
  stablehlo/tests/interpret/all_to_all.mlir
  stablehlo/tests/interpret/collective_permute.mlir
  stablehlo/tests/interpret/infeed.mlir
  stablehlo/tests/interpret/outfeed.mlir
  stablehlo/tests/interpret/partition_id.mlir
  stablehlo/tests/interpret/reduce_scatter.mlir
  stablehlo/tests/interpret/replica_id.mlir
  stablehlo/tests/interpret/send_recv.mlir
Labels: Cleanup/Refactoring

#1987 Rename function to closely match spec
  stablehlo/reference/Element.cpp
  stablehlo/reference/Element.h
  stablehlo/reference/Ops.cpp
Labels: Interpreter

#1999 Convert lambda call to a function call
  stablehlo/dialect/TypeInference.cpp
Labels: Type inference, Cleanup/Refactoring

#2000 Rename function to match spec
  stablehlo/dialect/TypeInference.cpp
Labels: Cleanup/Refactoring

#2003 Integrate LLVM at llvm/llvm-project@2cbe5a33a5fd
  WORKSPACE.bazel
  build_tools/llvm_version.txt
  stablehlo/conversions/linalg/transforms/StablehloToLinalgConvolution.cpp
  stablehlo/conversions/linalg/transforms/StablehloToLinalgReduce.cpp
Labels: Integrations

#2008 Bump patch version after integrate 0.18.0 -> 0.18.1
  stablehlo/dialect/Version.h
Labels: Integrations

#2013 Integrate LLVM at llvm/llvm-project@d592c8ec8f71
  WORKSPACE.bazel
  build_tools/llvm_version.txt
Labels: Integrations

#2015 Align the definition of `checkIfOperandAndResultElementTypesMatch` with its name
  stablehlo/dialect/VhloOps.cpp
Labels: Cleanup/Refactoring

#2023 Bump patch version after integrate 0.18.1 -> 0.18.2
  stablehlo/dialect/Version.h
Labels: Integrations

#2029 Integrate LLVM at llvm/llvm-project@4c6043de0b83
  WORKSPACE.bazel
  build_tools/llvm_version.txt
Labels: Integrations

#2034 Bump patch version after integrate 0.18.2 -> 0.18.3
  stablehlo/dialect/Version.h
Labels: Integrations

#2035 Integrate LLVM at llvm/llvm-project@e899641df239
  WORKSPACE.bazel
  build_tools/llvm_version.txt
Labels: Integrations

#2036 Simplify creation of `TensorType` variants using `TensorType::clone`
  stablehlo/dialect/Base.cpp
  stablehlo/dialect/TypeInference.cpp
Labels: Cleanup/Refactoring

#2037 Specification of quantized collective_broadcast op
  docs/spec.md
Labels: Spec

#2048 Integrate LLVM at llvm/llvm-project@e630a451b457
  WORKSPACE.bazel
  build_tools/llvm_version.txt
Labels: Integrations

#2057 Bump patch version after integrate 0.18.3 -> 0.18.4
  stablehlo/dialect/Version.h
Labels: Integrations

#2033 Remove suffixes for files that already have a license
  build_tools/github_actions/lint_check_license.sh
Labels: Cleanup/Refactoring

#2027 Move reduce and while printing to AssemblyFormat to be shared with MHLO
  stablehlo/dialect/AssemblyFormat.cpp
  stablehlo/dialect/AssemblyFormat.h
  stablehlo/dialect/StablehloOps.cpp
  stablehlo/tests/print_reduce.mlir
  stablehlo/tests/verify_reduce.mlir
Labels: Prettyprinting

#2054 Check quantized-storage-type to be a signless integer
  stablehlo/dialect/Base.td
  stablehlo/tests/ops_stablehlo_quantized.mlir
Labels: Verification

#2056 Add pass to refine dynamic function parameters into static arguments
  BUILD.bazel
  stablehlo/tests/stablehlo_refine_parameters.mlir
  stablehlo/tests/stablehlo_refine_shapes.mlir
  stablehlo/transforms/CMakeLists.txt
  stablehlo/transforms/Passes.h
  stablehlo/transforms/Passes.td
  stablehlo/transforms/StablehloRefineArguments.cpp
  stablehlo/transforms/StablehloRefineShapes.cpp
  stablehlo/transforms/StablehloRefineShapes.h
Labels: Dynamism
