Repository openxla/stablehlo, pull requests merged in 2024-01, with the labels that each got.

#1897 Clarify semantics of `ReduceWindowOp` and `SelectAndScatterOp`
  docs/spec.md
Labels: Spec

#1904 Bump patch version after integrate 0.17.0 -> 0.17.1
  stablehlo/dialect/Version.h
Labels: Integrations

#1927 Bump patch version after integrate 0.17.2 -> 0.17.3
  stablehlo/dialect/Version.h
Labels: Integrations

#1928 Add missing copyright message
  docs/_toc.yaml
Labels: Integrations

#1932 Integrate LLVM at llvm/llvm-project@3a82a1c3f6bd
  WORKSPACE.bazel
  build_tools/llvm_version.txt
  stablehlo/conversions/linalg/tests/reduce.mlir
  stablehlo/transforms/StablehloRefineShapes.cpp
Labels: Integrations

#1935 Fix typo in the spec example for all_reduce
  docs/spec.md
Labels: Spec

#1938 Integrate LLVM at llvm/llvm-project@21830c913505
  WORKSPACE.bazel
  build_tools/llvm_version.txt
Labels: Integrations

#1943 Add missing spec example links
  docs/spec.md
Labels: Spec

#1944 Fix broken spec example links
  docs/spec.md
Labels: Spec

#1948 Integrate LLVM at llvm/llvm-project@98509c7f9792
  WORKSPACE.bazel
  build_tools/llvm_version.txt
Labels: Integrations

#1949 Fix clangtidy issue found in downstream integrate
  stablehlo/reference/Ops.cpp
Labels: Integrations

#1947 Notify before returning to avoid race condition
  stablehlo/reference/Ops.cpp
  stablehlo/reference/ProcessGrid.cpp
  stablehlo/reference/ProcessGrid.h
  stablehlo/tests/interpret/all_gather.mlir
Labels: Interpreter

#1957 Add CollectiveBroadcastOp to the status tracker
  docs/status.md
Labels: Process

#1968 Bump patch version after integrate 0.17.5 -> 0.17.6
  stablehlo/dialect/Version.h
Labels: Integrations
