Repository openxla/stablehlo, pull requests merged in 2024-09, with the labels that each got.

#2486 [RFC] Add f8E4M3 and f8E3M4 types support
  rfcs/20240808-f8E4M3_f8E3M4.md
Labels: RFC

#2522 [cmake] Remove dependence on LLVM 'Core' component in the CMake build
  stablehlo/conversions/linalg/transforms/CMakeLists.txt
  stablehlo/conversions/tosa/transforms/CMakeLists.txt
Labels: Build

#2523 Move StableHLO passes test files to a dedicated ./transforms dir
  stablehlo/tests/transforms/shape_legalize_to_stablehlo.mlir
  stablehlo/tests/transforms/stablehlo_aggressive_folder.mlir
  stablehlo/tests/transforms/stablehlo_aggressive_simplification.mlir
  stablehlo/tests/transforms/stablehlo_canonicalize_dynamism.mlir
  stablehlo/tests/transforms/stablehlo_convert_to_signless.mlir
  stablehlo/tests/transforms/stablehlo_legalize_composite_to_call.mlir
  stablehlo/tests/transforms/stablehlo_legalize_deprecated_ops.mlir
  stablehlo/tests/transforms/stablehlo_legalize_quant_to_int.mlir
  stablehlo/tests/transforms/stablehlo_legalize_quantized_op_to_qdq.mlir
  stablehlo/tests/transforms/stablehlo_probe_instrumentation.mlir
  stablehlo/tests/transforms/stablehlo_refine_parameters.mlir
  stablehlo/tests/transforms/stablehlo_refine_shapes.mlir
Labels: Transformations

#2527 Fix some warnings
  stablehlo/dialect/Version.cpp
  stablehlo/transforms/StablehloAggressiveFolder.cpp
Labels: Cleanup/Refactoring

#2548 Integrate LLVM at llvm/llvm-project@36adf8ecedb6
  WORKSPACE.bazel
  build_tools/llvm_version.txt
  stablehlo/conversions/tosa/tests/unary.mlir
  stablehlo/conversions/tosa/transforms/StablehloLegalizeToTosa.cpp
Labels: Integrations

#2550 Bump patch version after integrate 1.7.2 -> 1.7.3
  stablehlo/dialect/Version.h
Labels: Integrations

#2554 Integrate LLVM at llvm/llvm-project@94c024adedcb
  WORKSPACE.bazel
  build_tools/llvm_version.txt
Labels: Integrations

#2556 Bump patch version after integrate 1.7.3 -> 1.7.4
  stablehlo/dialect/Version.h
Labels: Integrations

#2558 Integrate LLVM at llvm/llvm-project@42b696d7b994
  WORKSPACE.bazel
  build_tools/llvm_version.txt
Labels: Integrations

#2560 Bump patch version after integrate 1.7.4 -> 1.7.5
  stablehlo/dialect/Version.h
Labels: Integrations

#2562 Integrate LLVM at llvm/llvm-project@29b92d07746f
  WORKSPACE.bazel
  build_tools/llvm_version.txt
Labels: Integrations

#2563 Bump patch version after integrate 1.7.5 -> 1.7.6
  stablehlo/dialect/Version.h
Labels: Integrations
