Repository openxla/stablehlo, pull requests merged in 2025-03, with the labels that each got.

#2734 Bump patch version after integrate 1.9.6 -> 1.9.7
  stablehlo/dialect/Version.cpp
  stablehlo/dialect/Version.h
Labels: Integrations

#2739 Integrate LLVM at llvm/llvm-project@e739ce2e10e6
  WORKSPACE.bazel
  build_tools/github_actions/ci_build_bazel.sh
  build_tools/llvm_version.txt
  docs/generated/chlo.md
  stablehlo/conversions/tosa/tests/legalize_quant_ops_to_tosa_rescale.mlir
  stablehlo/conversions/tosa/tests/legalize_tosa_rescale_to_stablehlo.mlir
  stablehlo/conversions/tosa/transforms/StablehloQuantLegalizeToTosaRescale.cpp
  stablehlo/dialect/Base.cpp
  stablehlo/dialect/Base.h
  stablehlo/dialect/ChloOps.cpp
  stablehlo/dialect/ChloOps.td
Labels: Integrations

#2741 Bump patch version after integrate 1.9.7 -> 1.9.8
  stablehlo/dialect/Version.h
Labels: Integrations

#2746 Fix Scatter Spec Diagram
  docs/images/spec/README.md
  docs/images/spec/scatter.svg
Labels: Spec

#2722 Pass to wrap StableHLO ops in composite
  BUILD.bazel
  docs/generated/stablehlo_passes.md
  stablehlo/tests/transforms/stablehlo_wrap_in_composite.mlir
  stablehlo/transforms/CMakeLists.txt
  stablehlo/transforms/Passes.h
  stablehlo/transforms/Passes.td
  stablehlo/transforms/StablehloWrapInComposite.cpp
Labels: Transformations

#2752 Integrate LLVM at llvm/llvm-project@0230d63b4a8b
  BUILD.bazel
  WORKSPACE.bazel
  build_tools/integrate/llvm_bump_revision.sh
  build_tools/llvm_version.txt
  docs/generated/stablehlo_tosa_passes.md
  stablehlo/conversions/tosa/tests/BUILD.bazel
  stablehlo/conversions/tosa/tests/lit.cfg.py
  stablehlo/conversions/tosa/transforms/CMakeLists.txt
  stablehlo/conversions/tosa/transforms/Passes.td
Labels: Integrations

#2723 Extend legalize-quant-to-math pass to support composite op
  stablehlo/tests/transforms/stablehlo_legalize_quant_to_int.mlir
  stablehlo/transforms/StablehloLegalizeQuantToMath.cpp
Labels: Transformations, Quantization

#2758 Integrate LLVM at llvm/llvm-project@dd3addf954ac
  BUILD.bazel
  WORKSPACE.bazel
  build_tools/llvm_version.txt
  docs/generated/stablehlo_tosa_passes.md
  stablehlo/conversions/tosa/tests/BUILD.bazel
  stablehlo/conversions/tosa/tests/lit.cfg.py
  stablehlo/conversions/tosa/transforms/CMakeLists.txt
  stablehlo/conversions/tosa/transforms/Passes.td
Labels: Integrations

#2759 Bump patch version after integrate 1.10.1 -> 1.10.2
  stablehlo/dialect/Version.h
Labels: Integrations

#2762 Integrate LLVM at llvm/llvm-project@ac9049df7e62
  WORKSPACE.bazel
  build_tools/llvm_version.txt
  stablehlo/conversions/tosa/tests/unary.mlir
Labels: Integrations
