Repository openxla/stablehlo, pull requests merged in 2025-01, with the labels that each got.

#2684 [StableHLO Quantization] Add quantization documentation
  docs/quantization.md
Labels: Quantization

#2686 Integrate LLVM at llvm/llvm-project@faa3f752896903
  WORKSPACE.bazel
  build_tools/llvm_version.txt
  build_tools/math/generate_ChloDecompositionPatternsMath.py
  build_tools/math/generate_tests.py
  stablehlo/conversions/linalg/transforms/TypeConversion.cpp
  stablehlo/conversions/tosa/transforms/StablehloLegalizeToTosa.cpp
  stablehlo/conversions/tosa/transforms/StablehloPrepareForTosa.cpp
  stablehlo/conversions/tosa/transforms/StablehloQuantLegalizeToTosaRescale.cpp
  stablehlo/conversions/tosa/transforms/TosaRescaleLegalizeToStablehlo.cpp
  stablehlo/tests/TestUtils.cpp
  stablehlo/tests/chlo/chlo_legalize_to_stablehlo.mlir
  stablehlo/tests/vhlo/stablehlo_legalize_to_vhlo.0_18_0.mlir.bc
  stablehlo/tests/vhlo/stablehlo_legalize_to_vhlo.0_19_0.mlir.bc
  stablehlo/tests/vhlo/stablehlo_legalize_to_vhlo.0_20_0.mlir.bc
  stablehlo/tests/vhlo/stablehlo_legalize_to_vhlo.1_0_0.mlir.bc
  stablehlo/tests/vhlo/stablehlo_legalize_to_vhlo.1_1_0.mlir.bc
  stablehlo/tests/vhlo/stablehlo_legalize_to_vhlo.1_2_0.mlir.bc
  stablehlo/tests/vhlo/stablehlo_legalize_to_vhlo.1_3_0.mlir.bc
  stablehlo/tests/vhlo/stablehlo_legalize_to_vhlo.1_4_0.mlir.bc
  stablehlo/tests/vhlo/stablehlo_legalize_to_vhlo.1_5_0.mlir.bc
  stablehlo/tests/vhlo/stablehlo_legalize_to_vhlo.1_6_0.mlir.bc
  stablehlo/tests/vhlo/stablehlo_legalize_to_vhlo.1_7_0.mlir.bc
  stablehlo/tests/vhlo/stablehlo_legalize_to_vhlo.1_8_0.mlir.bc
  stablehlo/transforms/StablehloAggressiveFolder.cpp
  stablehlo/transforms/StablehloAggressiveSimplification.cpp
  stablehlo/transforms/StablehloCanonicalizeDynamism.cpp
  stablehlo/transforms/StablehloCompatibilityExpander.cpp
  stablehlo/transforms/StablehloComplexMathExpander.cpp
  stablehlo/transforms/StablehloLegalizeQDQToQuantizedOp.cpp
  stablehlo/transforms/StablehloLegalizeQuantizedOpToQDQ.cpp
  stablehlo/transforms/StablehloRefineShapes.cpp
Labels: Integrations

#2689 Integrate LLVM at llvm/llvm-project@b270525f730b
  WORKSPACE.bazel
  build_tools/llvm_version.txt
  docs/spec.md
Labels: Integrations

#2691 Bump patch version after integrate 1.8.9 -> 1.8.10
  stablehlo/dialect/Version.cpp
  stablehlo/dialect/Version.h
Labels: Integrations

#2687 Add PrintOp to the Interpreter dialect
  stablehlo/reference/Api.cpp
  stablehlo/reference/InterpreterOps.cpp
  stablehlo/reference/InterpreterOps.h
  stablehlo/reference/InterpreterOps.td
Labels: Interpreter

#2693 Integrate LLVM at llvm/llvm-project@e2402615a5a7
  WORKSPACE.bazel
  build_tools/llvm_version.txt
  examples/c++/ExampleAdd.cpp
  stablehlo/conversions/tosa/tests/nullary.mlir
  stablehlo/conversions/tosa/transforms/StablehloLegalizeToTosa.cpp
  stablehlo/tests/chlo/chlo_legalize_to_stablehlo.mlir
  stablehlo/tests/interpret/chlo/ragged_dot.mlir
  stablehlo/tests/transforms/stablehlo_refine_parameters.mlir
  stablehlo/transforms/ChloLegalizeToStablehlo.cpp
  stablehlo/transforms/StablehloRefineArguments.cpp
  stablehlo/transforms/StablehloRefineShapes.cpp
  stablehlo/transforms/StablehloRefineShapes.h
Labels: Integrations

#2692 Bump patch version after integrate 1.8.10 -> 1.8.11
  stablehlo/dialect/Version.cpp
  stablehlo/dialect/Version.h
Labels: Integrations

#2695 Expose populateStablehloToLinalgConversionPatterns function
  stablehlo/conversions/linalg/transforms/Rewriters.h
  stablehlo/conversions/linalg/transforms/StablehloLegalizeToLinalg.cpp
Labels: Transformations

#2700 Bump patch version after integrate 1.8.11 -> 1.8.12
  stablehlo/dialect/Version.cpp
  stablehlo/dialect/Version.h
Labels: Integrations

#2701 Integrate LLVM at llvm/llvm-project@aa65f93b71de
  WORKSPACE.bazel
  build_tools/llvm_version.txt
  stablehlo/dialect/Base.cpp
  stablehlo/dialect/Base.h
  stablehlo/dialect/Base.td
  stablehlo/dialect/StablehloOps.td
  stablehlo/dialect/TypeInference.cpp
  stablehlo/dialect/Version.cpp
  stablehlo/dialect/VhloOps.cpp
  stablehlo/reference/Types.cpp
  stablehlo/tests/ops_stablehlo.mlir
  stablehlo/tests/ops_stablehlo_bounded_dynamism.mlir
  stablehlo/tests/transforms/stablehlo_aggressive_simplification.mlir
  stablehlo/transforms/Passes.h
  stablehlo/transforms/StablehloAggressiveSimplification.cpp
Labels: Integrations

#2703 Bump patch version after integrate 1.9.0 -> 1.9.1
  stablehlo/dialect/Version.h
Labels: Integrations
