Repository openxla/stablehlo, pull requests merged in 2025-02, with the labels that each got.

#2704 Integrate LLVM at llvm/llvm-project@956c0707d909
  WORKSPACE.bazel
  build_tools/llvm_version.txt
  stablehlo/conversions/tosa/tests/unary.mlir
  stablehlo/conversions/tosa/transforms/StablehloLegalizeToTosa.cpp
  stablehlo/conversions/tosa/transforms/StablehloLegalizeToTosa.pdll
Labels: Integrations

#2706 Bump patch version after integrate 1.9.1 -> 1.9.2
  stablehlo/dialect/Version.h
Labels: Integrations

#2707 Add target independent optimization pass
  BUILD.bazel
  build_tools/github_actions/ci_build_docs.sh
  docs/_toc.yaml
  docs/generated/stablehlo_optimization_passes.md
  docs/generated/stablehlo_passes.md
  stablehlo/tests/transforms/stablehlo_target_independent_optimization.mlir
  stablehlo/tools/StablehloOptMain.cpp
  stablehlo/transforms/CMakeLists.txt
  stablehlo/transforms/Passes.h
  stablehlo/transforms/Passes.td
  stablehlo/transforms/StablehloRefineShapes.cpp
  stablehlo/transforms/optimization/CMakeLists.txt
  stablehlo/transforms/optimization/Passes.h
  stablehlo/transforms/optimization/Passes.td
  stablehlo/transforms/optimization/StablehloAggressiveFolder.cpp
  stablehlo/transforms/optimization/StablehloAggressiveSimplification.cpp
  stablehlo/transforms/optimization/StablehloAggressiveSimplificationPatterns.td
  stablehlo/transforms/optimization/StablehloTargetIndependentOptimization.cpp
Labels: Transformations

#2712 Bump patch version after integrate 1.9.2 -> 1.9.3
  stablehlo/dialect/Version.cpp
  stablehlo/dialect/Version.h
Labels: Integrations

#2713 Integrate LLVM at llvm/llvm-project@0e779ad4998e
  BUILD.bazel
  WORKSPACE.bazel
  build_tools/llvm_version.txt
  docs/generated/interpreter_passes.md
  docs/generated/stablehlo_linalg_passes.md
  docs/generated/stablehlo_optimization_passes.md
  docs/generated/stablehlo_passes.md
  docs/generated/stablehlo_tosa_passes.md
  stablehlo/conversions/tosa/tests/binary.mlir
  stablehlo/conversions/tosa/transforms/StablehloLegalizeToTosa.cpp
  stablehlo/conversions/tosa/transforms/StablehloLegalizeToTosa.pdll
  stablehlo/dialect/Base.cpp
  stablehlo/dialect/Base.td
  stablehlo/dialect/StablehloOps.td
  stablehlo/tests/ops_stablehlo_quantized.mlir
Labels: Integrations

#2718 Fix the spec example of get_tuple_element
  docs/spec.md
Labels: Spec

#2719 Bump patch version after integrate 1.9.4 -> 1.9.5
  stablehlo/dialect/Version.h
Labels: Integrations

#2720 Integrate LLVM at llvm/llvm-project@d23da7d6300e
  WORKSPACE.bazel
  build_tools/llvm_version.txt
  stablehlo/tests/ops_stablehlo_bounded_dynamism.mlir
  stablehlo/tests/transforms/stablehlo_legalize_qdq_to_quantized_op.mlir
  stablehlo/transforms/StablehloLegalizeQDQToQuantizedOp.cpp
Labels: Integrations

#2730 Bump patch version after integrate 1.9.5 -> 1.9.6
  stablehlo/dialect/Version.cpp
  stablehlo/dialect/Version.h
Labels: Integrations
